import { createFileRoute, Link } from "@tanstack/react-router";
import { InfoPage } from "@/components/marketing/InfoPage";
import { Button } from "@/components/ui/button";
import { Tag } from "@/components/common/Primitives";

export const Route = createFileRoute("/developers")({ head: () => ({ meta: [{ title: "Developers — Aether AI Platform" }, { name: "description", content: "Build external applications on the Aether Ascension Intelligence API with scoped, revocable credentials." }] }), component: DevelopersPage });
function DevelopersPage() {
  return <InfoPage eyebrow="Developers" title="Build on Aether" description="External applications connect to Aether through the Aether Ascension Intelligence API. Applications remain independent of Aether user sessions and receive only capabilities authorized by their AAX API key."><div className="space-y-4">
    <div className="panel p-5"><h3 className="text-sm font-semibold">AAX Intelligence API</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Send authenticated JSON requests to <code className="font-mono text-xs text-primary">/api/v1/intelligence</code>. Aether authenticates the AAX key, enforces lifecycle, model lock, capability permissions, quota and atomic rate limits, validates the result and records durable request telemetry.</p><pre className="mt-4 overflow-x-auto rounded-lg border bg-elevated/30 p-4 font-mono text-xs leading-relaxed text-muted-foreground">{`POST /api/v1/intelligence\nAuthorization: Bearer AAX-<generation>.<revision>-<64-character-secret>\nContent-Type: application/json\nIdempotency-Key: <unique-request-key>\n\n{\n  "model": "<the model locked to your key>",\n  "messages": [{ "role": "user", "content": "Hello Aether" }]\n}`}</pre></div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="panel p-5"><h3 className="text-sm font-semibold">Key lifecycle</h3><ul className="mt-4 space-y-3 text-sm text-muted-foreground"><li>Secrets are cryptographically random and stored as a hash plus encrypted recovery copy.</li><li>Authorized owners can recover the complete secret; revoked credentials cannot authenticate.</li><li>Keys support active, suspended, revoked and expired states.</li><li>Rotation issues a replacement credential through the existing Z2 rotation workflow.</li><li>Requests are rate-limited, quota-accounted and durably audited.</li></ul><div className="mt-5 flex flex-wrap gap-2"><Tag tone="primary">REST / JSON</Tag><Tag>Idempotency</Tag><Tag>Audit</Tag></div></div><div className="panel p-5"><h3 className="text-sm font-semibold">Policy boundary</h3><p className="mt-2 text-sm text-muted-foreground">A key authorizes Aether capabilities; it never contains Aether intelligence, provider credentials or private platform secrets.</p><ul className="mt-4 space-y-2 text-xs text-muted-foreground"><li>• Model selection is locked to the key policy.</li><li>• Provider credentials stay server-side.</li><li>• Application and environment metadata are persisted.</li><li>• Research access is an explicit capability gate.</li></ul></div></div>
    <div className="panel p-5"><h3 className="text-sm font-semibold">Idempotency and errors</h3><p className="mt-2 text-sm text-muted-foreground">When an <code className="font-mono">Idempotency-Key</code> is supplied, Aether binds it to a SHA-256 request-body fingerprint for that API key. Reusing the same key with a different request body returns <code className="font-mono">409 idempotency_conflict</code>; an in-flight identical request returns a conflict; a completed request can be replayed.</p><p className="mt-3 text-xs text-muted-foreground">Common failures include invalid API key (401), inactive lifecycle (403), unauthorized capability (403), model lock violation (403), malformed JSON (400), quota exhaustion (429), rate limit exceeded (429), invalid model response (502) and provider/runtime failure (500/503 as applicable).</p></div>
    <div className="panel p-5"><h3 className="text-sm font-semibold">Streaming status</h3><p className="mt-2 text-sm text-muted-foreground">External streaming is not part of the published Z2 contract yet. A server-side provider streaming adapter exists for future use, but the public API does not advertise or expose it until quota accounting, cancellation, audit finalization and stream replay semantics are wired end-to-end.</p></div>
    <div className="flex flex-wrap gap-3"><Button asChild variant="outline"><Link to="/docs">API documentation</Link></Button><Button asChild><Link to="/login" search={{ redirect: "/api-keys" }}>Open AAX API keys</Link></Button></div>
  </div></InfoPage>;
}
