import { createFileRoute } from "@tanstack/react-router";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AdminShell } from "@/components/layout/AdminShell";
import { PageHeader,Panel,Tag } from "@/components/common/Primitives";
import { getAdminModels } from "@/lib/admin/console.functions";
import { updatePhaseUModel } from "@/lib/admin/phase-u.functions";
export const Route=createFileRoute("/_authenticated/admin/model-routing")({head:()=>({meta:[{title:"Model routing — Aether"},{name:"robots",content:"noindex"}]}),component:Page});
function Page(){const qc=useQueryClient();const load=useServerFn(getAdminModels);const update=useServerFn(updatePhaseUModel);const {data,isLoading}=useQuery({queryKey:["phase-u-models"],queryFn:()=>load({})});const act=async(roleKey:string,status:string)=>{try{await update({roleKey,status});await qc.invalidateQueries({queryKey:["phase-u-models"]});}catch(e){alert(e instanceof Error?e.message:"Model update failed");}};return <AdminShell><div className="space-y-6"><PageHeader eyebrow="AAX routing" title="Model routing" description="Administrator controls for Aether model roles, provider mapping, availability and routing priority." backFallback="/admin/models"/>{isLoading?<Panel><p className="text-sm text-muted-foreground">Loading model roles…</p></Panel>:<div className="grid gap-4 lg:grid-cols-2">{(data?.models??[]).map((m:any)=><Panel key={m.role_key} className="space-y-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{m.display_name}</h2><p className="mt-1 font-mono text-[10px] text-muted-foreground">{m.role_key}</p></div><Tag tone={m.status==="active"||m.status==="available"?"success":"neutral"}>{m.status??"unknown"}</Tag></div><div className="grid gap-3 text-xs sm:grid-cols-2"><div><p className="text-muted-foreground">Provider</p><p className="mt-1 font-medium">{m.provider??"Not configured"}</p></div><div><p className="text-muted-foreground">Provider model</p><p className="mt-1 font-medium">{m.provider_model??"Not configured"}</p></div><div><p className="text-muted-foreground">Routing priority</p><p className="mt-1 font-medium">{m.sort_order}</p></div><div><p className="text-muted-foreground">Telemetry</p><p className="mt-1 font-medium">{m.productivity?`${m.productivity.request_count} requests`:"No data"}</p></div></div><div className="flex flex-wrap gap-2"><button className="rounded border px-3 py-2 text-xs hover:bg-muted" onClick={()=>act(m.role_key,m.status==="active"?"disabled":"active")}>{m.status==="active"?"Disable role":"Enable role"}</button></div></Panel>)}</div>}<Panel><p className="text-[11px] text-muted-foreground">Provider credentials are not editable or displayed here. They remain server-side. AAX product roles remain separate from physical provider/model identifiers.</p></Panel></div></AdminShell>}
