import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AdminShell } from "@/components/layout/AdminShell";
import { PageHeader,Panel,Tag } from "@/components/common/Primitives";
import { getPhaseUUsers,setPhaseUUserRole,setPhaseUUserBan } from "@/lib/admin/phase-u.functions";
export const Route=createFileRoute("/_authenticated/admin/users")({head:()=>({meta:[{title:"Users — Aether"},{name:"robots",content:"noindex"}]}),component:Page});
function Page(){const qc=useQueryClient();const [search,setSearch]=useState("");const load=useServerFn(getPhaseUUsers);const role=useServerFn(setPhaseUUserRole);const ban=useServerFn(setPhaseUUserBan);const {data=[],isLoading}=useQuery({queryKey:["phase-u-users",search],queryFn:()=>load({search}),refetchInterval:30000});const act=async(fn:()=>Promise<any>)=>{try{await fn();await qc.invalidateQueries({queryKey:["phase-u-users"]});}catch(e){alert(e instanceof Error?e.message:"User action failed");}};return <AdminShell><div className="space-y-6"><PageHeader eyebrow="Identity control" title="Users" description="Secure account search, role administration and account status controls." backFallback="/admin"/><Panel><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by display name or email" className="w-full rounded-md border bg-background px-3 py-2 text-sm"/></Panel><Panel className="space-y-0 p-0">{isLoading?<p className="px-5 py-5 text-sm text-muted-foreground">Loading accounts…</p>:data.length===0?<p className="px-5 py-5 text-sm text-muted-foreground">No matching accounts.</p>:data.map((u:any,i:number)=><div key={u.id} className={`px-5 py-4 ${i<data.length-1?"border-b border-border/50":""}`}><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{u.displayName??u.email??u.id}</p><p className="truncate text-xs text-muted-foreground">{u.email??"—"} · joined {new Date(u.created_at).toLocaleDateString()}</p><p className="mt-1 text-[11px] text-muted-foreground">Last sign-in {u.lastSignInAt?new Date(u.lastSignInAt).toLocaleString():"never"}</p></div><div className="flex flex-wrap gap-1.5">{(u.roles??[]).map((r:string)=><Tag key={r} tone={r==="admin"?"admin":"primary"}>{r}</Tag>)}{u.roles?.length===0&&<Tag>user</Tag>}{u.bannedUntil&&<Tag tone="danger">banned</Tag>}</div></div><div className="mt-3 flex flex-wrap gap-2"><button className="rounded border px-2 py-1 text-xs hover:bg-muted" onClick={()=>act(()=>role({userId:u.id,role:u.roles?.includes("admin")?"user":"admin"}))}>{u.roles?.includes("admin")?"Remove admin":"Grant admin"}</button><button className="rounded border px-2 py-1 text-xs hover:bg-muted" onClick={()=>act(()=>ban({userId:u.id,banned:!u.bannedUntil}))}>{u.bannedUntil?"Unban":"Ban"}</button></div></div>)}</Panel></div></AdminShell>}
