import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { PageHeader, Panel, Tag, EmptyState } from "@/components/common/Primitives";
import { Button } from "@/components/ui/button";
import { createMyZ2ApiKey, getMyZ2ApiKeySecret, getMyZ2UsageForecast, listMyZ2ApiKeys, listMyZ2Models, listMyZ2RequestRecords, revokeMyZ2ApiKey, rotateMyZ2ApiKey, suspendMyZ2ApiKey } from "@/lib/aether/phase-z2-api.functions";

export const Route = createFileRoute("/_authenticated/api-keys")({ head: () => ({ meta: [{ title: "API Keys — Aether" }, { name: "description", content: "Manage Aether Ascension Intelligence API credentials." }] }), component: Page });
const environments = ["development", "test", "production"] as const;
function Page() {
  const qc = useQueryClient();
  const list = useServerFn(listMyZ2ApiKeys), models = useServerFn(listMyZ2Models), create = useServerFn(createMyZ2ApiKey), recover = useServerFn(getMyZ2ApiKeySecret), revoke = useServerFn(revokeMyZ2ApiKey), suspend = useServerFn(suspendMyZ2ApiKey), rotate = useServerFn(rotateMyZ2ApiKey), forecast = useServerFn(getMyZ2UsageForecast), requests = useServerFn(listMyZ2RequestRecords);
  const { data: keys = [], isLoading } = useQuery({ queryKey: ["z2-api-keys"], queryFn: () => list({}) });
  const { data: modelList = [] } = useQuery({ queryKey: ["z2-models"], queryFn: () => models({}) });
  const [name, setName] = useState(""), [application, setApplication] = useState(""), [environment, setEnvironment] = useState<(typeof environments)[number]>("development"), [modelKey, setModelKey] = useState(""), [expiresAt, setExpiresAt] = useState(""), [newKey, setNewKey] = useState<string | null>(null), [busy, setBusy] = useState(false), [selectedKey, setSelectedKey] = useState<string | null>(null);
  const [activity, setActivity] = useState<any[]>([]);
  const make = async () => { setBusy(true); try { const chosen = modelKey || (modelList[0] as any)?.model_key; if (!chosen) throw new Error("No AAX model is currently available"); const r = await create({ data: { name, applicationName: application, environment, modelKey: chosen, expiresAt: expiresAt ? new Date(expiresAt).toISOString() : null } }); setNewKey(r.key); setName(""); setApplication(""); await qc.invalidateQueries({ queryKey: ["z2-api-keys"] }); } catch (e) { alert(e instanceof Error ? e.message : "API key creation failed"); } finally { setBusy(false); } };
  const reveal = async (keyId: string) => { try { const r = await recover({ data: { keyId } }); setNewKey(r.key); await navigator.clipboard?.writeText(r.key); } catch (e) { alert(e instanceof Error ? e.message : "Unable to recover API key"); } };
  const loadActivity = async (keyId: string) => { try { setSelectedKey(keyId); setActivity(await requests({ data: { keyId } })); } catch (e) { alert(e instanceof Error ? e.message : "Unable to load request history"); } };
  return <AppShell><PageHeader title="API Keys" description="Aether Ascension Intelligence API credentials, models, usage and request history." backFallback="/dashboard"/><div className="mt-6 space-y-5">
    <Panel><h2 className="text-sm font-semibold">Create Aether API key</h2><p className="mt-1 text-xs text-muted-foreground">Choose the Ascension model this credential is locked to, name the application, choose its environment, and optionally set an expiration.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="h-9 rounded-md border bg-background px-3 text-sm" value={name} onChange={e=>setName(e.target.value)} placeholder="Key nickname" maxLength={120}/><input className="h-9 rounded-md border bg-background px-3 text-sm" value={application} onChange={e=>setApplication(e.target.value)} placeholder="Application name" maxLength={160}/><select className="h-9 rounded-md border bg-background px-3 text-sm" value={environment} onChange={e=>setEnvironment(e.target.value as any)}>{environments.map(e=><option key={e} value={e}>{e}</option>)}</select><select className="h-9 rounded-md border bg-background px-3 text-sm" value={modelKey} onChange={e=>setModelKey(e.target.value)}><option value="">Choose Ascension model</option>{(modelList as any[]).map(m=><option key={m.model_key} value={m.model_key}>{m.display_name ?? m.model_key} · {m.generation}.{m.revision}</option>)}</select><input className="h-9 rounded-md border bg-background px-3 text-sm" type="datetime-local" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)} aria-label="Expiration"/></div><Button className="mt-4" disabled={busy||!name.trim()||!application.trim()||!modelList.length} onClick={()=>void make()}>Generate Aether API key</Button>{newKey?<div className="mt-4 rounded-lg border p-3"><p className="text-xs font-semibold">Your API key</p><code className="mt-2 block break-all text-xs">{newKey}</code><Button className="mt-3" size="sm" variant="outline" onClick={()=>void navigator.clipboard?.writeText(newKey)}>Copy API key</Button></div>:null}</Panel>
    <Panel><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Your Aether Intelligence keys</h2><p className="mt-1 text-xs text-muted-foreground">Free accounts: up to 5 active keys, 200,000 monthly tokens per key.</p></div></div>{isLoading?<p className="mt-4 text-sm text-muted-foreground">Loading…</p>:keys.length===0?<EmptyState title="No Aether API keys" description="Create a key to connect an independent application to AAX intelligence."/>:<div className="mt-4 divide-y divide-border">{(keys as any[]).map(k=><div key={k.id} className="py-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{k.name}</p><p className="font-mono text-[11px] text-muted-foreground">{k.key_prefix}•••• · {k.model_key} · {k.environment}</p><p className="text-[11px] text-muted-foreground">{k.application_name} · Last used {k.last_used_at?new Date(k.last_used_at).toLocaleString():"never"}</p><p className="text-[11px] text-muted-foreground">Tokens: {k.tokensRemaining===null?"Unlimited":`${k.usage?.tokens_consumed??0} consumed / ${k.monthly_token_limit} allocated · ${k.tokensRemaining} remaining`} · Requests: {k.usage?.request_count??0}</p></div><Tag tone={k.status==="active"?"success":k.status==="suspended"?"warning":"neutral"}>{k.status}</Tag></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>void reveal(k.id)}>Copy API key</Button><Button size="sm" variant="outline" onClick={()=>void loadActivity(k.id)}>View activity</Button>{k.status==="active"?<Button size="sm" variant="outline" onClick={async()=>{try{await suspend({data:{keyId:k.id,suspend:true}});await qc.invalidateQueries({queryKey:["z2-api-keys"]})}catch(e){alert(e instanceof Error?e.message:"Unable to suspend key")}}}>Suspend</Button>:k.status==="suspended"?<Button size="sm" variant="outline" onClick={async()=>{try{await suspend({data:{keyId:k.id,suspend:false}});await qc.invalidateQueries({queryKey:["z2-api-keys"]})}catch(e){alert(e instanceof Error?e.message:"Unable to resume key")}}}>Resume</Button>:null}{k.status!=="revoked"&&<><Button size="sm" variant="outline" onClick={async()=>{try{const r=await rotate({data:{keyId:k.id}});setNewKey(r.key);await qc.invalidateQueries({queryKey:["z2-api-keys"]})}catch(e){alert(e instanceof Error?e.message:"Unable to rotate key")}}}>Rotate</Button><Button size="sm" variant="ghost" onClick={async()=>{try{await revoke({data:{keyId:k.id}});await qc.invalidateQueries({queryKey:["z2-api-keys"]})}catch(e){alert(e instanceof Error?e.message:"Unable to revoke key")}}}>Revoke</Button></>}</div></div>)}</div>}</Panel>
    {selectedKey?<Panel><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Request explorer</h2><Button size="sm" variant="ghost" onClick={()=>setSelectedKey(null)}>Close</Button></div><div className="mt-3 space-y-2">{activity.length===0?<p className="text-xs text-muted-foreground">No requests recorded for this key.</p>:activity.map((r:any)=><div key={r.id} className="rounded border p-3 text-xs"><div className="flex justify-between gap-3"><span className="font-mono">{r.request_id}</span><span>{r.status_code} · {r.latency_ms??"—"}ms</span></div><p className="mt-1 text-muted-foreground">{r.model_key} · {r.outcome} · {r.tokens_total??0} tokens · {new Date(r.created_at).toLocaleString()}</p></div>)}</div></Panel>:null}
    <Panel><h2 className="text-sm font-semibold">Usage forecast</h2><p className="mt-1 text-xs text-muted-foreground">Seven-day usage trend projected forward; actual usage remains authoritative.</p><Button className="mt-3" size="sm" variant="outline" onClick={async()=>{try{const r=await forecast({});alert(`7d: ${r.tokens} tokens across ${r.requests} requests. Projected 30d: ${r.projectedMonthlyTokens} tokens.`)}catch(e){alert(e instanceof Error?e.message:"Unable to load usage forecast")}}}>View forecast</Button></Panel>
  </div></AppShell>;
}
