import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Archive, FolderKanban, Pencil, Plus, RotateCcw, Trash2, Upload, X } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { EmptyState, PageHeader, Panel, StatCard, Tag } from "@/components/common/Primitives";
import { Button } from "@/components/ui/button";
import { createAetherProject, deleteAetherProject, getAetherProjectFileDownloadUrl, getAetherProjectWorkspace, listAetherProjects, archiveAetherProject, registerAetherProjectFile, restoreAetherProject, updateAetherProject, deleteAetherProjectFile } from "@/lib/aether/aether-project.functions";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/projects")({ head: () => ({ meta: [{ title: "Projects — Aether" }, { name: "description", content: "Persistent projects with isolated conversations, memory and files." }] }), component: Page });

type Project = { id: string; name: string; slug: string; description: string | null; project_type: string; status: string; archived: boolean; memory_enabled: boolean; created_at: string; updated_at: string };
type Workspace = { project: Project; files: { id: string; filename: string; mime_type: string; size_bytes: number; extraction_status: string; created_at: string }[]; memories: { id: string; content: string; memory_type: string; version: number }[]; conversations: { id: string; title: string; updated_at: string; archived: boolean }[] };

function Page() {
  const qc = useQueryClient(); const getProjects = useServerFn(listAetherProjects); const createProject = useServerFn(createAetherProject); const updateProject = useServerFn(updateAetherProject); const archiveProject = useServerFn(archiveAetherProject); const restoreProject = useServerFn(restoreAetherProject); const deleteProject = useServerFn(deleteAetherProject); const getWorkspace = useServerFn(getAetherProjectWorkspace); const registerFile = useServerFn(registerAetherProjectFile); const deleteFile = useServerFn(deleteAetherProjectFile); const getFileUrl = useServerFn(getAetherProjectFileDownloadUrl);
  const { data: projects = [] } = useQuery({ queryKey: ["aether-projects-page"], queryFn: () => getProjects({ data: { includeArchived: true } }) as Promise<Project[]> }); const [selectedId, setSelectedId] = useState<string | null>(null); const { data: workspace } = useQuery({ queryKey: ["aether-project-workspace", selectedId], queryFn: () => getWorkspace({ data: { projectId: selectedId! } }) as Promise<Workspace>, enabled: Boolean(selectedId) });
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [editing, setEditing] = useState<Project | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const activeProjects = useMemo(() => projects.filter((p) => !p.archived), [projects]);
  function resetForm() { setEditing(null); setName(""); setDescription(""); }
  async function save() { const value = name.trim(); if (!value) return; setBusy(true); setError(""); try { if (editing) await updateProject({ data: { projectId: editing.id, name: value, description } }); else { const p = await createProject({ data: { name: value, description } }); setSelectedId(p.id); } resetForm(); await qc.invalidateQueries({ queryKey: ["aether-projects-page"] }); } catch (e) { setError(e instanceof Error ? e.message : "Could not save project."); } finally { setBusy(false); } }
  async function archive(id: string) { await archiveProject({ data: { projectId: id } }); if (selectedId === id) setSelectedId(null); await qc.invalidateQueries({ queryKey: ["aether-projects-page"] }); }
  async function restore(id: string) { await restoreProject({ data: { projectId: id } }); await qc.invalidateQueries({ queryKey: ["aether-projects-page"] }); }
  async function remove(id: string) { if (!window.confirm("Permanently delete this project and its project-scoped memory/files?")) return; await deleteProject({ data: { projectId: id } }); if (selectedId === id) setSelectedId(null); await qc.invalidateQueries({ queryKey: ["aether-projects-page"] }); }
  async function upload(file: File) { if (!workspace || file.size > 25 * 1024 * 1024) { setError("Project files are limited to 25 MB."); return; } const user = (await supabase.auth.getUser()).data.user; if (!user) { setError("Authentication expired."); return; } const path = `${user.id}/${workspace.project.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const up = await supabase.storage.from("aether-project-files").upload(path, file, { contentType: file.type, upsert: false }); if (up.error) { setError(up.error.message); return; } try { await registerFile({ data: { projectId: workspace.project.id, storagePath: path, filename: file.name, mimeType: file.type || "application/octet-stream", sizeBytes: file.size } }); await qc.invalidateQueries({ queryKey: ["aether-project-workspace", selectedId] }); } catch (e) { await supabase.storage.from("aether-project-files").remove([path]); setError(e instanceof Error ? e.message : "Could not register project file."); } }
  return <AppShell><PageHeader title="Projects" description="Persistent workspaces with isolated conversations, memory and files." actions={<Button size="sm" onClick={resetForm}><Plus className="mr-1.5 h-4 w-4" />New project</Button>} />
  <div className="mt-6 grid gap-4 sm:grid-cols-3"><StatCard label="Active projects" value={String(activeProjects.length)} hint="Owned by the current user" tone="primary" /><StatCard label="Selected memories" value={String(workspace?.memories.length ?? 0)} hint="Project-scoped active memories" /><StatCard label="Project files" value={String(workspace?.files.length ?? 0)} hint="Private storage" /></div>
  {error ? <div className="mt-4 flex items-center justify-between rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive"><span>{error}</span><button onClick={() => setError("")}><X className="h-4 w-4" /></button></div> : null}
  <div className="mt-6 grid gap-5 lg:grid-cols-[340px_minmax(0,1fr)]"><div className="space-y-3"><Panel><h2 className="text-sm font-semibold">{editing ? "Edit project" : "Create project"}</h2><div className="mt-3 space-y-2"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Project name" maxLength={120} className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm"/><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description" maxLength={1000} rows={4} className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm"/><div className="flex gap-2"><Button disabled={busy || !name.trim()} onClick={() => void save()}>{editing ? "Save changes" : "Create project"}</Button>{editing ? <Button variant="ghost" onClick={resetForm}>Cancel</Button> : null}</div></div></Panel>
  {projects.length ? projects.map((p) => <button key={p.id} type="button" onClick={() => setSelectedId(p.id)} className={`w-full rounded-xl border p-4 text-left transition-colors ${selectedId === p.id ? "border-primary/40 bg-primary/5" : "border-border bg-card hover:bg-muted/30"}`}><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-border bg-muted/40 text-primary"><FolderKanban className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="truncate text-sm font-medium">{p.name}</span><Tag tone={p.archived ? "neutral" : "success"}>{p.archived ? "ARCHIVED" : "ACTIVE"}</Tag></div><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{p.description || "No description"}</p></div></div></button>) : <EmptyState title="No projects" description="Create your first project to isolate context, memory and files." icon={<FolderKanban className="h-5 w-5" />} />}</div>
  <div>{workspace ? <div className="space-y-4"><Panel><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">{workspace.project.name}</h2><Tag>{workspace.project.project_type}</Tag></div><p className="mt-1 text-sm text-muted-foreground">{workspace.project.description || "No description"}</p><p className="mt-2 text-[11px] text-muted-foreground">Memory {workspace.project.memory_enabled ? "enabled" : "disabled"} · Created {new Date(workspace.project.created_at).toLocaleDateString()}</p></div><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => { setEditing(workspace.project); setName(workspace.project.name); setDescription(workspace.project.description || ""); }}> <Pencil className="mr-1 h-3.5 w-3.5"/>Edit</Button>{workspace.project.archived ? <Button size="sm" variant="ghost" onClick={() => void restore(workspace.project.id)}><RotateCcw className="mr-1 h-3.5 w-3.5"/>Restore</Button> : <Button size="sm" variant="ghost" onClick={() => void archive(workspace.project.id)}><Archive className="mr-1 h-3.5 w-3.5"/>Archive</Button>}<Button size="icon" variant="ghost" onClick={() => void remove(workspace.project.id)}><Trash2 className="h-4 w-4"/></Button></div></div></Panel>
  <Panel><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Project files</h3><p className="mt-1 text-xs text-muted-foreground">Private, project-scoped storage. Maximum 25 MB per file.</p></div><label className="inline-flex cursor-pointer items-center rounded-md border border-border px-3 py-2 text-xs hover:bg-muted/40"><Upload className="mr-1.5 h-3.5 w-3.5"/>Upload<input type="file" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) void upload(f); e.currentTarget.value = ""; }}/></label></div>{workspace.files.length ? <div className="mt-4 divide-y divide-border">{workspace.files.map((f) => <div key={f.id} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm">{f.filename}</p><p className="text-[11px] text-muted-foreground">{Math.round(f.size_bytes / 1024)} KB · {f.extraction_status}</p></div><Button size="sm" variant="ghost" onClick={async () => { const r = await getFileUrl({ data: { fileId: f.id } }); window.open(r.url, "_blank", "noopener,noreferrer"); }}>Open</Button><Button size="icon" variant="ghost" onClick={async () => { await deleteFile({ data: { fileId: f.id } }); await qc.invalidateQueries({ queryKey: ["aether-project-workspace", selectedId] }); }}><Trash2 className="h-4 w-4"/></Button></div>)}</div> : <p className="mt-4 text-xs text-muted-foreground">No files in this project.</p>}</Panel>
  <Panel><h3 className="text-sm font-semibold">Project memory</h3><p className="mt-1 text-xs text-muted-foreground">Only active memory belonging to this project is shown here.</p>{workspace.memories.length ? <div className="mt-3 space-y-2">{workspace.memories.slice(0,8).map((m) => <div key={m.id} className="rounded-lg border border-border p-3"><div className="flex items-center gap-1.5"><Tag tone="primary">{m.memory_type}</Tag><Tag>v{m.version}</Tag></div><p className="mt-2 text-sm">{m.content}</p></div>)}</div> : <p className="mt-4 text-xs text-muted-foreground">No project memory yet.</p>}</Panel>
  <Panel><h3 className="text-sm font-semibold">Conversations</h3>{workspace.conversations.length ? <div className="mt-3 space-y-1">{workspace.conversations.map((c) => <div key={c.id} className="flex items-center justify-between rounded-md px-3 py-2 hover:bg-muted/30"><span className="truncate text-sm">{c.title}</span><span className="ml-3 shrink-0 text-[11px] text-muted-foreground">{new Date(c.updated_at).toLocaleDateString()}</span></div>)}</div> : <p className="mt-4 text-xs text-muted-foreground">No conversations in this project.</p>}</Panel></div> : <EmptyState title="Select a project" description="Choose a project to inspect its isolated context, memory, files and conversations." icon={<FolderKanban className="h-5 w-5" />} />}</div></div></AppShell>;
}
