import { createServerFn } from "@tanstack/react-start";
import type { SupabaseClient } from "@supabase/supabase-js";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { executeAaxChat } from "./aax-gateway";
import { executeAaxWebResearch } from "./aax-web-research";

const MAX_MESSAGE_CHARS = 32_000;
const MAX_HISTORY_MESSAGES = 40;
const db = (value: unknown) => value as SupabaseClient;
type SendInput = { conversationId?: string; modelKey?: string; message?: string; attachmentIds?: string[]; regenerateMessageId?: string; projectId?: string | null; webResearch?: boolean; memoryEnabled?: boolean; temperature?: number; maxOutputTokens?: number };

async function assertProject(client: SupabaseClient, projectId: string | null | undefined, userId: string) {
  if (!projectId) return null;
  const { data, error } = await client.from("projects").select("id,name,slug,description,status,archived").eq("id", projectId).eq("owner_id", userId).eq("archived", false).maybeSingle();
  if (error || !data) throw new Response("Project not found or not owned by the current user", { status: 404 });
  return data;
}
async function getOwnedConversation(client: SupabaseClient, conversationId: string, userId: string) {
  const { data, error } = await client.from("aax_conversations").select("id,owner_id,model_id,title,archived,project_id,memory_enabled,web_research_enabled,aax_models(model_key,display_name,generation,revision)").eq("id", conversationId).eq("owner_id", userId).maybeSingle();
  if (error || !data) throw new Response("Conversation not found", { status: 404 });
  return data;
}

export const listAaxProjects = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => {
  const { data, error } = await db(context.supabase).from("projects").select("id,name,slug,description,status,archived,updated_at").eq("owner_id", context.userId).eq("archived", false).order("updated_at", { ascending: false }).limit(100);
  if (error) throw new Response(`Could not load projects: ${error.message}`, { status: 500 }); return data ?? [];
});

export const listAaxConversations = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).validator((input?: { search?: string; cursor?: string | null; limit?: number }) => input ?? {}).handler(async ({ context, data }) => {
  const limit = Math.min(Math.max(data.limit ?? 50, 1), 100); const search = data.search?.trim();
  let query = db(context.supabase).from("aax_conversations").select("id,model_id,title,archived,project_id,memory_enabled,web_research_enabled,last_message_at,created_at,updated_at,aax_models(model_key,display_name,generation,revision)").eq("owner_id", context.userId).eq("archived", false).order("updated_at", { ascending: false }).limit(limit + 1);
  if (search) query = query.ilike("title", `%${search.replace(/[%_]/g, "\\$&")}%`); if (data.cursor) query = query.lt("updated_at", data.cursor);
  const { data: rows, error } = await query; if (error) throw new Response(`Could not load conversations: ${error.message}`, { status: 500 });
  const list = rows ?? []; return { conversations: list.slice(0, limit), nextCursor: list.length > limit ? list[limit - 1]?.updated_at ?? null : null };
});

export const getAaxConversation = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).validator((input: { conversationId: string }) => input).handler(async ({ context, data }) => {
  const conversation = await getOwnedConversation(db(context.supabase), data.conversationId, context.userId);
  const { data: messages, error } = await db(context.supabase).from("aax_conversation_messages").select("id,role,content,metadata,created_at").eq("conversation_id", data.conversationId).eq("owner_id", context.userId).order("created_at", { ascending: true });
  if (error) throw new Response(`Could not load messages: ${error.message}`, { status: 500 });
  const { data: sources, error: sourceError } = await db(context.supabase).from("aax_chat_sources").select("id,message_id,url,title,domain,snippet,citation_index,created_at").eq("conversation_id", data.conversationId).eq("owner_id", context.userId).order("citation_index", { ascending: true });
  if (sourceError) throw new Response(`Could not load sources: ${sourceError.message}`, { status: 500 });
  const { data: attachments, error: attachmentError } = await db(context.supabase).from("aax_chat_attachments").select("id,message_id,filename,mime_type,size_bytes,extraction_status,metadata,created_at").eq("conversation_id", data.conversationId).eq("owner_id", context.userId).order("created_at", { ascending: true });
  if (attachmentError) throw new Response(`Could not load attachments: ${attachmentError.message}`, { status: 500 });
  return { conversation, messages: messages ?? [], sources: sources ?? [], attachments: attachments ?? [] };
});

export const createAaxConversation = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { modelKey: string; title?: string; projectId?: string | null; memoryEnabled?: boolean; webResearchEnabled?: boolean }) => input).handler(async ({ context, data }) => {
  await assertProject(db(context.supabase), data.projectId, context.userId);
  const { data: model, error: modelError } = await supabaseAdmin.from("aax_models").select("id,model_key,release_status").eq("model_key", data.modelKey).maybeSingle();
  if (modelError || !model) throw new Response("AAX model not found", { status: 404 });
  const { data: created, error } = await supabaseAdmin.from("aax_conversations").insert({ owner_id: context.userId, model_id: model.id, title: data.title?.trim().slice(0, 120) || "New conversation", project_id: data.projectId ?? null, memory_enabled: data.memoryEnabled ?? true, web_research_enabled: data.webResearchEnabled ?? false }).select("id").single();
  if (error || !created) throw new Response(`Could not create conversation: ${error?.message ?? "unknown error"}`, { status: 500 }); return { conversationId: created.id };
});
export const renameAaxConversation = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { conversationId: string; title: string }) => input).handler(async ({ context, data }) => { const title = data.title.trim().slice(0, 120); if (!title) throw new Response("Title is required", { status: 400 }); const { error } = await db(context.supabase).from("aax_conversations").update({ title, updated_at: new Date().toISOString() }).eq("id", data.conversationId).eq("owner_id", context.userId); if (error) throw new Response(`Could not rename conversation: ${error.message}`, { status: 500 }); return { ok: true }; });
export const archiveAaxConversation = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { conversationId: string }) => input).handler(async ({ context, data }) => { const { error } = await db(context.supabase).from("aax_conversations").update({ archived: true, archived_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", data.conversationId).eq("owner_id", context.userId); if (error) throw new Response(`Could not archive conversation: ${error.message}`, { status: 500 }); return { ok: true }; });
export const deleteAaxConversation = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { conversationId: string }) => input).handler(async ({ context, data }) => { const client = db(context.supabase); const conversation = await getOwnedConversation(client, data.conversationId, context.userId); const { data: attachments } = await client.from("aax_chat_attachments").select("storage_path").eq("conversation_id", conversation.id).eq("owner_id", context.userId); if (attachments?.length) await supabaseAdmin.storage.from("aax-chat-attachments").remove(attachments.map((item) => item.storage_path)); const { error } = await client.from("aax_conversations").delete().eq("id", data.conversationId).eq("owner_id", context.userId); if (error) throw new Response(`Could not delete conversation: ${error.message}`, { status: 500 }); return { ok: true }; });
export const updateAaxConversationSettings = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { conversationId: string; projectId?: string | null; memoryEnabled?: boolean; webResearchEnabled?: boolean }) => input).handler(async ({ context, data }) => { await getOwnedConversation(db(context.supabase), data.conversationId, context.userId); if (data.projectId !== undefined) await assertProject(db(context.supabase), data.projectId, context.userId); const patch: Record<string, unknown> = { updated_at: new Date().toISOString() }; if (data.projectId !== undefined) patch.project_id = data.projectId; if (data.memoryEnabled !== undefined) patch.memory_enabled = data.memoryEnabled; if (data.webResearchEnabled !== undefined) patch.web_research_enabled = data.webResearchEnabled; const { error } = await db(context.supabase).from("aax_conversations").update(patch).eq("id", data.conversationId).eq("owner_id", context.userId); if (error) throw new Response(`Could not update conversation settings: ${error.message}`, { status: 500 }); return { ok: true }; });
export const stopAaxGeneration = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { runId: string }) => input).handler(async ({ context, data }) => { const { error } = await db(context.supabase).from("aax_chat_generation_runs").update({ status: "cancelled", completed_at: new Date().toISOString(), error: "Cancelled by user" }).eq("id", data.runId).eq("owner_id", context.userId).eq("status", "running"); if (error) throw new Response(`Could not stop generation: ${error.message}`, { status: 500 }); return { ok: true }; });
export const saveAaxMemoryCandidate = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { conversationId: string; messageId: string; content: string }) => input).handler(async ({ context, data }) => { const client = db(context.supabase); await getOwnedConversation(client, data.conversationId, context.userId); const content = data.content.trim().slice(0, 12000); if (!content) throw new Response("Memory content is required", { status: 400 }); const { data: candidate, error } = await client.from("aax_chat_memory_candidates").insert({ conversation_id: data.conversationId, message_id: data.messageId, owner_id: context.userId, content, status: "candidate" }).select("id,status").single(); if (error || !candidate) throw new Response(`Could not save memory candidate: ${error?.message ?? "unknown error"}`, { status: 500 }); return candidate; });

export const registerAaxAttachment = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { conversationId: string; storagePath: string; filename: string; mimeType: string; sizeBytes: number }) => input).handler(async ({ context, data }) => {
  const client = db(context.supabase); await getOwnedConversation(client, data.conversationId, context.userId); if (!data.storagePath.startsWith(`${context.userId}/`)) throw new Response("Invalid attachment path", { status: 403 }); if (data.sizeBytes <= 0 || data.sizeBytes > 25 * 1024 * 1024) throw new Response("Attachment exceeds the 25 MB limit", { status: 413 });
  const allowed = new Set(["application/pdf","text/plain","text/markdown","text/csv","application/json","application/xml","text/xml","text/html","image/jpeg","image/png","image/webp","image/gif"]); if (!allowed.has(data.mimeType)) throw new Response("Unsupported attachment type", { status: 415 });
  const { data: attachment, error } = await client.from("aax_chat_attachments").insert({ conversation_id: data.conversationId, owner_id: context.userId, storage_path: data.storagePath, filename: data.filename.slice(0, 255), mime_type: data.mimeType, size_bytes: data.sizeBytes, extraction_status: "pending" }).select("id,filename,mime_type,size_bytes,extraction_status").single(); if (error || !attachment) throw new Response(`Could not register attachment: ${error?.message ?? "unknown error"}`, { status: 500 }); void extractAaxAttachment(attachment.id, context.userId).catch(() => undefined); return attachment;
});
export const getAaxAttachmentDownloadUrl = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).validator((input: { attachmentId: string }) => input).handler(async ({ context, data }) => { const { data: row, error } = await db(context.supabase).from("aax_chat_attachments").select("storage_path,filename").eq("id", data.attachmentId).eq("owner_id", context.userId).maybeSingle(); if (error || !row) throw new Response("Attachment not found", { status: 404 }); const { data: signed, error: signedError } = await supabaseAdmin.storage.from("aax-chat-attachments").createSignedUrl(row.storage_path, 300); if (signedError || !signed?.signedUrl) throw new Response("Could not create attachment download URL", { status: 500 }); return { url: signed.signedUrl, filename: row.filename }; });

async function extractAaxAttachment(attachmentId: string, ownerId: string) {
  const { data: row } = await supabaseAdmin.from("aax_chat_attachments").select("id,storage_path,mime_type,size_bytes").eq("id", attachmentId).eq("owner_id", ownerId).maybeSingle(); if (!row) return; await supabaseAdmin.from("aax_chat_attachments").update({ extraction_status: "processing" }).eq("id", attachmentId);
  try {
    const { data: blob, error } = await supabaseAdmin.storage.from("aax-chat-attachments").download(row.storage_path); if (error || !blob) throw new Error(error?.message ?? "Attachment download failed"); let text = "";
    if (row.mime_type === "application/pdf") { const { getDocument } = await import("pdfjs-serverless"); const buffer = new Uint8Array(await blob.arrayBuffer()); const document = await getDocument({ data: buffer, useSystemFonts: true }).promise; const pages: string[] = []; for (let pageNo = 1; pageNo <= document.numPages; pageNo += 1) { const page = await document.getPage(pageNo); const content = await page.getTextContent(); pages.push(content.items.map((item: any) => typeof item.str === "string" ? item.str : "").join(" ")); } text = pages.join("\n\n"); }
    else if (row.mime_type.startsWith("text/") || ["application/json","application/xml"].includes(row.mime_type)) text = await blob.text();
    else { await supabaseAdmin.from("aax_chat_attachments").update({ extraction_status: "unsupported", metadata: { note: "Binary image retained securely; image understanding will be handled by a multimodal AAX provider when enabled." } }).eq("id", attachmentId); return; }
    const clipped = text.slice(0, 500_000); await supabaseAdmin.from("aax_chat_attachments").update({ extraction_status: "completed", extracted_text: clipped, metadata: { extractedCharacters: clipped.length } }).eq("id", attachmentId);
  } catch (error) { await supabaseAdmin.from("aax_chat_attachments").update({ extraction_status: "failed", metadata: { error: error instanceof Error ? error.message : String(error) } }).eq("id", attachmentId); }
}

export async function executeAaxConversationTurn(admin: SupabaseClient, input: SendInput & { userId: string; signal?: AbortSignal }) {
  const client = admin; let conversationId = input.conversationId?.trim() || null; let modelKey = input.modelKey?.trim() || null; let message = input.message?.trim() ?? "";
  if (input.regenerateMessageId) { const { data: previous, error: previousError } = await supabaseAdmin.from("aax_conversation_messages").select("id,conversation_id,owner_id,role,content").eq("id", input.regenerateMessageId).eq("owner_id", input.userId).maybeSingle(); if (previousError || !previous || previous.role !== "user") throw new Response("Regeneration source message not found", { status: 404 }); if (input.conversationId && previous.conversation_id !== input.conversationId) throw new Response("Regeneration source does not belong to this conversation", { status: 409 }); message = previous.content; }
  if (!message) throw new Response("Message is required", { status: 400 }); if (message.length > MAX_MESSAGE_CHARS) throw new Response("Message is too large", { status: 413 });
  if (conversationId) { const conversation = await getOwnedConversation(client, conversationId, input.userId); const joined = conversation.aax_models as any; modelKey = Array.isArray(joined) ? joined[0]?.model_key : joined?.model_key; if (input.projectId !== undefined || input.webResearch !== undefined || input.memoryEnabled !== undefined) { if (input.projectId !== undefined) await assertProject(client, input.projectId, input.userId); const patch: Record<string, unknown> = { updated_at: new Date().toISOString() }; if (input.projectId !== undefined) patch.project_id = input.projectId; if (input.webResearch !== undefined) patch.web_research_enabled = input.webResearch; if (input.memoryEnabled !== undefined) patch.memory_enabled = input.memoryEnabled; await client.from("aax_conversations").update(patch).eq("id", conversationId).eq("owner_id", input.userId); } }
  if (!modelKey) throw new Response("AAX model is required", { status: 400 });
  if (!conversationId) { await assertProject(client, input.projectId, input.userId); const { data: model, error } = await supabaseAdmin.from("aax_models").select("id,model_key").eq("model_key", modelKey).maybeSingle(); if (error || !model) throw new Response("AAX model not found", { status: 404 }); const { data: created, error: createError } = await supabaseAdmin.from("aax_conversations").insert({ owner_id: input.userId, model_id: model.id, title: message.slice(0, 80) || "New conversation", project_id: input.projectId ?? null, memory_enabled: input.memoryEnabled ?? true, web_research_enabled: input.webResearch ?? false }).select("id").single(); if (createError || !created) throw new Response(`Could not create conversation: ${createError?.message ?? "unknown error"}`, { status: 500 }); conversationId = created.id; }
  const conversation = await getOwnedConversation(client, conversationId, input.userId); const { data: history, error: historyError } = await supabaseAdmin.from("aax_conversation_messages").select("role,content").eq("conversation_id", conversationId).eq("owner_id", input.userId).order("created_at", { ascending: false }).limit(MAX_HISTORY_MESSAGES); if (historyError) throw new Response(`Could not load conversation history: ${historyError.message}`, { status: 500 });
  let userMessage: { id: string } | null = null;
  if (input.regenerateMessageId) { userMessage = { id: input.regenerateMessageId }; const { data: latestAssistant } = await supabaseAdmin.from("aax_conversation_messages").select("id").eq("conversation_id", conversationId).eq("owner_id", input.userId).eq("role", "assistant").order("created_at", { ascending: false }).limit(1).maybeSingle(); if (latestAssistant?.id) await supabaseAdmin.from("aax_conversation_messages").delete().eq("id", latestAssistant.id).eq("owner_id", input.userId); }
  else { const inserted = await supabaseAdmin.from("aax_conversation_messages").insert({ conversation_id: conversationId, owner_id: input.userId, model_id: conversation.model_id, role: "user", content: message, metadata: { webResearch: input.webResearch ?? conversation.web_research_enabled, memoryEnabled: input.memoryEnabled ?? conversation.memory_enabled, projectId: input.projectId ?? conversation.project_id } }).select("id").single(); if (inserted.error || !inserted.data) throw new Response(`Could not persist message: ${inserted.error?.message ?? "unknown error"}`, { status: 500 }); userMessage = inserted.data; }
  if (!input.regenerateMessageId && input.attachmentIds?.length) { const ids = input.attachmentIds.slice(0, 10); const { data: ownedAttachments } = await supabaseAdmin.from("aax_chat_attachments").select("id,extracted_text,filename,mime_type").in("id", ids).eq("owner_id", input.userId).eq("conversation_id", conversationId); if ((ownedAttachments?.length ?? 0) !== ids.length) throw new Response("One or more attachments are not owned by this user or conversation", { status: 403 }); await supabaseAdmin.from("aax_chat_attachments").update({ message_id: userMessage!.id }).in("id", ids).eq("owner_id", input.userId); }
  const attachedRows = !input.regenerateMessageId && input.attachmentIds?.length ? (await supabaseAdmin.from("aax_chat_attachments").select("filename,mime_type,extracted_text,extraction_status").in("id", input.attachmentIds.slice(0, 10)).eq("owner_id", input.userId).eq("conversation_id", conversationId)).data ?? [] : [];
  const attachmentContext = attachedRows.filter((item) => item.extraction_status === "completed" && item.extracted_text).map((item) => `Attachment: ${item.filename}\n${item.extracted_text}`).join("\n\n");
  const messages = [...(history ?? []).reverse(), ...(attachmentContext ? [{ role: "system" as const, content: `Use the following user-provided attachments as source material.\n${attachmentContext}` }] : []), { role: "user" as const, content: message }].map((item) => ({ role: item.role as "user" | "assistant" | "system", content: item.content }));
  const webResearch = input.webResearch ?? conversation.web_research_enabled; const run = await supabaseAdmin.from("aax_chat_generation_runs").insert({ conversation_id: conversationId, owner_id: input.userId, model_id: conversation.model_id, user_message_id: userMessage!.id, status: "running", web_research: webResearch }).select("id").single(); if (run.error || !run.data) throw new Response(`Could not create generation run: ${run.error?.message ?? "unknown error"}`, { status: 500 });
  try { const response = webResearch ? await executeAaxWebResearch(supabaseAdmin, { modelKey: modelKey!, messages, maxOutputTokens: input.maxOutputTokens, signal: input.signal, telemetry: { userId: input.userId, runId: run.data.id } }) : await executeAaxChat(supabaseAdmin, { modelKey: modelKey!, messages, temperature: input.temperature, maxOutputTokens: input.maxOutputTokens, signal: input.signal, telemetry: { userId: input.userId, kind: "aax.chat", runId: run.data.id } }); const assistant = await supabaseAdmin.from("aax_conversation_messages").insert({ conversation_id: conversationId, owner_id: input.userId, model_id: conversation.model_id, role: "assistant", content: response.content, metadata: { webResearch, providerModel: "providerModel" in response ? response.providerModel : undefined, tokensIn: response.tokensIn, tokensOut: response.tokensOut, latencyMs: response.latencyMs } }).select("id").single(); if (assistant.error || !assistant.data) throw new Error(`Could not persist assistant response: ${assistant.error?.message ?? "unknown error"}`); if (webResearch && "sources" in response) { const sourceRows = response.sources.map((source) => ({ conversation_id: conversationId, message_id: assistant.data.id, owner_id: input.userId, url: source.url, title: source.title ?? null, domain: source.domain ?? null, snippet: source.snippet ?? null, citation_index: source.citationIndex })); if (sourceRows.length) await supabaseAdmin.from("aax_chat_sources").insert(sourceRows); } await supabaseAdmin.from("aax_chat_generation_runs").update({ status: "completed", assistant_message_id: assistant.data.id, completed_at: new Date().toISOString(), metadata: { sourceCount: "sources" in response ? response.sources.length : 0 } }).eq("id", run.data.id); await supabaseAdmin.from("aax_conversations").update({ last_message_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", conversationId).eq("owner_id", input.userId); if (conversation.memory_enabled) await supabaseAdmin.from("agent_learning_records").insert({ agent_key: "knowledge-acquisition", source_agent_key: "aax", owner_id: input.userId, source_type: "conversation", source_id: userMessage!.id, candidate: { modelKey, conversationId, message, assistantResponseId: assistant.data.id }, status: "candidate" }); return { conversationId, runId: run.data.id, userMessageId: userMessage!.id, assistantMessageId: assistant.data.id, content: response.content, sources: "sources" in response ? response.sources : [], webResearch }; } catch (error) { await supabaseAdmin.from("aax_chat_generation_runs").update({ status: "failed", completed_at: new Date().toISOString(), error: error instanceof Error ? error.message : String(error) }).eq("id", run.data.id); throw error; }
}

export async function prepareAaxStreamingTurn(admin: SupabaseClient, input: SendInput & { userId: string }) {
  const client = admin; let conversationId = input.conversationId?.trim() || null; let modelKey = input.modelKey?.trim() || null; let message = input.message?.trim() ?? "";
  if (input.regenerateMessageId) { const { data: previous, error: previousError } = await supabaseAdmin.from("aax_conversation_messages").select("id,conversation_id,owner_id,role,content").eq("id", input.regenerateMessageId).eq("owner_id", input.userId).maybeSingle(); if (previousError || !previous || previous.role !== "user") throw new Response("Regeneration source message not found", { status: 404 }); if (input.conversationId && previous.conversation_id !== input.conversationId) throw new Response("Regeneration source does not belong to this conversation", { status: 409 }); message = previous.content; }
  if (!message) throw new Response("Message is required", { status: 400 }); if (message.length > MAX_MESSAGE_CHARS) throw new Response("Message is too large", { status: 413 });
  if (conversationId) { const conversation = await getOwnedConversation(client, conversationId, input.userId); const joined = conversation.aax_models as any; modelKey = Array.isArray(joined) ? joined[0]?.model_key : joined?.model_key; } else if (!modelKey) throw new Response("AAX model is required", { status: 400 });
  if (!conversationId) { await assertProject(client, input.projectId, input.userId); const { data: model, error } = await supabaseAdmin.from("aax_models").select("id,model_key").eq("model_key", modelKey).maybeSingle(); if (error || !model) throw new Response("AAX model not found", { status: 404 }); const { data: created, error: createError } = await supabaseAdmin.from("aax_conversations").insert({ owner_id: input.userId, model_id: model.id, title: message.slice(0, 80), project_id: input.projectId ?? null, memory_enabled: input.memoryEnabled ?? true, web_research_enabled: input.webResearch ?? false }).select("id").single(); if (createError || !created) throw new Response(`Could not create conversation: ${createError?.message ?? "unknown error"}`, { status: 500 }); conversationId = created.id; }
  const conversation = await getOwnedConversation(client, conversationId, input.userId); const { data: history, error: historyError } = await supabaseAdmin.from("aax_conversation_messages").select("role,content").eq("conversation_id", conversationId).eq("owner_id", input.userId).order("created_at", { ascending: false }).limit(MAX_HISTORY_MESSAGES); if (historyError) throw new Response(`Could not load conversation history: ${historyError.message}`, { status: 500 }); const webResearch = input.webResearch ?? conversation.web_research_enabled;
  let userMessage: { id: string } | null = null;
  if (input.regenerateMessageId) { userMessage = { id: input.regenerateMessageId }; const { data: latestAssistant } = await supabaseAdmin.from("aax_conversation_messages").select("id").eq("conversation_id", conversationId).eq("owner_id", input.userId).eq("role", "assistant").order("created_at", { ascending: false }).limit(1).maybeSingle(); if (latestAssistant?.id) await supabaseAdmin.from("aax_conversation_messages").delete().eq("id", latestAssistant.id).eq("owner_id", input.userId); }
  else { const inserted = await supabaseAdmin.from("aax_conversation_messages").insert({ conversation_id: conversationId, owner_id: input.userId, model_id: conversation.model_id, role: "user", content: message, metadata: { webResearch, memoryEnabled: input.memoryEnabled ?? conversation.memory_enabled, projectId: input.projectId ?? conversation.project_id } }).select("id").single(); if (inserted.error || !inserted.data) throw new Response(`Could not persist message: ${inserted.error?.message ?? "unknown error"}`, { status: 500 }); userMessage = inserted.data; }
  if (!input.regenerateMessageId && input.attachmentIds?.length) { const ids = input.attachmentIds.slice(0, 10); const { data: ownedAttachments } = await supabaseAdmin.from("aax_chat_attachments").select("id").in("id", ids).eq("owner_id", input.userId).eq("conversation_id", conversationId); if ((ownedAttachments?.length ?? 0) !== ids.length) throw new Response("One or more attachments are not owned by this user or conversation", { status: 403 }); await supabaseAdmin.from("aax_chat_attachments").update({ message_id: userMessage!.id }).in("id", ids).eq("owner_id", input.userId); }
  const attachedRows = !input.regenerateMessageId && input.attachmentIds?.length ? (await supabaseAdmin.from("aax_chat_attachments").select("filename,mime_type,extracted_text,extraction_status").in("id", input.attachmentIds.slice(0, 10)).eq("owner_id", input.userId).eq("conversation_id", conversationId)).data ?? [] : [];
  const attachmentContext = attachedRows.filter((item) => item.extraction_status === "completed" && item.extracted_text).map((item) => `Attachment: ${item.filename}\n${item.extracted_text}`).join("\n\n");
  const { data: run, error: runError } = await supabaseAdmin.from("aax_chat_generation_runs").insert({ conversation_id: conversationId, owner_id: input.userId, model_id: conversation.model_id, user_message_id: userMessage!.id, status: "running", web_research: webResearch }).select("id").single(); if (runError || !run) throw new Response(`Could not create generation run: ${runError?.message ?? "unknown error"}`, { status: 500 });
  return { conversationId, modelKey: modelKey!, ownerId: input.userId, conversation, messages: [...(history ?? []).reverse(), ...(attachmentContext ? [{ role: "system" as const, content: `Use the following user-provided attachments as source material.\n${attachmentContext}` }] : []), { role: "user" as const, content: message }].map((item) => ({ role: item.role as "user" | "assistant" | "system", content: item.content })), userMessageId: userMessage!.id, runId: run.id, webResearch };
}
export async function completeAaxStreamingTurn(admin: SupabaseClient, prepared: Awaited<ReturnType<typeof prepareAaxStreamingTurn>>, response: { content: string; modelId: string; provider: string; providerModel: string; tokensIn: number; tokensOut: number; latencyMs: number }) {
  const assistant = await supabaseAdmin.from("aax_conversation_messages").insert({ conversation_id: prepared.conversationId, owner_id: prepared.ownerId, model_id: response.modelId, role: "assistant", content: response.content, metadata: { webResearch: false, provider: response.provider, providerModel: response.providerModel, tokensIn: response.tokensIn, tokensOut: response.tokensOut, latencyMs: response.latencyMs } }).select("id").single(); if (assistant.error || !assistant.data) throw new Error(`Could not persist assistant response: ${assistant.error?.message ?? "unknown error"}`);
  await supabaseAdmin.from("aax_chat_generation_runs").update({ status: "completed", assistant_message_id: assistant.data.id, completed_at: new Date().toISOString() }).eq("id", prepared.runId).eq("owner_id", prepared.ownerId); await supabaseAdmin.from("aax_conversations").update({ last_message_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", prepared.conversationId).eq("owner_id", prepared.ownerId); if (prepared.conversation.memory_enabled) await supabaseAdmin.from("agent_learning_records").insert({ agent_key: "knowledge-acquisition", source_agent_key: "aax", owner_id: prepared.ownerId, source_type: "conversation", source_id: prepared.userMessageId, candidate: { modelKey: prepared.modelKey, conversationId: prepared.conversationId, messageId: prepared.userMessageId, assistantResponseId: assistant.data.id }, status: "candidate" }); return assistant.data.id;
}
