/** AETHER AI TEAM — agent contracts. */
export type AgentKey="orchestrator"|"research"|"verification"|"knowledge-acquisition"|"curator"|"report"|"notification"|"security"|"optimization"|"module"|"recycling";
export type AgentStatus="enabled"|"disabled"|"maintenance";
export interface AgentPermission{permission:string;label:string;allowed:boolean;requiresApproval?:boolean;}
export interface AgentDefinition{key:AgentKey;name:string;description:string;purpose:string;mission:string;responsibilities:string[];prohibited:string[];status:AgentStatus;tools:string[];permissions:AgentPermission[];lastActivity:string;openTasks:number;}
const def=(key:AgentKey,name:string,status:AgentStatus,description:string,tools:string[],lastActivity:string):AgentDefinition=>({key,name,description,purpose:description,mission:description,responsibilities:tools,prohibited:["Bypass authorization","Modify roles","Self-escalate permissions"],status,tools,permissions:[],lastActivity,openTasks:0});
export const AGENTS:AgentDefinition[]=[
 def("orchestrator","Orchestrator Agent","disabled","Coordinates multi-agent workflows and routes work to the correct specialists.",["task.route","workflow.compose","run.track"],"No activity yet"),
 def("research","Research Agent","disabled","Searches the web and gathers candidate information into a research sandbox.",["web.search","url.fetch","sandbox.write"],"No activity yet"),
 def("verification","Verification Agent","enabled","Checks claims, sources, dates, contradictions and evidence quality.",["research.read","sources.compare","evidence.evaluate"],"Phase G activated"),
 def("knowledge-acquisition","Knowledge Acquisition Agent","enabled","Ingests source text and prepares governed candidate knowledge.",["source.parse","claims.extract","entities.extract","relations.extract","knowledge.compare","candidate.write"],"Phase H activated"),
 def("curator","Knowledge Curator","enabled","Governs candidate knowledge and publishes only explicitly approved, verified material.",["verified.read","knowledge.review","knowledge.write","knowledge.version","knowledge.rollback"],"Phase H activated"),
 def("report","Report / PDF Agent","enabled","Builds deterministic Aether-branded review reports from verified research.",["verified.read","pdf.generate","archive.write","report.download.authorize"],"Phase J activated"),
 {...def("notification","Notification & Delivery Agent","enabled","Delivers durable in-app and provider-backed notifications with explicit ownership, preferences and action links.",["notify.create","notify.queue","notify.deliver","notify.preferences","notify.audit"],"Phase K activated"),responsibilities:["Create notifications","Queue delivery channels","Apply recipient preferences","Deliver in-app events","Provider-backed email delivery","Retry failed deliveries","Preserve delivery audit state"],prohibited:["Arbitrary user data access","Cross-user private resource delivery","Change task ownership","Modify knowledge","Bypass recipient authorization","Expose private report URLs","Self-configure external providers"],permissions:[{permission:"notifications.create",label:"Can create notifications",allowed:true},{permission:"notifications.queue",label:"Can queue delivery",allowed:true},{permission:"notifications.deliver",label:"Can deliver notifications",allowed:true},{permission:"notifications.preferences",label:"Can apply recipient preferences",allowed:true},{permission:"notifications.cross_user",label:"Can deliver another user's private resources",allowed:false},{permission:"roles.modify",label:"Can modify roles",allowed:false}]},
 {...def("security","Security & Compliance Agent","enabled","Monitors permission boundaries, policy violations, suspicious internal behaviour and durable security incidents.",["security.inspect","violations.flag","security.incident.create","security.policy.evaluate"],"Phase O activated"),permissions:[{permission:"security.inspect",label:"Can inspect security boundaries",allowed:true},{permission:"violations.flag",label:"Can flag policy violations",allowed:true},{permission:"security.incident.create",label:"Can create security incidents",allowed:true},{permission:"security.policy.evaluate",label:"Can evaluate security policy",allowed:true},{permission:"roles.modify",label:"Can modify roles",allowed:false},{permission:"permissions.self_modify",label:"Can self-modify permissions",allowed:false}]},
 {...def("optimization","Optimization Agent","enabled","Analyses real performance telemetry and produces governed optimization recommendations with durable approval and rollback.",["telemetry.read","recommendations.write","optimization.scan","optimization.recommend","optimization.apply","optimization.rollback"],"Phase P activated"),responsibilities:["Read real task-run telemetry","Calculate deterministic performance metrics","Detect failure, retry, timeout and latency hotspots","Persist evidence-backed recommendations","Request and record administrator decisions","Apply only approved safe agent-policy changes","Rollback applied optimization versions","Emit durable optimization audit events"],prohibited:["Fabricate telemetry","Auto-apply production changes","Modify roles","Modify security policies","Bypass Phase O authorization","Self-escalate permissions","Change task ownership","Delete audit evidence"],permissions:[{permission:"optimization.scan",label:"Can scan performance telemetry",allowed:true},{permission:"optimization.recommend",label:"Can create optimization recommendations",allowed:true},{permission:"optimization.apply",label:"Can apply approved optimization changes",allowed:true,requiresApproval:true},{permission:"optimization.rollback",label:"Can rollback optimization changes",allowed:true,requiresApproval:true},{permission:"roles.modify",label:"Can modify roles",allowed:false},{permission:"permissions.self_modify",label:"Can modify its own permissions",allowed:false}]},
 {...def("module","Module Agent","enabled","Creates, validates, tests and governs extensible application, game, integration, tool and workflow modules through a durable registry and trusted runtime.",["modules.read","modules.create","modules.validate","modules.test","modules.activate","modules.manage","modules.run","modules.artifacts","agent.execute"],"Phase Q activated"),responsibilities:["Create versioned module manifests","Validate module contracts and dependencies","Test trusted runtime handlers","Activate and govern module versions","Queue durable module runs through the universal task runtime","Record module events and artifacts","Maintain module configuration history"],prohibited:["Bypass authorization","Modify roles","Self-escalate permissions","Execute untrusted arbitrary code","Read secrets without an explicit approved capability","Mutate host filesystem","Delete module audit evidence"],permissions:[{permission:"agent.execute",label:"Can execute through the universal task runtime",allowed:true},{permission:"modules.create",label:"Can create modules",allowed:true},{permission:"modules.validate",label:"Can validate modules",allowed:true},{permission:"modules.test",label:"Can test modules",allowed:true},{permission:"modules.activate",label:"Can activate modules",allowed:true},{permission:"modules.manage",label:"Can manage module lifecycle",allowed:true},{permission:"modules.run",label:"Can queue module runs",allowed:true},{permission:"modules.artifacts",label:"Can manage module artifacts",allowed:true},{permission:"roles.modify",label:"Can modify roles",allowed:false},{permission:"permissions.self_modify",label:"Can modify its own permissions",allowed:false}]},
 {...def("recycling","Recycling Agent","enabled","Maintains the independent Aether Safety Bin ecosystem, preserves deletion evidence, supports recovery and produces governed evidence reports.",["safety_bin.read","safety_bin.search","safety_bin.integrity","safety_bin.restore","safety_bin.report","safety_bin.freeze"],"Phase Y activated"),responsibilities:["Preserve deleted platform records","Attribute deletion to authenticated actors","Search Safety Bin records by user, project, time and type","Verify evidence integrity","Support authorized restoration","Freeze evidence for investigations","Generate Aether-branded Safety Bin reports"],prohibited:["Bypass Phase X authorization","Self-escalate permissions","Permanently purge evidence","Modify roles","Delete or alter chain-of-custody history","Read another user's private data without authorized admin/investigation access"],permissions:[{permission:"safety_bin.read",label:"Can read authorized Safety Bin records",allowed:true},{permission:"safety_bin.search",label:"Can search authorized Safety Bin records",allowed:true},{permission:"safety_bin.integrity",label:"Can verify evidence integrity",allowed:true},{permission:"safety_bin.restore",label:"Can request authorized restoration",allowed:true},{permission:"safety_bin.report",label:"Can generate Safety Bin reports",allowed:true},{permission:"safety_bin.freeze",label:"Can freeze evidence",allowed:true},{permission:"safety_bin.purge",label:"Can permanently purge evidence",allowed:false},{permission:"roles.modify",label:"Can modify roles",allowed:false},{permission:"permissions.self_modify",label:"Can modify its own permissions",allowed:false}]}
];
