/** AETHER AI TEAM — agent contracts. */
export type AgentKey="orchestrator"|"research"|"verification"|"knowledge-acquisition"|"curator"|"report"|"notification"|"security"|"optimization"|"module";
export type AgentStatus="enabled"|"disabled"|"maintenance";
export interface AgentPermission{permission:string;label:string;allowed:boolean;requiresApproval?:boolean;}
export interface AgentDefinition{key:AgentKey;name:string;description:string;purpose:string;mission:string;responsibilities:string[];prohibited:string[];status:AgentStatus;tools:string[];permissions:AgentPermission[];lastActivity:string;openTasks:number;}
const def=(key:AgentKey,name:string,status:AgentStatus,description:string,tools:string[],lastActivity:string):AgentDefinition=>({key,name,description,purpose:description,mission:description,responsibilities:tools,prohibited:["Bypass authorization","Modify roles","Self-escalate permissions"],status,tools,permissions:[],lastActivity,openTasks:0});
export const AGENTS:AgentDefinition[]=[
 def("orchestrator","Orchestrator Agent","disabled","Coordinates multi-agent workflows and routes work to the correct specialists.",["task.route","workflow.compose","run.track"],"No activity yet"),
 def("research","Research Agent","disabled","Searches the web and gathers candidate information into a research sandbox.",["web.search","url.fetch","sandbox.write"],"No activity yet"),
 def("verification","Verification Agent","enabled","Checks claims, sources, dates, contradictions and evidence quality.",["research.read","sources.compare","evidence.evaluate"],"Phase G activated"),
 def("knowledge-acquisition","Knowledge Acquisition Agent","enabled","Ingests source text and prepares governed candidate knowledge.",["source.parse","claims.extract","entities.extract","relations.extract","knowledge.compare","candidate.write"],"Phase H activated"),
 def("curator","Knowledge Curator","enabled","Governs candidate knowledge and publishes only explicitly approved, verified material.",["verified.read","knowledge.review","knowledge.write","knowledge.version","knowledge.rollback"],"Phase H activated"),
 def("report","Report / PDF Agent","enabled","Builds deterministic Aether-branded review reports from verified research.",["verified.read","pdf.generate","archive.write","report.download.authorize"],"Phase J activated"),
 {...def("notification","Notification & Delivery Agent","enabled","Delivers durable in-app and provider-backed notifications with explicit ownership, preferences and action links.",["notify.create","notify.queue","notify.deliver","notify.preferences","notify.audit"],"Phase K activated"),responsibilities:["Create notifications","Queue delivery channels","Apply recipient preferences","Deliver in-app events","Provider-backed email delivery","Retry failed deliveries","Preserve delivery audit state"],prohibited:["Arbitrary user data access","Cross-user private resource delivery","Change task ownership","Modify knowledge","Bypass recipient authorization","Expose private report URLs","Self-configure external providers"],permissions:[{permission:"notifications.create",label:"Can create notifications",allowed:true},{permission:"notifications.queue",label:"Can queue delivery",allowed:true},{permission:"notifications.deliver",label:"Can deliver notifications",allowed:true},{permission:"notifications.preferences",label:"Can apply recipient preferences",allowed:true},{permission:"notifications.cross_user",label:"Can deliver another user's private resources",allowed:false},{permission:"roles.modify",label:"Can modify roles",allowed:false}]},
 def("security","Security & Compliance Agent","disabled","Monitors permission boundaries, policy violations and suspicious internal behaviour.",["security.inspect","violations.flag"],"No activity yet"),
 def("optimization","Optimization Agent","disabled","Analyses real performance telemetry and recommends configuration improvements.",["telemetry.read","recommendations.write"],"No activity yet"),
 def("module","Module Agent","disabled","Helps create and manage structured application and game modules in sandbox form.",["modules.read","modules.draft"],"No activity yet")
];
