/** AETHER AGENT SDK — strongly typed, provider-independent internal worker contract. */
import { AGENTS, type AgentKey, type AgentDefinition as BaseAgentDefinition } from "@/lib/aether/agents";
export type AgentRunStatus="queued"|"running"|"completed"|"failed"|"cancelled"|"waiting_approval"|"paused"|"retrying"|"scheduled";
export type VerificationState="verified"|"needs_review"|"conflicting"|"unsupported"|"outdated"|"rejected"|"pending";
export interface AgentPolicy{timeoutMs:number;maxRetries:number;backoffMs?:number;escalateOnFailure:boolean;escalateTo?:"admin"|"security"|"orchestrator";}
export interface AgentScheduleConfig{enabled:boolean;type?:"one_time"|"delayed"|"recurring"|"interval"|"date_range"|"event";cron?:string;intervalMinutes?:number;startAt?:string;endAt?:string;}
export interface AgentTelemetryConfig{collectMetrics:boolean;collectTimeline:boolean;retainDays:number;}
export interface FullAgentDefinition extends BaseAgentDefinition{agent_id:string;version:string;prohibited:string[];allowed_inputs:string[];expected_outputs:string[];quality_requirements:string[];timeout_policy:AgentPolicy;retry_policy:AgentPolicy;escalation_policy:AgentPolicy;schedule_configuration:AgentScheduleConfig;telemetry_configuration:AgentTelemetryConfig;}
export interface AgentTaskContext{taskId:string;runId:string;agentKey:AgentKey;agentId?:string;requesterId:string;projectId?:string|null;taskType:string;priority?:number|"low"|"normal"|"high"|"critical";deadline?:string|null;permissionsContext?:string[];inputs:Record<string,unknown>;previousResults?:AgentResult[];sourceContext?:Record<string,unknown>;}
export interface AgentArtifactRef{type:string;id?:string;path?:string;title?:string;metadata?:Record<string,unknown>;}
export interface AgentResult{taskId:string;runId:string;agentKey:AgentKey;agentId?:string;status:AgentRunStatus;result?:Record<string,unknown>;artifacts?:AgentArtifactRef[];findings?:Array<{claim:string;evidence?:string;confidence?:number;sources?:string[];verification_state?:VerificationState;[key:string]:unknown}>;warnings?:string[];errors?:string[];confidence?:number|null;nextAction?:string|null;requiresReview?:boolean;timestamp:string;metrics?:Record<string,number|string>;}
export interface AgentMessage{fromAgent:AgentKey;toAgent:AgentKey;runId:string;taskId:string;type:string;payload:AgentResult|Record<string,unknown>;timestamp:string;}
export function getAgentContract(key:AgentKey){return AGENTS.find((a)=>a.key===key)??null;}
export function agentAllows(key:AgentKey,permission:string){const agent=getAgentContract(key);if(!agent)return{allowed:false,requiresApproval:false,reason:"Unknown agent"};if(agent.status==="disabled"||agent.status==="maintenance")return{allowed:false,requiresApproval:false,reason:`Agent is ${agent.status}`};const perm=agent.permissions.find((p)=>p.permission===permission);if(!perm)return{allowed:false,requiresApproval:false,reason:"Permission not granted"};return{allowed:perm.allowed,requiresApproval:Boolean(perm.requiresApproval)};}
export function assertAgentPermission(key:AgentKey,permission:string){const check=agentAllows(key,permission);if(!check.allowed)throw new Error(`Permission denied for ${key}: ${permission}${check.reason?` (${check.reason})`:""}`);}
export function createFullAgentDefinition(base:BaseAgentDefinition,overrides?:Partial<FullAgentDefinition>):FullAgentDefinition{const policy:AgentPolicy={timeoutMs:300_000,maxRetries:2,backoffMs:5_000,escalateOnFailure:true,escalateTo:"admin"};return{...base,agent_id:overrides?.agent_id??`agent_${base.key}`,version:overrides?.version??"1.0.0",prohibited:overrides?.prohibited??["Bypass authorization","Modify roles","Self-escalate permissions"],allowed_inputs:overrides?.allowed_inputs??["task_context","previous_results"],expected_outputs:overrides?.expected_outputs??["result","status","requires_review"],quality_requirements:overrides?.quality_requirements??["structured output","source traceability where applicable","no silent production writes"],timeout_policy:overrides?.timeout_policy??policy,retry_policy:overrides?.retry_policy??{...policy,maxRetries:3},escalation_policy:overrides?.escalation_policy??policy,schedule_configuration:overrides?.schedule_configuration??{enabled:false},telemetry_configuration:overrides?.telemetry_configuration??{collectMetrics:true,collectTimeline:true,retainDays:90},...overrides};}
