/** Phase M — authenticated Agent SDK control-plane functions. All mutations are server/admin guarded. */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { AGENTS, type AgentKey } from "./agents";
import { mergeStaticContract, makeVersionHash, validateAgentDefinition } from "./agent-registry";
import { authorizeAgentAction, appendAgentMessage, requestAgentHandoff, openAgentSandbox } from "./agent-runtime";

const db = supabaseAdmin as any;
async function assertAdmin(userId:string){const {data,error}=await db.rpc("has_role",{_user_id:userId,_role:"admin"});if(error||!data)throw new Response("Administrator authorization required",{status:403});}
function keyOf(value:unknown):AgentKey{const key=String(value||"") as AgentKey;if(!AGENTS.some((a)=>a.key===key))throw new Response("Unknown agent",{status:400});return key;}

export const getAgentControlPlane = createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await assertAdmin(context.userId);const [{data:agents,error:aErr},{data:versions,error:vErr},{data:permissions,error:pErr},{data:history,error:hErr}]=await Promise.all([db.from("agents").select("id,agent_key,name,description,purpose,status,tools,config,last_activity_at,created_at,updated_at").order("name"),db.from("agent_versions").select("id,agent_id,version,lifecycle_state,definition,config_hash,parent_version_id,created_by,validated_by,tested_by,activated_by,created_at,validated_at,tested_at,activated_at,retired_at,rollback_reason").order("created_at",{ascending:false}),db.from("agent_permissions").select("id,agent_id,permission,allowed,requires_approval,created_at"),db.from("agent_config_history").select("id,agent_id,version_id,action,reason,actor_id,created_at").order("created_at",{ascending:false}).limit(500)]);if(aErr||vErr||pErr||hErr)throw new Response("Could not load agent control plane",{status:500});return{agents:agents??[],versions:versions??[],permissions:permissions??[],history:history??[]};});

export const createAgentVersion = createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({agentKey:keyOf(x?.agentKey),version:String(x?.version||""),definition:x?.definition&&typeof x.definition==="object"?x.definition:{},reason:x?.reason?String(x.reason):null})).handler(async({context,data})=>{await assertAdmin(context.userId);if(!/^\d+\.\d+\.\d+$/.test(data.version.trim()))throw new Response("Version must use semver",{status:400});const definition=mergeStaticContract(data.agentKey,data.definition as any);definition.version=data.version.trim();definition.agent_id=`agent_${data.agentKey}`;const validation=validateAgentDefinition(definition);if(!validation.ok)throw new Response(validation.message,{status:400});const {data:agent,error:agentError}=await db.from("agents").select("id").eq("agent_key",data.agentKey).single();if(agentError||!agent)throw new Response("Agent not found",{status:404});const {data:parent}=await db.from("agent_versions").select("id").eq("agent_id",agent.id).order("created_at",{ascending:false}).limit(1).maybeSingle();const {data:row,error}=await db.from("agent_versions").insert({agent_id:agent.id,version:data.version,lifecycle_state:"draft",definition,config_hash:makeVersionHash(definition),parent_version_id:parent?.id??null,created_by:context.userId}).select("*").single();if(error||!row)throw new Response(error?.message??"Could not create version",{status:500});await db.from("agent_config_history").insert({agent_id:agent.id,version_id:row.id,action:"created",after_config:definition,actor_id:context.userId,reason:data.reason});return row;});

async function transition(contextUserId:string,versionId:string,target:string,reason?:string|null){await assertAdmin(contextUserId);const {data,error}=await db.rpc("agent_lifecycle_transition",{p_version_id:versionId,p_target_state:target,p_actor_id:contextUserId,p_reason:reason??null});if(error||!data)throw new Response(error?.message??"Lifecycle transition failed",{status:409});return data;}
export const validateAgentVersion=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{versionId:string})=>x).handler(async({context,data})=>{await assertAdmin(context.userId);const {data:version,error}=await db.from("agent_versions").select("id,definition,lifecycle_state").eq("id",data.versionId).single();if(error||!version)throw new Response("Agent version not found",{status:404});if(version.lifecycle_state!=="draft")throw new Response("Only draft versions can be validated",{status:409});const result=validateAgentDefinition(version.definition);if(!result.ok)throw new Response(result.message,{status:400});return transition(context.userId,data.versionId,"validated","Contract validation passed");});
export const testAgentVersion=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{versionId:string})=>x).handler(async({context,data})=>{await assertAdmin(context.userId);const {data:version,error}=await db.from("agent_versions").select("id,definition,lifecycle_state").eq("id",data.versionId).single();if(error||!version)throw new Response("Agent version not found",{status:404});if(version.lifecycle_state!=="validated")throw new Response("Only validated versions can be tested",{status:409});const result=validateAgentDefinition(version.definition);if(!result.ok)throw new Response(result.message,{status:400});const permissions=(version.definition as any).permissions??[];const names=permissions.map((p:any)=>String(p.permission||""));if(new Set(names).size!==names.length)throw new Response("Agent contract contains duplicate permissions",{status:400});return transition(context.userId,data.versionId,"tested","Contract structural test passed");});
export const activateAgentVersion=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{versionId:string})=>x).handler(async({context,data})=>transition(context.userId,data.versionId,"active","Version activated after validation and test gates"));
export const setAgentOperationalState=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{versionId:string;state:"maintenance"|"disabled"})=>x).handler(async({context,data})=>transition(context.userId,data.versionId,data.state,`Agent moved to ${data.state}`));
export const rollbackAgentVersion=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{agentKey:AgentKey;versionId:string;reason?:string})=>({agentKey:keyOf(x.agentKey),versionId:x.versionId,reason:x.reason?String(x.reason):null})).handler(async({context,data})=>{await assertAdmin(context.userId);const {data:agent,error}=await db.from("agents").select("id").eq("agent_key",data.agentKey).single();if(error||!agent)throw new Response("Agent not found",{status:404});const {data:row,error:rpcError}=await db.rpc("agent_rollback_to_version",{p_agent_id:agent.id,p_target_version_id:data.versionId,p_actor_id:context.userId,p_reason:data.reason});if(rpcError||!row)throw new Response(rpcError?.message??"Rollback failed",{status:409});return row;});

export const authorizeAgentToolAction=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({agentKey:keyOf(x?.agentKey),permission:String(x?.permission||""),action:String(x?.action||""),taskId:x?.taskId?String(x.taskId):null,runId:x?.runId?String(x.runId):null,metadata:x?.metadata&&typeof x.metadata==="object"?x.metadata:{}})).handler(async({context,data})=>authorizeAgentAction({...data,actorId:context.userId}));
export const sendAgentHandoff=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({taskId:String(x?.taskId||""),runId:x?.runId?String(x.runId):null,fromAgent:keyOf(x?.fromAgent),toAgent:keyOf(x?.toAgent),payload:x?.payload&&typeof x.payload==="object"?x.payload:{}})).handler(async({context,data})=>requestAgentHandoff({...data,actorId:context.userId}));
export const openAgentSandboxSession=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({taskId:String(x?.taskId||""),runId:x?.runId?String(x.runId):null,agentKey:keyOf(x?.agentKey),ttlSeconds:x?.ttlSeconds===undefined?900:Number(x.ttlSeconds)})).handler(async({context,data})=>openAgentSandbox({...data,actorId:context.userId}));
export const appendAgentMessageFn=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({taskId:String(x?.taskId||""),runId:x?.runId?String(x.runId):null,fromAgent:keyOf(x?.fromAgent),toAgent:keyOf(x?.toAgent),type:String(x?.type||""),payload:x?.payload&&typeof x.payload==="object"?x.payload:{}})).handler(async({context,data})=>appendAgentMessage({...data,actorId:context.userId}));
