/** Phase R — authenticated Battleversia control plane. */
import {createServerFn} from '@tanstack/react-start';
import {requireSupabaseAuth} from '@/integrations/supabase/auth-middleware';
import {supabaseAdmin} from '@/integrations/supabase/client.server';
import {authorizeSecurityAction} from './security-runtime';
import {authorizeAgentAction} from './agent-runtime';
import {createTask,createRun} from './task-service';
import {DEFAULT_AUCTION_FUND,AUCTION_MIN_PLAYERS,AUCTION_MAX_PLAYERS,validAuctionMode,type BVAuctionMode,tournamentValid} from './battleversia-runtime';
const db=supabaseAdmin as any;
async function admin(uid:string){const {data}=await db.rpc('has_role',{_user_id:uid,_role:'admin'});return Boolean(data);}
async function gate(uid:string,action:string,permission:string,resourceId?:string){const s=await authorizeSecurityAction({actorId:uid,agentKey:'module',action,resourceType:'battleversia',resourceId,context:{phase:'R'}});if(!s.allowed)throw new Response(s.reason,{status:s.requiresApproval?409:403});const a=await authorizeAgentAction({agentKey:'module',permission,action,actorId:uid,metadata:{resourceId,domain:'battleversia'}});if(!a.allowed)throw new Response(a.reason,{status:a.requiresApproval?409:403});}
async function wallet(uid:string){const {data,error}=await db.from('bv_wallets').upsert({owner_id:uid},{onConflict:'owner_id'}).select('*').single();if(error)throw new Response(error.message,{status:500});return data;}
export const getBattleversiaHome=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).handler(async({context})=>{const w=await wallet(context.userId);const [{data:characters},{data:auctions},{data:tournaments},{data:servers}]=await Promise.all([db.from('bv_characters').select('id,slug,name,universe,power_score,price,market_available').eq('active',true).order('power_score',{ascending:false}).limit(12),db.from('bv_auctions').select('*').in('status',['lobby','active','paused']).order('created_at',{ascending:false}).limit(10),db.from('bv_tournaments').select('*').in('status',['registration','active','paused']).order('starts_at',{ascending:true}).limit(10),db.from('bv_servers').select('*').order('name')]);return{wallet:w,characters:characters??[],auctions:auctions??[],tournaments:tournaments??[],servers:servers??[]};});
export const listBattleversiaCharacters=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({universe:x?.universe?String(x.universe):undefined})).handler(async({data})=>{let q=db.from('bv_characters').select('*').eq('active',true).order('power_score',{ascending:false});if(data.universe)q=q.eq('universe',data.universe);const {data:rows,error}=await q.limit(500);if(error)throw new Response(error.message,{status:500});return rows??[];});
export const createBattleversiaAuction=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({mode:String(x?.mode??'overall'),entryFee:Math.max(0,Number(x?.entryFee??0)),fund:Math.max(0,Number(x?.fund??DEFAULT_AUCTION_FUND))})).handler(async({context,data})=>{if(!validAuctionMode(data.mode))throw new Response('Invalid auction mode',{status:400});await gate(context.userId,'battleversia.auction.create','modules.run');const {data:a,error}=await db.from('bv_auctions').insert({owner_id:context.userId,mode:data.mode,entry_fee:data.entryFee,fund:data.fund,max_players:AUCTION_MAX_PLAYERS}).select('*').single();if(error)throw new Response(error.message,{status:500});const {error:j}=await db.from('bv_auction_players').insert({auction_id:a.id,player_id:context.userId});if(j)throw new Response(j.message,{status:500});await db.from('bv_events').insert({actor_id:context.userId,event_type:'auction.created',entity_type:'auction',entity_id:a.id,payload:{mode:data.mode,fund:data.fund}});return a;});
export const joinBattleversiaAuction=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({auctionId:String(x?.auctionId??'')})).handler(async({context,data})=>{await gate(context.userId,'battleversia.auction.join','modules.run',data.auctionId);const {data:row,error}=await db.rpc('bv_join_auction',{p_auction_id:data.auctionId,p_player_id:context.userId});if(error)throw new Response(error.message,{status:409});return row;});
export const startBattleversiaAuction=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({auctionId:String(x?.auctionId??'')})).handler(async({context,data})=>{await gate(context.userId,'battleversia.auction.start','modules.run',data.auctionId);const {data:row,error}=await db.rpc('bv_start_auction',{p_auction_id:data.auctionId,p_owner_id:context.userId});if(error)throw new Response(error.message,{status:409});return row;});
export const placeBattleversiaBid=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({auctionId:String(x?.auctionId??''),amount:Math.floor(Number(x?.amount??0))})).handler(async({context,data})=>{if(data.amount<=0)throw new Response('Bid must be positive',{status:400});await gate(context.userId,'battleversia.auction.bid','modules.run',data.auctionId);const {data:row,error}=await db.rpc('bv_place_bid',{p_auction_id:data.auctionId,p_bidder_id:context.userId,p_amount:data.amount});if(error)throw new Response(error.message,{status:409});return row;});
export const listBattleversiaAuctions=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).handler(async()=>{const {data,error}=await db.from('bv_auctions').select('*,bv_auction_players(*)').in('status',['lobby','active','paused']).order('created_at',{ascending:false}).limit(100);if(error)throw new Response(error.message,{status:500});return data??[];});
export const createBattleversiaTournament=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({name:String(x?.name??'').trim(),prizePool:Math.max(0,Number(x?.prizePool??0)),entryFee:Math.max(0,Number(x?.entryFee??0)),minPlayers:Math.floor(Number(x?.minPlayers??2)),maxPlayers:Math.floor(Number(x?.maxPlayers??32)),format:String(x?.format??'single_elimination')})).handler(async({context,data})=>{if(!data.name)throw new Response('Tournament name is required',{status:400});if(!tournamentValid(data.minPlayers,data.maxPlayers))throw new Response('Invalid player limits',{status:400});await gate(context.userId,'battleversia.tournament.create','modules.create');const {data:t,error}=await db.from('bv_tournaments').insert({owner_id:context.userId,name:data.name,prize_pool:data.prizePool,entry_fee:data.entryFee,min_players:data.minPlayers,max_players:data.maxPlayers,format:data.format}).select('*').single();if(error)throw new Response(error.message,{status:500});await db.from('bv_events').insert({actor_id:context.userId,event_type:'tournament.created',entity_type:'tournament',entity_id:t.id,payload:{name:data.name}});return t;});
export const joinBattleversiaTournament=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({tournamentId:String(x?.tournamentId??'')})).handler(async({context,data})=>{const {data:t,error}=await db.from('bv_tournaments').select('*').eq('id',data.tournamentId).single();if(error||!t)throw new Response('Tournament not found',{status:404});if(t.status!=='registration')throw new Response('Tournament registration is closed',{status:409});const {count}=await db.from('bv_tournament_players').select('id',{count:'exact',head:true}).eq('tournament_id',t.id);if((count??0)>=t.max_players)throw new Response('Tournament is full',{status:409});const {data:row,error:j}=await db.from('bv_tournament_players').insert({tournament_id:t.id,player_id:context.userId}).select('*').single();if(j)throw new Response(j.message,{status:409});return row;});
export const listBattleversiaTournaments=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).handler(async()=>{const {data,error}=await db.from('bv_tournaments').select('*').neq('status','draft').order('starts_at',{ascending:true}).limit(100);if(error)throw new Response(error.message,{status:500});return data??[];});
export const getBattleversiaEconomy=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).handler(async({context})=>{const w=await wallet(context.userId);const {data:owned}=await db.from('bv_character_ownership').select('*,bv_characters(*)').eq('owner_id',context.userId).order('acquired_at',{ascending:false});return{wallet:w,owned:owned??[]};});
export const queueBattleversiaMatch=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({mode:String(x?.mode??'standard'),opponentId:String(x?.opponentId??'')})).handler(async({context,data})=>{if(!data.opponentId)throw new Response('Opponent is required',{status:400});await gate(context.userId,'battleversia.match.create','modules.run');const task=await createTask(supabaseAdmin,{owner_id:context.userId,title:'Battleversia match',kind:'battleversia:match',detail:{mode:data.mode,opponentId:data.opponentId},status:'queued',timeout_ms:180000,max_retries:1});const run=await createRun(supabaseAdmin,{task_id:task.id,owner_id:context.userId,agent_key:'module',inputs:{mode:data.mode,opponentId:data.opponentId},attempt:1,timeout_ms:180000,max_retries:1});const {data:m,error}=await db.from('bv_matches').insert({owner_id:context.userId,mode:data.mode,status:'pending'}).select('*').single();if(error)throw new Response(error.message,{status:500});await db.from('bv_match_players').insert([{match_id:m.id,player_id:context.userId},{match_id:m.id,player_id:data.opponentId}]);await db.from('bv_events').insert({actor_id:context.userId,event_type:'match.queued',entity_type:'match',entity_id:m.id,payload:{taskId:task.id,runId:run.id,opponentId:data.opponentId}});return{match:m,taskId:task.id,runId:run.id};});
export const getBattleversiaControl=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).handler(async({context})=>{if(!(await admin(context.userId)))throw new Response('Administrator authorization required',{status:403});const [{data:characters},{data:servers},{data:auctions},{data:tournaments}]=await Promise.all([db.from('bv_characters').select('*').order('universe').order('power_score',{ascending:false}),db.from('bv_servers').select('*'),db.from('bv_auctions').select('*').order('created_at',{ascending:false}).limit(100),db.from('bv_tournaments').select('*').order('created_at',{ascending:false}).limit(100)]);return{characters:characters??[],servers:servers??[],auctions:auctions??[],tournaments:tournaments??[]};});
export const seedBattleversiaWallet=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).handler(async({context})=>wallet(context.userId));
