import { createHash, randomBytes } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { createTask, createRun, getTaskWithRuns, getTaskEvents } from "./task-service";
import { resolveTimeoutMs, type TimeoutPreset } from "./task-runtime";
import { listAgents, type AgentKey } from "./agent-registry";
import { listAetherMemories, createAetherMemory } from "./aether-memory.functions";

export const API_VERSION = "v1";
export const API_SCOPES = ["projects:read","projects:write","conversations:read","conversations:write","tasks:read","tasks:write","runs:read","agents:read","orchestration:read","orchestration:write","memory:read","memory:write","research:read","research:write","knowledge:read","knowledge:write","reports:read","notifications:read","schedules:read","schedules:write","modules:read","modules:write","battleversia:read","battleversia:write","webhooks:read","webhooks:write","logs:read"] as const;
export type ApiScope = typeof API_SCOPES[number];
export type ApiIdentity = { apiKeyId: string; ownerId: string; projectId: string | null; scopes: string[]; rateLimitPerMinute: number };

const json = (body: unknown, status = 200, headers: Record<string,string> = {}) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", ...headers } });
export const apiError = (status: number, code: string, message: string, details?: unknown) => json({ error: { code, message, ...(details === undefined ? {} : { details }) } }, status);
export const hashSecret = (value: string) => createHash("sha256").update(value).digest("hex");
const makeSecret = (prefix: string) => `${prefix}_${randomBytes(32).toString("base64url")}`;
export const normalizeScopeList = (scopes: unknown): string[] => Array.isArray(scopes) ? Array.from(new Set(scopes.map(String).filter((s) => (API_SCOPES as readonly string[]).includes(s)))) : [];

export async function createDeveloperApiKey(input: { ownerId: string; projectId?: string | null; name: string; scopes?: string[]; rateLimitPerMinute?: number; expiresAt?: string | null }) {
  const name = input.name.trim().slice(0,120); if (!name) throw new Response("Key name is required", { status: 400 });
  const scopes = normalizeScopeList(input.scopes); const finalScopes = scopes.length ? scopes : ["tasks:read","tasks:write","runs:read"];
  if (input.projectId) { const { data } = await supabaseAdmin.from("projects").select("id").eq("id", input.projectId).eq("owner_id", input.ownerId).eq("archived", false).maybeSingle(); if (!data) throw new Response("Project not found or not owned by the current user", { status: 404 }); }
  const secret = makeSecret("aether_sk"); const keyHash = hashSecret(secret); const keyPrefix = secret.slice(0, 16);
  const { data, error } = await supabaseAdmin.from("aether_api_keys").insert({ owner_id: input.ownerId, project_id: input.projectId ?? null, name, key_prefix: keyPrefix, key_hash: keyHash, scopes: finalScopes, rate_limit_per_minute: Math.max(1, Math.min(10000, Math.floor(input.rateLimitPerMinute ?? 60))), expires_at: input.expiresAt ?? null }).select("id,name,key_prefix,project_id,scopes,rate_limit_per_minute,expires_at,created_at").single();
  if (error || !data) throw new Response(`Could not create API key: ${error?.message ?? "unknown error"}`, { status: 500 });
  await supabaseAdmin.from("aether_api_key_events").insert({ api_key_id: data.id, owner_id: input.ownerId, event_type: "created", metadata: { scopes: finalScopes, project_id: input.projectId ?? null } });
  return { ...data, key: secret };
}

export async function authenticateDeveloperApiKey(request: Request): Promise<ApiIdentity | null> {
  const header = request.headers.get("authorization") ?? ""; const match = header.match(/^Bearer\s+(.+)$/i); if (!match) return null;
  const presented = match[1].trim(); if (!presented.startsWith("aether_sk_") || presented.length < 30) return null;
  const { data, error } = await supabaseAdmin.rpc("aether_api_authenticate", { p_key_hash: hashSecret(presented) });
  if (error || !data?.length) return null;
  const identity = data[0] as ApiIdentity; const { data: allowed } = await supabaseAdmin.rpc("aether_api_rate_allowed", { p_api_key_id: identity.apiKeyId, p_limit: identity.rateLimitPerMinute });
  if (allowed === false) throw new Response("Rate limit exceeded", { status: 429, headers: { "Retry-After": "60" } });
  return identity;
}

export function requireScope(identity: ApiIdentity, scope: ApiScope) { if (!identity.scopes.includes(scope) && !identity.scopes.includes("*")) throw new Response(JSON.stringify({ error: { code: "insufficient_scope", message: `Scope ${scope} is required` } }), { status: 403, headers: { "Content-Type": "application/json" } }); }

export async function logApiRequest(identity: ApiIdentity | null, request: Request, path: string, statusCode: number, startedAt: number, metadata: Record<string,unknown> = {}) {
  await supabaseAdmin.from("aether_api_logs").insert({ api_key_id: identity?.apiKeyId ?? null, owner_id: identity?.ownerId ?? null, method: request.method, path, status_code: statusCode, latency_ms: Math.max(0, Date.now() - startedAt), request_id: request.headers.get("x-request-id") || randomBytes(12).toString("hex"), metadata });
}

export async function listDeveloperApiKeys(ownerId: string) { const { data, error } = await supabaseAdmin.from("aether_api_keys").select("id,name,key_prefix,project_id,scopes,rate_limit_per_minute,expires_at,revoked_at,last_used_at,created_at,updated_at").eq("owner_id", ownerId).order("created_at", { ascending: false }); if (error) throw new Response(error.message,{status:500}); return data ?? []; }
export async function revokeDeveloperApiKey(ownerId: string, keyId: string) { const { data, error } = await supabaseAdmin.from("aether_api_keys").update({ revoked_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", keyId).eq("owner_id", ownerId).is("revoked_at", null).select("id").maybeSingle(); if (error || !data) throw new Response("API key not found or already revoked",{status:404}); await supabaseAdmin.from("aether_api_key_events").insert({api_key_id:keyId,owner_id:ownerId,event_type:"revoked"}); return {ok:true}; }
export async function rotateDeveloperApiKey(ownerId: string, keyId: string) { const { data: old } = await supabaseAdmin.from("aether_api_keys").select("name,project_id,scopes,rate_limit_per_minute,expires_at").eq("id",keyId).eq("owner_id",ownerId).maybeSingle(); if(!old) throw new Response("API key not found",{status:404}); await revokeDeveloperApiKey(ownerId,keyId); return createDeveloperApiKey({ownerId,projectId:old.project_id,name:old.name,scopes:old.scopes,rateLimitPerMinute:old.rate_limit_per_minute,expiresAt:old.expires_at}); }

async function ownedProject(identity: ApiIdentity, projectId: string) { const { data } = await supabaseAdmin.from("projects").select("id,name,slug,description,status,archived,created_at,updated_at").eq("id",projectId).eq("owner_id",identity.ownerId).maybeSingle(); if(!data) throw new Response("Project not found",{status:404}); return data; }
export async function handleDeveloperApi(request: Request, identity: ApiIdentity, segments: string[], body: any) {
  const [resource, id, action] = segments;
  if (!resource) return json({ data:{ version:API_VERSION, name:"Aether Developer API", status:"online", scopes:API_SCOPES } });
  if (resource === "auth") { requireScope(identity,"projects:read"); return json({ data:{ authenticated:true, apiKeyId:identity.apiKeyId, projectId:identity.projectId, scopes:identity.scopes, rateLimitPerMinute:identity.rateLimitPerMinute } }); }
  if (resource === "projects") { requireScope(identity, request.method === "GET" ? "projects:read" : "projects:write"); if(request.method === "GET") { if(id) return json({data:await ownedProject(identity,id)}); const {data,error}=await supabaseAdmin.from("projects").select("id,name,slug,description,status,archived,created_at,updated_at").eq("owner_id",identity.ownerId).eq("archived",false).order("updated_at",{ascending:false}).limit(100); if(error) throw new Response(error.message,{status:500}); return json({data:data??[]}); } if(request.method==="POST"){ const name=String(body?.name??"").trim().slice(0,120); if(!name) return apiError(400,"invalid_request","name is required"); const slug=(String(body?.slug??name).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||`project-${Date.now()}`).slice(0,80); const {data,error}=await supabaseAdmin.from("projects").insert({owner_id:identity.ownerId,name,slug,description:String(body?.description??"").slice(0,1000),status:"active",archived:false}).select("id,name,slug,description,status,archived,created_at,updated_at").single(); if(error||!data) return apiError(409,"project_create_failed",error?.message??"Could not create project"); return json({data},201); } if(request.method==="DELETE"&&id){await ownedProject(identity,id); const {error}=await supabaseAdmin.from("projects").update({archived:true,updated_at:new Date().toISOString()}).eq("id",id).eq("owner_id",identity.ownerId); if(error) throw new Response(error.message,{status:500}); return json({data:{ok:true}});} }
  if (resource === "tasks") { requireScope(identity, request.method === "GET" ? "tasks:read" : "tasks:write"); if(request.method==="GET"){ if(id) return json({data:await getTaskWithRuns(supabaseAdmin,id,identity.ownerId,false)}); const {data,error}=await supabaseAdmin.from("tasks").select("id,title,kind,status,progress,priority,timeout_ms,deadline_at,retry_count,max_retries,created_at,updated_at,completed_at").eq("user_id",identity.ownerId).order("created_at",{ascending:false}).limit(100); if(error) throw new Response(error.message,{status:500}); return json({data:data??[]}); } if(request.method==="POST"){ const title=String(body?.title??"").trim(); const kind=String(body?.kind??"general").trim().slice(0,64)||"general"; if(!title) return apiError(400,"invalid_request","title is required"); const timeoutMs=resolveTimeoutMs(body?.timeout as number|TimeoutPreset|undefined); const task=await createTask(supabaseAdmin,{owner_id:identity.ownerId,project_id:body?.projectId??identity.projectId,title:title.slice(0,200),kind,detail:body?.detail??{},status:"queued",timeout_ms:timeoutMs,max_retries:Math.max(0,Math.min(20,Math.floor(body?.maxRetries??3))),priority:Math.max(-100,Math.min(100,Math.floor(body?.priority??0))),idempotencyKey:body?.idempotencyKey?.trim().slice(0,255)||undefined}); const run=await createRun(supabaseAdmin,{task_id:task.id,owner_id:identity.ownerId,inputs:{title,kind,...(body?.detail??{})},attempt:1,timeout_ms:timeoutMs,max_retries:task.max_retries}); return json({data:{taskId:task.id,runId:run.id}},201); } }
  if (resource === "runs") { requireScope(identity,"runs:read"); if(!id) return apiError(400,"invalid_request","run id is required"); const {data,error}=await supabaseAdmin.from("task_runs").select("id,task_id,status,attempt,progress,started_at,completed_at,error,created_at,updated_at").eq("id",id).eq("owner_id",identity.ownerId).maybeSingle(); if(error||!data) return apiError(404,"not_found","Run not found"); const events=await getTaskEvents(supabaseAdmin,data.task_id,identity.ownerId,false); return json({data:{...data,events}}); }
  if (resource === "agents") { requireScope(identity,"agents:read"); const agents=await listAgents(); return json({data:agents}); }
  if (resource === "orchestration") { requireScope(identity,request.method==="GET"?"orchestration:read":"orchestration:write"); const {data,error}=await supabaseAdmin.from("orchestration_plans").select("id,title,status,created_at,updated_at").eq("owner_id",identity.ownerId).order("created_at",{ascending:false}).limit(100); if(error) return apiError(500,"orchestration_error",error.message); return json({data:data??[]}); }
  if (resource === "memory") { requireScope(identity,request.method==="GET"?"memory:read":"memory:write"); if(request.method==="GET"){ const {data,error}=await supabaseAdmin.from("aether_memories").select("id,project_id,scope,memory_type,content,status,persistence_mode,reason,confidence,importance,version,created_at,updated_at,last_used_at").eq("owner_id",identity.ownerId).eq("status","active").order("updated_at",{ascending:false}).limit(200); if(error) return apiError(500,"memory_error",error.message); return json({data:data??[]}); } if(request.method==="POST"){ const content=String(body?.content??"").trim(); if(!content)return apiError(400,"invalid_request","content is required"); const scope=body?.scope==="project"?"project":"global"; const projectId=scope==="project"?(body?.projectId??identity.projectId):null; if(projectId) await ownedProject(identity,projectId); const {data,error}=await supabaseAdmin.from("aether_memories").insert({owner_id:identity.ownerId,project_id:projectId,scope,memory_type:String(body?.memoryType??"fact").slice(0,64),content:content.slice(0,12000),persistence_mode:"explicit",reason:String(body?.reason??"").slice(0,1000),confidence:body?.confidence??null,importance:Math.max(0,Math.min(1,Number(body?.importance??0.5)))}).select("id,project_id,scope,memory_type,content,status,persistence_mode,reason,confidence,importance,version,created_at,updated_at").single(); if(error||!data)return apiError(500,"memory_create_failed",error?.message??"Could not create memory"); return json({data},201);} }
  if (resource === "schedules") { requireScope(identity,request.method==="GET"?"schedules:read":"schedules:write"); const q=supabaseAdmin.from("schedules").select("id,name,kind,status,cron_expression,interval_seconds,next_run_at,last_run_at,created_at,updated_at").eq("owner_id",identity.ownerId).order("created_at",{ascending:false}).limit(100); const {data,error}=await q; if(error)return apiError(500,"schedule_error",error.message); if(request.method==="GET")return json({data:data??[]}); if(request.method==="POST"){const row={owner_id:identity.ownerId,project_id:body?.projectId??identity.projectId,name:String(body?.name??"API schedule").slice(0,120),kind:body?.kind??"once",cron_expression:body?.cronExpression??null,interval_seconds:body?.intervalSeconds??null,next_run_at:body?.nextRunAt??new Date().toISOString(),payload:body?.payload??{},status:"active"}; const {data:created,error:e}=await supabaseAdmin.from("schedules").insert(row).select("id,name,kind,status,next_run_at,created_at").single(); if(e||!created)return apiError(500,"schedule_create_failed",e?.message??"Could not create schedule"); return json({data:created},201);} }
  if (resource === "modules") { requireScope(identity,"modules:read"); const {data,error}=await supabaseAdmin.from("modules").select("id,module_key,name,version,status,description,created_at,updated_at").order("name",{ascending:true}).limit(200); if(error)return apiError(500,"module_error",error.message); return json({data:data??[]}); }
  if (resource === "battleversia") { requireScope(identity,"battleversia:read"); const tables:Record<string,string>={characters:"battleversia_characters",market:"battleversia_market_items",rankings:"battleversia_rankings",auctions:"battleversia_auctions",tournaments:"battleversia_tournaments"}; const table=tables[id??""]; if(!table)return json({data:{world:"Battleversia",realms:["characters","market","economy","auctions","tournaments","rankings"]}}); const {data,error}=await supabaseAdmin.from(table).select("*").limit(100); if(error)return apiError(500,"battleversia_error",error.message); return json({data:data??[]}); }
  if (resource === "reports") { requireScope(identity,"reports:read"); const {data,error}=await supabaseAdmin.from("reports").select("id,title,status,created_at,updated_at").eq("owner_id",identity.ownerId).order("created_at",{ascending:false}).limit(100); if(error)return apiError(500,"report_error",error.message); return json({data:data??[]}); }
  if (resource === "notifications") { requireScope(identity,"notifications:read"); const {data,error}=await supabaseAdmin.from("notifications").select("id,type,title,message,read,created_at").eq("user_id",identity.ownerId).order("created_at",{ascending:false}).limit(100); if(error)return apiError(500,"notification_error",error.message); return json({data:data??[]}); }
  if (resource === "knowledge") { requireScope(identity,"knowledge:read"); const {data,error}=await supabaseAdmin.from("knowledge_items").select("*").eq("owner_id",identity.ownerId).order("updated_at",{ascending:false}).limit(100); if(error)return apiError(500,"knowledge_error",error.message); return json({data:data??[]}); }
  if (resource === "research") { requireScope(identity,request.method==="GET"?"research:read":"research:write"); const {data,error}=await supabaseAdmin.from("research_jobs").select("*").eq("owner_id",identity.ownerId).order("created_at",{ascending:false}).limit(100); if(error)return apiError(500,"research_error",error.message); return json({data:data??[]}); }
  if (resource === "conversations") { requireScope(identity,request.method==="GET"?"conversations:read":"conversations:write"); if(id){ const {data,error}=await supabaseAdmin.from("aax_conversations").select("id,model_id,title,archived,project_id,memory_enabled,web_research_enabled,last_message_at,created_at,updated_at,aax_models(model_key,display_name,generation,revision)").eq("id",id).eq("owner_id",identity.ownerId).maybeSingle(); if(error||!data)return apiError(404,"not_found","Conversation not found"); return json({data}); } const {data,error}=await supabaseAdmin.from("aax_conversations").select("id,model_id,title,archived,project_id,memory_enabled,web_research_enabled,last_message_at,created_at,updated_at,aax_models(model_key,display_name,generation,revision)").eq("owner_id",identity.ownerId).eq("archived",false).order("updated_at",{ascending:false}).limit(100); if(error)return apiError(500,"conversation_error",error.message); return json({data:data??[]}); }
  if (resource === "webhooks") { requireScope(identity,request.method==="GET"?"webhooks:read":"webhooks:write"); if(request.method==="GET"){const {data,error}=await supabaseAdmin.from("aether_api_webhooks").select("id,project_id,url,events,active,created_at,updated_at").eq("owner_id",identity.ownerId).order("created_at",{ascending:false}); if(error)return apiError(500,"webhook_error",error.message); return json({data:data??[]});} if(request.method==="POST"){const url=String(body?.url??"").trim(); try{new URL(url);}catch{return apiError(400,"invalid_request","A valid webhook URL is required");} const secret=makeSecret("whsec"); const {data,error}=await supabaseAdmin.from("aether_api_webhooks").insert({owner_id:identity.ownerId,project_id:body?.projectId??identity.projectId,url,events:Array.isArray(body?.events)?body.events.map(String).slice(0,50):["task.completed","task.failed"],secret_hash:hashSecret(secret),active:true}).select("id,project_id,url,events,active,created_at").single(); if(error||!data)return apiError(500,"webhook_create_failed",error?.message??"Could not create webhook"); return json({data:{...data,secret}},201);} }
  if (resource === "logs") { requireScope(identity,"logs:read"); const {data,error}=await supabaseAdmin.from("aether_api_logs").select("id,method,path,status_code,latency_ms,request_id,metadata,created_at").eq("owner_id",identity.ownerId).order("created_at",{ascending:false}).limit(200); if(error)return apiError(500,"log_error",error.message); return json({data:data??[]}); }
  return apiError(404,"not_found",`Unknown API resource: ${resource}`);
}
