import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { createDeveloperApiKey, listDeveloperApiKeys, revokeDeveloperApiKey, rotateDeveloperApiKey } from "./developer-api";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

export const listMyDeveloperApiKeys = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(({ context }) => listDeveloperApiKeys(context.userId));
export const createMyDeveloperApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { name: string; projectId?: string | null; scopes?: string[]; rateLimitPerMinute?: number; expiresAt?: string | null }) => data).handler(({ context, data }) => createDeveloperApiKey({ ownerId: context.userId, ...data }));
export const revokeMyDeveloperApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { keyId: string }) => data).handler(({ context, data }) => revokeDeveloperApiKey(context.userId, data.keyId));
export const rotateMyDeveloperApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { keyId: string }) => data).handler(({ context, data }) => rotateDeveloperApiKey(context.userId, data.keyId));
export const listMyApiWebhooks = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { const { data, error } = await supabaseAdmin.from("aether_api_webhooks").select("id,project_id,url,events,active,created_at,updated_at").eq("owner_id", context.userId).order("created_at", { ascending: false }); if (error) throw new Response(error.message,{status:500}); return data ?? []; });
export const createMyApiWebhook = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { url: string; projectId?: string | null; events?: string[] }) => data).handler(async ({ context, data }) => { try { new URL(data.url); } catch { throw new Response("A valid webhook URL is required",{status:400}); } const secret = `whsec_${crypto.randomUUID().replaceAll("-","")}${crypto.randomUUID().replaceAll("-","")}`; const { createHash } = await import("node:crypto"); const secretHash = createHash("sha256").update(secret).digest("hex"); const { data: row, error } = await supabaseAdmin.from("aether_api_webhooks").insert({ owner_id:context.userId, project_id:data.projectId??null, url:data.url.trim(), events:(data.events??["task.completed","task.failed"]).map(String).slice(0,50), secret_hash:secretHash, active:true }).select("id,project_id,url,events,active,created_at").single(); if(error||!row) throw new Response(error?.message??"Could not create webhook",{status:500}); return {...row,secret}; });
export const deleteMyApiWebhook = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { webhookId: string }) => data).handler(async ({ context, data }) => { const { error } = await supabaseAdmin.from("aether_api_webhooks").delete().eq("id",data.webhookId).eq("owner_id",context.userId); if(error) throw new Response(error.message,{status:500}); return {ok:true}; });
export const listMyApiLogs = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { const { data, error } = await supabaseAdmin.from("aether_api_logs").select("id,method,path,status_code,latency_ms,request_id,metadata,created_at").eq("owner_id",context.userId).order("created_at",{ascending:false}).limit(200); if(error) throw new Response(error.message,{status:500}); return data??[]; });
