/** Phase Q — durable worker tick. No browser state or in-memory queue is authoritative. */
import { supabaseAdmin } from '@/integrations/supabase/client.server';
import { authorizeSecurityAction } from './security-runtime';
import { executeRegisteredModule } from './module-runtime';
const db=supabaseAdmin as any;
export async function recoverModuleRuns(limit=100){const {data,error}=await db.rpc('recover_expired_module_runs',{p_limit:Math.min(500,Math.max(1,limit))});if(error)throw new Error(error.message);return Number(data??0);}
export async function claimModuleRuns(workerId:string,limit=10){if(!workerId.trim())throw new Error('workerId is required');const {data,error}=await db.rpc('claim_module_runs',{p_worker_id:workerId,p_limit:Math.min(50,Math.max(1,limit))});if(error)throw new Error(error.message);return data??[];}
async function authorizeCapabilities(row:any,manifest:any){const capabilities=Array.isArray(manifest.capabilities)?manifest.capabilities.map(String):[];for(const capability of capabilities){const {data:grant,error}=await db.from('module_permissions').select('allowed,requires_approval').eq('module_version_id',row.module_version_id).eq('permission',`module.capability.${capability}`).maybeSingle();if(error||!grant?.allowed)throw new Error(`Module capability denied: ${capability}`);if(grant.requires_approval)throw new Error(`Module capability requires approval: ${capability}`);const security=await authorizeSecurityAction({actorId:row.owner_id,agentKey:'module',action:`module.capability.${capability}`,resourceType:'module',resourceId:row.module_id,taskId:row.task_id,runId:row.run_id,context:{moduleVersionId:row.module_version_id}});if(!security.allowed)throw new Error(security.reason);}}
export async function runModuleWorkerTick(workerId:string,limit=10){await recoverModuleRuns();const rows=await claimModuleRuns(workerId,limit);const results:Array<{id:string;status:string;error?:string}>=[];for(const row of rows){const {data:version,error}=await db.from('module_versions').select('version,manifest,config').eq('id',row.module_version_id).single();if(error||!version){await db.rpc('complete_module_run',{p_run_id:row.id,p_status:'failed',p_outputs:{},p_error:'Module version not found'});results.push({id:String(row.id),status:'failed'});continue;}const manifest=version.manifest??{};try{await authorizeCapabilities(row,manifest);const result=await executeRegisteredModule(String(manifest.slug),{moduleId:row.module_id,moduleSlug:String(manifest.slug),version:String(version.version),taskId:row.task_id,runId:row.run_id,ownerId:row.owner_id,inputs:row.inputs??{},config:version.config??{}});await db.rpc('complete_module_run',{p_run_id:row.id,p_status:result.status,p_outputs:result.outputs??{},p_error:result.error??null});await db.from('module_events').insert({module_id:row.module_id,module_version_id:row.module_version_id,run_id:row.id,event_type:`module.worker.${result.status}`,payload:{workerId},actor_id:null});results.push({id:String(row.id),status:result.status});}catch(error){const message=error instanceof Error?error.message:String(error);await db.rpc('complete_module_run',{p_run_id:row.id,p_status:'failed',p_outputs:{},p_error:message});await db.from('module_events').insert({module_id:row.module_id,module_version_id:row.module_version_id,run_id:row.id,event_type:'module.worker.failed',payload:{workerId,error:message},actor_id:null});results.push({id:String(row.id),status:'failed',error:message});}}return{workerId,claimed:rows.length,results};}
