/** Phase Q — authenticated module control plane and durable runtime bridge. */
import { createServerFn } from '@tanstack/react-start';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
import { supabaseAdmin } from '@/integrations/supabase/client.server';
import { authorizeSecurityAction } from './security-runtime';
import { authorizeAgentAction } from './agent-runtime';
import { createTask, createRun } from './task-service';
import { validateModuleManifest, validateModuleVersion, stableModuleHash, versionSatisfies, assertModuleDependenciesAcyclic, executeRegisteredModule, type ModuleManifest, type ModuleExecutionContext } from './module-runtime';
const db=supabaseAdmin as any;
async function isAdmin(userId:string){const {data}=await db.rpc('has_role',{_user_id:userId,_role:'admin'});return Boolean(data);}
async function requireAdmin(userId:string){if(!(await isAdmin(userId)))throw new Response('Administrator authorization required',{status:403});}
async function ownModule(id:string,userId:string,admin=false){const {data,error}=await db.from('modules').select('*').eq('id',id).maybeSingle();if(error||!data)throw new Response('Module not found',{status:404});if(data.owner_id!==userId&&!admin)throw new Response('Forbidden: module does not belong to the current actor',{status:403});return data;}
async function moduleAgent(permission:string,action:string,userId:string,moduleId:string){const decision=await authorizeAgentAction({agentKey:'module',permission,action,actorId:userId,metadata:{moduleId}});if(!decision.allowed)throw new Response(decision.reason,{status:decision.requiresApproval?409:403});}

export const createModule=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({slug:String(x?.slug??'').trim().toLowerCase(),name:String(x?.name??'').trim(),description:String(x?.description??'').trim(),kind:String(x?.kind??'application'),version:String(x?.version??'1.0.0').trim(),manifest:x?.manifest??{},config:x?.config??{}})).handler(async({context,data})=>{if(!data.slug||!data.name)throw new Response('slug and name are required',{status:400});const manifest={...data.manifest,apiVersion:'aether.module/v1',slug:data.slug,name:data.name,description:data.description,kind:data.kind};const errors=[...validateModuleManifest(manifest),...validateModuleVersion(data.version)];if(errors.length)throw new Response(errors.join('; '),{status:400});const security=await authorizeSecurityAction({actorId:context.userId,agentKey:'module',action:'module.create',resourceType:'module',resourceId:data.slug,context:{kind:data.kind}});if(!security.allowed)throw new Response(security.reason,{status:security.requiresApproval?409:403});const existing=await db.from('modules').select('id').eq('slug',data.slug).maybeSingle();if(existing.data)throw new Response('Module slug already exists',{status:409});const {data:module,error}=await db.from('modules').insert({slug:data.slug,name:data.name,description:data.description,module_kind:data.kind,owner_id:context.userId,created_by:context.userId,manifest,config:data.config,status:'draft'}).select('*').single();if(error||!module)throw new Response(error?.message??'Could not create module',{status:500});const {data:version,error:vError}=await db.from('module_versions').insert({module_id:module.id,version:data.version,lifecycle_state:'draft',manifest,config:data.config,config_hash:stableModuleHash({manifest,config:data.config}),created_by:context.userId}).select('*').single();if(vError||!version)throw new Response(vError?.message??'Could not create module version',{status:500});await db.from('module_config_history').insert({module_id:module.id,version_id:version.id,action:'created',after_config:data.config,actor_id:context.userId,reason:'Phase Q module creation'});await db.from('module_events').insert({module_id:module.id,module_version_id:version.id,event_type:'module.created',payload:{version:data.version},actor_id:context.userId});return{module,version};});

export const listModules=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).handler(async({context})=>{const admin=await isAdmin(context.userId);let q=db.from('modules').select('*').order('updated_at',{ascending:false}).limit(200);if(!admin)q=q.eq('owner_id',context.userId);const {data,error}=await q;if(error)throw new Response(error.message,{status:500});return data??[];});
export const getModuleControlPlane=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({moduleId:String(x?.moduleId??'')})).handler(async({context,data})=>{const admin=await isAdmin(context.userId);const module=await ownModule(data.moduleId,context.userId,admin);const [{data:versions,error:vError},{data:deps,error:dError},{data:perms,error:pError},{data:runs,error:rError}]=await Promise.all([db.from('module_versions').select('*').eq('module_id',module.id).order('created_at',{ascending:false}),db.from('module_dependencies').select('*').in('module_version_id',(await db.from('module_versions').select('id').eq('module_id',module.id)).data?.map((v:any)=>v.id)??[]),db.from('module_permissions').select('*').in('module_version_id',(await db.from('module_versions').select('id').eq('module_id',module.id)).data?.map((v:any)=>v.id)??[]),db.from('module_runs').select('*').eq('module_id',module.id).order('created_at',{ascending:false}).limit(100)]);if(vError||dError||pError||rError)throw new Response('Could not load module control plane',{status:500});return{module,versions:versions??[],dependencies:deps??[],permissions:perms??[],runs:runs??[]};});

export const validateModule=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({versionId:String(x?.versionId??'')})).handler(async({context,data})=>{await requireAdmin(context.userId);const {data:v,error}=await db.from('module_versions').select('*,modules(*)').eq('id',data.versionId).single();if(error||!v)throw new Response('Module version not found',{status:404});await moduleAgent('modules.validate','module.validate',context.userId,v.module_id);const errors=[...validateModuleManifest(v.manifest),...validateModuleVersion(v.version)];const deps=Array.isArray(v.manifest?.dependencies)?v.manifest.dependencies:[];const graph:Record<string,string[]>={};graph[v.modules.slug]=deps.map((d:any)=>String(d.slug));try{assertModuleDependenciesAcyclic(v.modules.slug,graph);}catch(e){errors.push(e instanceof Error?e.message:String(e));}if(errors.length)throw new Response(errors.join('; '),{status:400});const {data:row,error:e}=await db.rpc('module_lifecycle_transition',{p_version_id:v.id,p_target_state:'validated',p_actor_id:context.userId,p_reason:'Phase Q validation'});if(e||!row)throw new Response(e?.message??'Validation transition failed',{status:500});return row;});

export const testModule=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({versionId:String(x?.versionId??'')})).handler(async({context,data})=>{await requireAdmin(context.userId);const {data:v,error}=await db.from('module_versions').select('*,modules(*)').eq('id',data.versionId).single();if(error||!v)throw new Response('Module version not found',{status:404});await moduleAgent('modules.test','module.test',context.userId,v.module_id);if(v.lifecycle_state!=='validated')throw new Response('Only validated module versions can be tested',{status:409});const manifest=v.manifest as ModuleManifest;const checks={manifest:validateModuleManifest(manifest),handlerRegistered:false,dependencies:true};const {data:deps}=await db.from('module_dependencies').select('dependency_module_id,version_range,optional').eq('module_version_id',v.id);for(const dep of deps??[]){const {data:target}=await db.from('modules').select('id,active_version_id').eq('id',dep.dependency_module_id).maybeSingle();if(!target||!target.active_version_id){if(!dep.optional)checks.dependencies=false;continue;}const {data:av}=await db.from('module_versions').select('version').eq('id',target.active_version_id).single();if(av&&!versionSatisfies(av.version,dep.version_range)&&!dep.optional)checks.dependencies=false;}const {hasModuleHandler}=await import('./module-runtime');checks.handlerRegistered=hasModuleHandler(manifest.slug);if(checks.manifest.length||!checks.dependencies)return new Response(JSON.stringify(checks),{status:400});const {data:row,error:e}=await db.rpc('module_lifecycle_transition',{p_version_id:v.id,p_target_state:'tested',p_actor_id:context.userId,p_reason:'Phase Q runtime contract test'});if(e||!row)throw new Response(e?.message??'Test transition failed',{status:500});return{row,checks};});

export const activateModule=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({versionId:String(x?.versionId??'')})).handler(async({context,data})=>{await requireAdmin(context.userId);const {data:v,error}=await db.from('module_versions').select('*,modules(*)').eq('id',data.versionId).single();if(error||!v)throw new Response('Module version not found',{status:404});await moduleAgent('modules.activate','module.activate',context.userId,v.module_id);const security=await authorizeSecurityAction({actorId:context.userId,agentKey:'module',action:'module.activate',resourceType:'module',resourceId:v.module_id,context:{versionId:v.id}});if(!security.allowed)throw new Response(security.reason,{status:security.requiresApproval?409:403});if(v.lifecycle_state!=='tested')throw new Response('Only tested module versions can be activated',{status:409});const {data:row,error:e}=await db.rpc('module_lifecycle_transition',{p_version_id:v.id,p_target_state:'active',p_actor_id:context.userId,p_reason:'Phase Q activation'});if(e||!row)throw new Response(e?.message??'Activation failed',{status:500});return row;});

export const setModuleState=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({versionId:String(x?.versionId??''),state:String(x?.state??'disabled')})).handler(async({context,data})=>{await requireAdmin(context.userId);if(!['maintenance','disabled'].includes(data.state))throw new Response('Invalid module state',{status:400});const {data:v,error}=await db.from('module_versions').select('module_id').eq('id',data.versionId).single();if(error||!v)throw new Response('Module version not found',{status:404});await moduleAgent('modules.manage','module.state',context.userId,v.module_id);const {data:row,error:e}=await db.rpc('module_lifecycle_transition',{p_version_id:data.versionId,p_target_state:data.state,p_actor_id:context.userId,p_reason:`Phase Q state change to ${data.state}`});if(e||!row)throw new Response(e?.message??'State change failed',{status:500});return row;});

export const rollbackModule=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({versionId:String(x?.versionId??''),reason:String(x?.reason??'Phase Q rollback')})).handler(async({context,data})=>{await requireAdmin(context.userId);const {data:v,error}=await db.from('module_versions').select('module_id').eq('id',data.versionId).single();if(error||!v)throw new Response('Module version not found',{status:404});await moduleAgent('modules.manage','module.rollback',context.userId,v.module_id);const {data:row,error:e}=await db.rpc('module_lifecycle_transition',{p_version_id:data.versionId,p_target_state:'rolled_back',p_actor_id:context.userId,p_reason:data.reason});if(e||!row)throw new Response(e?.message??'Rollback failed',{status:500});return row;});

export const queueModuleRun=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({moduleId:String(x?.moduleId??''),inputs:x?.inputs??{},idempotencyKey:x?.idempotencyKey?String(x.idempotencyKey):undefined})).handler(async({context,data})=>{const module=await ownModule(data.moduleId,context.userId,false);if(module.status!=='active'||!module.active_version_id)throw new Response('Module is not active',{status:409});const {data:v,error}=await db.from('module_versions').select('*').eq('id',module.active_version_id).single();if(error||!v)throw new Response('Active module version not found',{status:409});const security=await authorizeSecurityAction({actorId:context.userId,agentKey:'module',action:'module.run',resourceType:'module',resourceId:module.id,context:{versionId:v.id}});if(!security.allowed)throw new Response(security.reason,{status:security.requiresApproval?409:403});await moduleAgent('modules.run','module.run',context.userId,module.id);const task=await createTask(supabaseAdmin,{owner_id:context.userId,title:`Module: ${module.name}`,kind:`module:${module.slug}`,detail:{moduleId:module.id,moduleVersionId:v.id,inputs:data.inputs},status:'queued',timeout_ms:300000,max_retries:2,idempotency_key:data.idempotencyKey?`module-task:${data.idempotencyKey}`:undefined});const run=await createRun(supabaseAdmin,{task_id:task.id,owner_id:context.userId,agent_key:'module',inputs:data.inputs,attempt:1,timeout_ms:300000,max_retries:2,idempotency_key:data.idempotencyKey?`module-runtime:${data.idempotencyKey}`:undefined});const existing=await db.from('module_runs').select('*').eq('idempotency_key',data.idempotencyKey??'').maybeSingle();if(existing.data)return existing.data;const {data:mr,error:mrError}=await db.from('module_runs').insert({module_id:module.id,module_version_id:v.id,owner_id:context.userId,task_id:task.id,run_id:run.id,status:'queued',inputs:data.inputs,max_attempts:3,idempotency_key:data.idempotencyKey??null}).select('*').single();if(mrError||!mr)throw new Response(mrError?.message??'Could not queue module run',{status:500});await db.from('module_events').insert({module_id:module.id,module_version_id:v.id,run_id:mr.id,event_type:'module.run.queued',payload:{taskId:task.id,runId:run.id},actor_id:context.userId});return mr;});

export const listModuleRuns=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({moduleId:String(x?.moduleId??'')})).handler(async({context,data})=>{const module=await ownModule(data.moduleId,context.userId,await isAdmin(context.userId));const {data:runs,error}=await db.from('module_runs').select('*').eq('module_id',module.id).order('created_at',{ascending:false}).limit(100);if(error)throw new Response(error.message,{status:500});return runs??[];});

export async function executeClaimedModuleRun(row:any,workerId:string){const manifest=row.module_version?.manifest??row.manifest??{};const context:ModuleExecutionContext={moduleId:row.module_id,moduleSlug:manifest.slug,version:row.version??row.module_version?.version??'unknown',taskId:row.task_id,runId:row.run_id,ownerId:row.owner_id,inputs:row.inputs??{},config:row.config??{}};try{const result=await executeRegisteredModule(manifest.slug,context);await db.rpc('complete_module_run',{p_run_id:row.id,p_status:result.status,p_outputs:result.outputs??{},p_error:result.error??null});await db.from('module_events').insert({module_id:row.module_id,module_version_id:row.module_version_id,run_id:row.id,event_type:`module.run.${result.status}`,payload:{workerId,error:result.error??null},actor_id:null});return result;}catch(error){await db.rpc('complete_module_run',{p_run_id:row.id,p_status:'failed',p_outputs:{},p_error:error instanceof Error?error.message:String(error)});throw error;}}
