/** Phase Q — version/artifact management kept separate from the core runtime boundary. */
import { createServerFn } from '@tanstack/react-start';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
import { supabaseAdmin } from '@/integrations/supabase/client.server';
import { authorizeSecurityAction } from './security-runtime';
import { validateModuleManifest,validateModuleVersion,stableModuleHash,assertModuleDependenciesAcyclic } from './module-runtime';
const db=supabaseAdmin as any;
async function admin(userId:string){const {data}=await db.rpc('has_role',{_user_id:userId,_role:'admin'});if(!data)throw new Response('Administrator authorization required',{status:403});}
async function loadVersion(id:string){const {data,error}=await db.from('module_versions').select('*,modules(*)').eq('id',id).single();if(error||!data)throw new Response('Module version not found',{status:404});return data;}
export const createModuleVersion=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({moduleId:String(x?.moduleId??''),version:String(x?.version??'').trim(),manifest:x?.manifest??{},config:x?.config??{},reason:String(x?.reason??'Phase Q module version update')})).handler(async({context,data})=>{await admin(context.userId);const {data:module,error}=await db.from('modules').select('*').eq('id',data.moduleId).single();if(error||!module)throw new Response('Module not found',{status:404});const manifest={...data.manifest,apiVersion:'aether.module/v1',slug:module.slug,name:module.name,description:module.description,kind:module.module_kind};const errors=[...validateModuleManifest(manifest),...validateModuleVersion(data.version)];const deps=Array.isArray(manifest.dependencies)?manifest.dependencies:[];const graph:Record<string,string[]>={[module.slug]:deps.map((d:any)=>String(d.slug))};try{assertModuleDependenciesAcyclic(module.slug,graph);}catch(e){errors.push(e instanceof Error?e.message:String(e));}if(errors.length)throw new Response(errors.join('; '),{status:400});const security=await authorizeSecurityAction({actorId:context.userId,agentKey:'module',action:'module.version.create',resourceType:'module',resourceId:module.id,context:{version:data.version}});if(!security.allowed)throw new Response(security.reason,{status:security.requiresApproval?409:403});const {data:parent}=await db.from('module_versions').select('id').eq('module_id',module.id).order('created_at',{ascending:false}).limit(1).maybeSingle();const {data:version,error:vError}=await db.from('module_versions').insert({module_id:module.id,version:data.version,lifecycle_state:'draft',manifest,config:data.config,config_hash:stableModuleHash({manifest,config:data.config}),parent_version_id:parent?.id??null,created_by:context.userId}).select('*').single();if(vError||!version)throw new Response(vError?.message??'Could not create module version',{status:500});for(const dep of deps){const {data:target}=await db.from('modules').select('id').eq('slug',String(dep.slug)).maybeSingle();if(target)await db.from('module_dependencies').insert({module_version_id:version.id,dependency_module_id:target.id,version_range:String(dep.versionRange),optional:Boolean(dep.optional)});}await db.from('module_config_history').insert({module_id:module.id,version_id:version.id,action:'version_created',after_config:data.config,actor_id:context.userId,reason:data.reason});return version;});
export const recordModuleArtifact=createServerFn({method:'POST',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({runId:String(x?.runId??''),artifactType:String(x?.artifactType??'output'),path:String(x?.path??'').trim(),checksum:x?.checksum?String(x.checksum):null,metadata:x?.metadata??{}})).handler(async({context,data})=>{const {data:run,error}=await db.from('module_runs').select('module_id,module_version_id,owner_id').eq('id',data.runId).single();if(error||!run)throw new Response('Module run not found',{status:404});const adminUser=Boolean((await db.rpc('has_role',{_user_id:context.userId,_role:'admin'})).data);if(run.owner_id!==context.userId&&!adminUser)throw new Response('Forbidden',{status:403});const security=await authorizeSecurityAction({actorId:context.userId,agentKey:'module',action:'module.artifact.write',resourceType:'module',resourceId:run.module_id,context:{runId:data.runId}});if(!security.allowed)throw new Response(security.reason,{status:security.requiresApproval?409:403});const {data:item,error:itemError}=await db.from('module_artifacts').insert({module_id:run.module_id,module_version_id:run.module_version_id,run_id:data.runId,owner_id:context.userId,artifact_type:data.artifactType,path:data.path,checksum:data.checksum,metadata:data.metadata}).select('*').single();if(itemError||!item)throw new Response(itemError?.message??'Could not record module artifact',{status:500});await db.from('module_events').insert({module_id:run.module_id,module_version_id:run.module_version_id,run_id:data.runId,event_type:'module.artifact.recorded',payload:{artifactId:item.id,path:data.path},actor_id:context.userId});return item;});
export const listModuleArtifacts=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({moduleId:String(x?.moduleId??''),runId:x?.runId?String(x.runId):undefined})).handler(async({context,data})=>{let q=db.from('module_artifacts').select('*').eq('module_id',data.moduleId).order('created_at',{ascending:false}).limit(200);const adminUser=Boolean((await db.rpc('has_role',{_user_id:context.userId,_role:'admin'})).data);if(data.runId)q=q.eq('run_id',data.runId);if(!adminUser)q=q.eq('owner_id',context.userId);const {data:items,error}=await q;if(error)throw new Response(error.message,{status:500});return items??[];});
export const getModuleVersion=createServerFn({method:'GET',strict:false}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({versionId:String(x?.versionId??'')})).handler(async({context,data})=>{const v=await loadVersion(data.versionId);const adminUser=Boolean((await db.rpc('has_role',{_user_id:context.userId,_role:'admin'})).data);if(v.modules.owner_id!==context.userId&&!adminUser)throw new Response('Forbidden',{status:403});return v;});
