/** Phase K — server-authoritative notification creation, delivery queueing and preferences. */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { buildNotificationLink, validateNotificationOwnership, type NotificationEventType, type NotificationAudience } from "./notifications";
import { deliveryIdempotencyKey, isValidEmail, normalizeEmail } from "./notification-delivery";

const EVENTS: NotificationEventType[]=["task.completed","task.failed","task.waiting_approval","report.ready","research.completed","knowledge.review_required","agent.failed","security.alert","optimization.recommendation","system.alert","approval.required","retry.requested"];
const c=(x:unknown)=>x as any;
async function admin(uid:string){const {data,error}=await supabaseAdmin.rpc("has_role",{_user_id:uid,_role:"admin"});if(error)throw new Response(error.message,{status:500});return !!data;}
export const createPhaseKNotification=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{recipientId:string;eventType:NotificationEventType;title:string;body?:string;resourceType?:string;resourceId?:string;taskId?:string;runId?:string;reportId?:string;resourceOwnerId?:string;audience?:NotificationAudience;idempotencyKey?:string})=>{if(!x?.recipientId||!x?.title?.trim()||!EVENTS.includes(x.eventType))throw new Error("Valid recipientId, eventType and title are required");return {recipientId:String(x.recipientId),eventType:x.eventType,title:x.title.trim().slice(0,200),body:x.body?.trim().slice(0,2000)||null,resourceType:x.resourceType||null,resourceId:x.resourceId||null,taskId:x.taskId||null,runId:x.runId||null,reportId:x.reportId||null,resourceOwnerId:x.resourceOwnerId||null,audience:x.audience||"user",idempotencyKey:x.idempotencyKey?.trim().slice(0,200)||null};}).handler(async({context,data})=>{const recipientAdmin=await admin(data.recipientId),v=validateNotificationOwnership({recipient_id:data.recipientId,audience:data.audience,event_type:data.eventType,title:data.title,body:data.body||undefined,resource_type:data.resourceType||undefined,resource_id:data.resourceId||undefined,task_id:data.taskId||undefined,run_id:data.runId||undefined,report_id:data.reportId||undefined},data.resourceOwnerId,recipientAdmin);if(!v.ok)throw new Response(v.message,{status:403});if(data.idempotencyKey){const {data:old}=await supabaseAdmin.from("notifications").select("id,link,status").eq("recipient_id",data.recipientId).eq("idempotency_key",data.idempotencyKey).maybeSingle();if(old)return {ok:true as const,reused:true,notificationId:old.id,link:old.link,status:old.status};}const link=buildNotificationLink(data.eventType,{taskId:data.taskId,runId:data.runId,reportId:data.reportId,resourceId:data.resourceId},recipientAdmin);const {data:n,error}=await supabaseAdmin.from("notifications").insert({recipient_id:data.recipientId,audience:data.audience,event_type:data.eventType,title:data.title,body:data.body,resource_type:data.resourceType,resource_id:data.resourceId,link,status:"pending",metadata:{task_id:data.taskId,run_id:data.runId,report_id:data.reportId},idempotency_key:data.idempotencyKey}).select("id,link,status").single();if(error||!n)throw new Response(error?.message||"Notification creation failed",{status:500});return {ok:true as const,reused:false,notificationId:n.id,link:n.link,status:n.status};});

export const queuePhaseKDelivery=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{notificationId:string;channel:"in_app"|"email";destination?:string})=>{if(!x?.notificationId||!x.channel)throw new Error("notificationId and channel are required");return {notificationId:String(x.notificationId),channel:x.channel,destination:x.destination?.trim()||null};}).handler(async({context,data})=>{const {data:n,error}=await context.supabase.from("notifications").select("id,recipient_id,title,body,link,status").eq("id",data.notificationId).eq("recipient_id",context.userId).maybeSingle();if(error)throw new Response(error.message,{status:500});if(!n)throw new Response("Notification not found",{status:404});let destination=data.destination;if(data.channel==="email"){const {data:p}=await context.supabase.from("notification_preferences").select("email_enabled,email_address").eq("user_id",context.userId).maybeSingle();if(!p?.email_enabled||!p.email_address)throw new Response("Email delivery is not enabled",{status:409});destination=normalizeEmail(p.email_address);if(!isValidEmail(destination))throw new Response("Configured email address is invalid",{status:409});}if(!destination)destination=context.userId;const key=deliveryIdempotencyKey(n.id,data.channel);const {data:d,error:de}=await supabaseAdmin.from("notification_deliveries").upsert({notification_id:n.id,channel:data.channel,destination,status:"pending",attempts:0,idempotency_key:key,next_attempt_at:new Date().toISOString()},{onConflict:"notification_id,channel,idempotency_key"}).select("id,status").single();if(de||!d)throw new Response(de?.message||"Could not queue delivery",{status:500});return {ok:true as const,deliveryId:d.id,status:d.status};});

export const updateNotificationPreferences=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{inAppEnabled?:boolean;emailEnabled?:boolean;emailAddress?:string|null;eventTypes?:string[]})=>({inAppEnabled:x?.inAppEnabled!==false,emailEnabled:!!x?.emailEnabled,emailAddress:x?.emailAddress?normalizeEmail(x.emailAddress):null,eventTypes:Array.isArray(x?.eventTypes)?x.eventTypes.filter(e=>EVENTS.includes(e as NotificationEventType)).slice(0,EVENTS.length):[]})).handler(async({context,data})=>{if(data.emailEnabled&&(!data.emailAddress||!isValidEmail(data.emailAddress)))throw new Response("A valid email address is required when email delivery is enabled",{status:400});const {error}=await supabaseAdmin.from("notification_preferences").upsert({user_id:context.userId,in_app_enabled:data.inAppEnabled,email_enabled:data.emailEnabled,email_address:data.emailAddress,event_types:data.eventTypes,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(error)throw new Response(error.message,{status:500});return {ok:true as const};});

export const getNotificationPreferences=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data,error}=await context.supabase.from("notification_preferences").select("in_app_enabled,email_enabled,email_address,event_types,updated_at").eq("user_id",context.userId).maybeSingle();if(error)throw new Response(error.message,{status:500});return data??{in_app_enabled:true,email_enabled:false,email_address:null,event_types:[]};});

export const deliverPhaseKPending=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{limit?:number}={})=>({limit:Math.min(25,Math.max(1,Math.floor(Number(x?.limit??10))))})).handler(async({context,data})=>{if(!await admin(context.userId))throw new Response("Administrator authorization required",{status:403});const {data:items,error}=await supabaseAdmin.from("notification_deliveries").select("id,notification_id,channel,destination,attempts").eq("status","pending").lte("next_attempt_at",new Date().toISOString()).order("created_at",{ascending:true}).limit(data.limit);if(error)throw new Response(error.message,{status:500});const results=[] as Array<{id:string;status:string;error?:string}>;for(const item of items??[]){if(item.channel==="in_app"){const now=new Date().toISOString();const {error:e}=await supabaseAdmin.from("notification_deliveries").update({status:"delivered",attempts:item.attempts+1,sent_at:now,updated_at:now,delivered_at:now,error:null}).eq("id",item.id).eq("status","pending");if(e){results.push({id:item.id,status:"failed",error:e.message});continue;}await supabaseAdmin.from("notifications").update({status:"delivered",delivered_at:now,delivery_attempts:item.attempts+1}).eq("id",item.notification_id);results.push({id:item.id,status:"delivered"});}else{const msg="No email provider is configured; delivery remains pending for provider-backed worker execution.";await supabaseAdmin.from("notification_deliveries").update({status:"failed",attempts:item.attempts+1,error:msg,next_attempt_at:new Date(Date.now()+30000).toISOString(),updated_at:new Date().toISOString()}).eq("id",item.id).eq("status","pending");results.push({id:item.id,status:"failed",error:msg});}}return {ok:true as const,processed:results.length,results};});
