/** Phase P — deterministic, provider-independent optimization analysis. */
import type { OptimizationRecommendation } from './optimization';

export interface OptimizationRunSample { id:string; agent_id?:string|null; agent_key?:string|null; status:string; started_at?:string|null; ended_at?:string|null; duration_ms?:number|null; timeout_ms?:number|null; retry_count?:number|null; failure_code?:string|null; }
export interface OptimizationTelemetry { total:number; succeeded:number; failed:number; cancelled:number; waitingApproval:number; retried:number; timedOut:number; successRate:number|null; failureRate:number|null; retryRate:number|null; timeoutRate:number|null; avgDurationMs:number|null; p95DurationMs:number|null; maxDurationMs:number|null; sampleSize:number; }
export interface OptimizationThresholds { minSamples:number; failureRate:number; retryRate:number; timeoutRate:number; avgDurationMs:number; p95DurationMs:number; }
export const DEFAULT_OPTIMIZATION_THRESHOLDS:OptimizationThresholds={minSamples:5,failureRate:0.25,retryRate:0.2,timeoutRate:0.1,avgDurationMs:120_000,p95DurationMs:300_000};

export function stableOptimizationHash(value:unknown):string { const text=JSON.stringify(value); let hash=2166136261; for(let i=0;i<text.length;i+=1){hash=Math.imul(hash^text.charCodeAt(i),16777619);} return (hash>>>0).toString(16).padStart(8,'0'); }
export function recommendationFingerprint(input:{agentKey?:string|null;category:string;title:string;evidence?:Record<string,unknown>;suggestedChange?:Record<string,unknown>}):string{return `phase-p:${stableOptimizationHash(input)}`;}

function durations(runs:OptimizationRunSample[]):number[]{return runs.map(r=>Number(r.duration_ms??(r.started_at&&r.ended_at?new Date(r.ended_at).getTime()-new Date(r.started_at).getTime():NaN))).filter(Number.isFinite).filter(v=>v>=0).sort((a,b)=>a-b);}
function percentile(values:number[],p:number):number|null{if(values.length===0)return null;const index=(values.length-1)*p;const lo=Math.floor(index),hi=Math.ceil(index);if(lo===hi)return values[lo]??null;const a=values[lo]??0,b=values[hi]??a;return Math.round(a+(b-a)*(index-lo));}
export function computeOptimizationTelemetry(runs:OptimizationRunSample[]):OptimizationTelemetry{const total=runs.length,succeeded=runs.filter(r=>r.status==='completed').length,failed=runs.filter(r=>r.status==='failed').length,cancelled=runs.filter(r=>r.status==='cancelled').length,waitingApproval=runs.filter(r=>r.status==='waiting_approval').length,retried=runs.filter(r=>Number(r.retry_count??0)>0).length,timedOut=runs.filter(r=>String(r.failure_code??'').toLowerCase().includes('timeout')||((r.timeout_ms??0)>0&&Number(r.duration_ms??0)>=Number(r.timeout_ms))).length;const ds=durations(runs);const avg=ds.length?Math.round(ds.reduce((a,b)=>a+b,0)/ds.length):null;return{total,succeeded,failed,cancelled,waitingApproval,retried,timedOut,successRate:total?succeeded/total:null,failureRate:total?failed/total:null,retryRate:total?retried/total:null,timeoutRate:total?timedOut/total:null,avgDurationMs:avg,p95DurationMs:percentile(ds,.95),maxDurationMs:ds.length?ds[ds.length-1]??null:null,sampleSize:total};}

export function analyseOptimizationTelemetry(stats:OptimizationTelemetry,thresholds:OptimizationThresholds=DEFAULT_OPTIMIZATION_THRESHOLDS,agentKey?:string|null):OptimizationRecommendation[]{if(stats.total<thresholds.minSamples)return[];const recs:OptimizationRecommendation[]=[];if((stats.failureRate??0)>thresholds.failureRate)recs.push({agent_key:agentKey??null,category:'failures',title:'Elevated failure rate detected',description:`${Math.round((stats.failureRate??0)*100)}% of ${stats.total} sampled runs failed. Investigate failure codes and dependency health before changing retry policy.`,severity:(stats.failureRate??0)>0.5?'high':'medium',status:'pending',evidence:{failureRate:stats.failureRate,total:stats.total,failed:stats.failed},suggested_change:{type:'investigate_failures'}});if((stats.retryRate??0)>thresholds.retryRate)recs.push({agent_key:agentKey??null,category:'retries',title:'High retry pressure detected',description:`${Math.round((stats.retryRate??0)*100)}% of sampled runs retried. Review retry limits and failure causes before increasing retries.`,severity:(stats.retryRate??0)>0.4?'high':'medium',status:'pending',evidence:{retryRate:stats.retryRate,retried:stats.retried,total:stats.total},suggested_change:{type:'review_retry_policy'}});if((stats.timeoutRate??0)>thresholds.timeoutRate)recs.push({agent_key:agentKey??null,category:'retries',title:'Timeout pressure detected',description:`${Math.round((stats.timeoutRate??0)*100)}% of sampled runs reached a timeout condition. Compare p95 duration with the active timeout policy.`,severity:(stats.timeoutRate??0)>0.25?'high':'medium',status:'pending',evidence:{timeoutRate:stats.timeoutRate,timedOut:stats.timedOut,p95DurationMs:stats.p95DurationMs},suggested_change:{type:'review_timeout_policy',p95DurationMs:stats.p95DurationMs}});if((stats.avgDurationMs??0)>thresholds.avgDurationMs||(stats.p95DurationMs??0)>thresholds.p95DurationMs)recs.push({agent_key:agentKey??null,category:'latency',title:'Execution latency is above target',description:`Average/p95 duration is ${Math.round((stats.avgDurationMs??0)/1000)}s/${Math.round((stats.p95DurationMs??0)/1000)}s. Review concurrency, model routing and external dependencies.`,severity:(stats.p95DurationMs??0)>thresholds.p95DurationMs*2?'high':'medium',status:'pending',evidence:{avgDurationMs:stats.avgDurationMs,p95DurationMs:stats.p95DurationMs,maxDurationMs:stats.maxDurationMs},suggested_change:{type:'review_latency'}});return recs;}
