/** Phase N — durable, provider-independent multi-agent orchestration primitives. */
import type { AgentKey } from "./agents";
import { AGENTS } from "./agents";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { authorizeAgentAction, appendAgentMessage } from "./agent-runtime";
import { exponentialBackoffMs, resolveTimeoutMs, type TaskRecord } from "./task-runtime";
export type OrchestrationStepStatus="pending"|"ready"|"running"|"waiting_approval"|"completed"|"failed"|"skipped"|"cancelled";
export type OrchestrationPlanStatus="draft"|"ready"|"running"|"waiting_approval"|"completed"|"failed"|"cancelled"|"paused";
export type OrchestrationGateType="approval"|"verification"|"policy";
export interface OrchestrationStepDefinition{stepId:string;agentKey:AgentKey;title:string;input?:Record<string,unknown>;dependsOn?:string[];requiresApproval?:boolean;requiresVerification?:boolean;maxRetries?:number;timeoutMs?:number;critical?:boolean;}
export interface OrchestrationPlanDefinition{taskId:string;objective:string;steps:OrchestrationStepDefinition[];context?:Record<string,unknown>;}
export interface OrchestrationDecision{stepId:string;agentKey:AgentKey;reason:string;score:number;}
const db=supabaseAdmin as any;const AGENT_SET=new Set<AgentKey>(AGENTS.map(a=>a.key));
export function validateOrchestrationPlan(plan:OrchestrationPlanDefinition):string[]{const errors:string[]=[];if(!plan.taskId)errors.push("taskId is required");if(!plan.objective?.trim())errors.push("objective is required");if(!Array.isArray(plan.steps)||!plan.steps.length)errors.push("At least one orchestration step is required");const ids=new Set<string>();for(const s of plan.steps??[]){if(!s.stepId||ids.has(s.stepId))errors.push(`Duplicate or empty stepId: ${s.stepId||"<empty>"}`);ids.add(s.stepId);if(!AGENT_SET.has(s.agentKey))errors.push(`Unknown agent: ${s.agentKey}`);if(s.agentKey==="orchestrator")errors.push("Orchestrator cannot delegate to itself");if(s.maxRetries!==undefined&&(!Number.isInteger(s.maxRetries)||s.maxRetries<0||s.maxRetries>20))errors.push(`Invalid maxRetries for ${s.stepId}`);if(s.timeoutMs!==undefined){try{resolveTimeoutMs(s.timeoutMs);}catch{errors.push(`Invalid timeout for ${s.stepId}`)}}}for(const s of plan.steps??[])for(const dep of s.dependsOn??[])if(!ids.has(dep))errors.push(`Unknown dependency ${dep} for ${s.stepId}`);if(!errors.length){const visiting=new Set<string>(),visited=new Set<string>();const walk=(id:string)=>{if(visiting.has(id)){errors.push("Orchestration plan contains a dependency cycle");return;}if(visited.has(id))return;visiting.add(id);const s=plan.steps.find(x=>x.stepId===id);for(const d of s?.dependsOn??[])walk(d);visiting.delete(id);visited.add(id);};for(const s of plan.steps)walk(s.stepId);}return[...new Set(errors)];}
export function readyStepIds(steps:Array<{step_id:string;status:OrchestrationStepStatus;depends_on?:string[]|null}>):string[]{const byId=new Map(steps.map(s=>[s.step_id,s]));return steps.filter(s=>s.status==="pending"&&(s.depends_on??[]).every(d=>byId.get(d)?.status==="completed")).map(s=>s.step_id);}
export function aggregateResults(results:Array<{stepId:string;agentKey:AgentKey;status:string;result?:Record<string,unknown>;warnings?:string[];errors?:string[]}>){const warnings=results.flatMap(r=>r.warnings??[]),errors=results.flatMap(r=>r.errors??[]),failed=results.some(r=>r.status==="failed");return{status:failed?"failed":"completed" as "failed"|"completed",result:{steps:results.map(r=>({stepId:r.stepId,agentKey:r.agentKey,status:r.status,result:r.result??{}}))},warnings,errors};}
export function selectAgent(agentKey:AgentKey):OrchestrationDecision{if(!AGENT_SET.has(agentKey))throw new Error(`Unknown agent: ${agentKey}`);if(agentKey==="orchestrator")throw new Error("Orchestrator cannot select itself as a worker");const a=AGENTS.find(x=>x.key===agentKey)!;return{stepId:"",agentKey,reason:`Selected ${a.name} for its declared mission and tool territory`,score:1};}
export function makeOrchestrationIdempotencyKey(taskId:string,objective:string){return`aether:orchestration:${taskId}:${stableHash(objective)}`;}
function stableHash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
export function retryDelay(retryCount:number){return exponentialBackoffMs(retryCount,5000,300000);}
export async function createOrchestrationPlan(input:OrchestrationPlanDefinition&{ownerId:string}){const errors=validateOrchestrationPlan(input);if(errors.length)throw new Error(errors.join("; "));const{data,error}=await db.rpc("create_orchestration_plan",{p_task_id:input.taskId,p_owner_id:input.ownerId,p_objective:input.objective,p_context:input.context??{},p_idempotency_key:makeOrchestrationIdempotencyKey(input.taskId,input.objective),p_steps:input.steps});if(error||!data)throw new Error(error?.message??"Could not create orchestration plan");return data;}
export async function dispatchReadyStep(input:{planId:string;stepId:string;task:TaskRecord;actorId:string}){const{data:step,error}=await db.from("orchestration_steps").select("*").eq("plan_id",input.planId).eq("step_id",input.stepId).single();if(error||!step)throw new Error("Orchestration step not found");const{data:plan}=await db.from("orchestration_plans").select("*").eq("id",input.planId).single();if(!plan||plan.owner_id!==input.task.owner_id)throw new Error("Forbidden: orchestration plan ownership mismatch");const{data:ready,error:readyError}=await db.rpc("orchestration_step_ready",{p_step_id:step.id});if(readyError||!ready)throw new Error(readyError?.message??"Step dependencies are not complete");const auth=await authorizeAgentAction({agentKey:step.agent_key,permission:"orchestration.execute",action:"orchestration.execute",taskId:input.task.id,actorId:input.actorId});if(!auth.allowed)throw new Error(auth.reason);const{data:claimed,error:claimError}=await db.rpc("claim_orchestration_step",{p_step_id:step.id,p_actor_id:input.actorId});if(claimError||!claimed)throw new Error(claimError?.message??"Step claim failed");return claimed;}
export async function recordStepResult(input:{stepId:string;status:OrchestrationStepStatus;result?:Record<string,unknown>;warnings?:string[];errors?:string[];actorId:string}){const{data,error}=await db.rpc("complete_orchestration_step",{p_step_id:input.stepId,p_status:input.status,p_result:input.result??{},p_warnings:input.warnings??[],p_errors:input.errors??[],p_actor_id:input.actorId});if(error||!data)throw new Error(error?.message??"Could not record orchestration result");return data;}
export async function requestGate(input:{stepId:string;gateType:OrchestrationGateType;actorId:string;reason:string}){const{data,error}=await db.rpc("request_orchestration_gate",{p_step_id:input.stepId,p_gate_type:input.gateType,p_reason:input.reason,p_actor_id:input.actorId});if(error||!data)throw new Error(error?.message??"Could not request orchestration gate");return data;}
export async function handoffStep(input:{taskId:string;runId:string;fromAgent:AgentKey;toAgent:AgentKey;payload:Record<string,unknown>;actorId:string}){return appendAgentMessage({taskId:input.taskId,runId:input.runId,fromAgent:input.fromAgent,toAgent:input.toAgent,type:"orchestration.handoff",payload:input.payload,actorId:input.actorId});}
export async function recoverOrchestrationPlans(){const{data,error}=await db.rpc("recover_orchestration_plans");if(error)throw new Error(error.message);return data??0;}
