import type { SupabaseClient } from "@supabase/supabase-js";
import { appendTaskEvent, createRun, transitionRunStatus } from "./task-service";
import { traceOrchestrationEvent } from "./orchestration-trace";
import type { TaskStatus } from "./task-runtime";

export type StepState = "pending" | "ready" | "running" | "waiting_approval" | "completed" | "failed" | "skipped";
interface StepRow { id: string; sequence: number; dependencies: string[] | null; status: StepState; agent_key: string | null; model_role: string | null; title: string; expected_output: Record<string, unknown> | null; }
function dependencySatisfied(step: StepRow, steps: StepRow[]) { const deps = Array.isArray(step.dependencies) ? step.dependencies : []; return deps.every((dep) => steps.some((candidate) => (candidate.id === dep || candidate.id === String(dep)) && candidate.status === "completed")); }
function tokenize(value: string) { return Array.from(new Set(value.toLowerCase().normalize("NFKC").match(/[\p{L}\p{N}]{2,}/gu) ?? [])); }

async function retrieveApprovedKnowledgeForPlan(admin: SupabaseClient, ownerId: string, projectId: string | null, query: string) {
  const terms = tokenize(query).slice(0, 32); if (!terms.length) return [];
  let chunkQuery = admin.from("aether_knowledge_chunks").select("id,entry_id,project_id,version,content,metadata").eq("owner_id", ownerId).eq("is_current", true);
  if (projectId) chunkQuery = chunkQuery.eq("project_id", projectId);
  const { data: chunks, error: chunkError } = await chunkQuery.limit(3000); if (chunkError) throw new Error(`Approved knowledge retrieval failed: ${chunkError.message}`);
  const entryIds = Array.from(new Set((chunks ?? []).map((chunk) => chunk.entry_id))); if (!entryIds.length) return [];
  const { data: entries, error: entryError } = await admin.from("knowledge_entries").select("id,title,stage,current_version").eq("owner_id", ownerId).eq("stage", "production").in("id", entryIds); if (entryError) throw new Error(`Approved knowledge metadata lookup failed: ${entryError.message}`);
  const entryMap = new Map((entries ?? []).map((entry) => [entry.id, entry]));
  return (chunks ?? []).map((chunk) => { const entry = entryMap.get(chunk.entry_id); if (!entry) return null; const lower = String(chunk.content ?? "").toLowerCase(); const matched = terms.filter((term) => lower.includes(term)); return { entryId: entry.id, title: entry.title, version: entry.current_version, score: matched.length / terms.length, matchedTerms: matched, content: String(chunk.content ?? "").slice(0, 4000), provenance: { source: "approved-production-knowledge", version: entry.current_version, chunkId: chunk.id } }; }).filter((value): value is NonNullable<typeof value> => Boolean(value)).filter((value) => value.score > 0).sort((a, b) => b.score - a.score).slice(0, 8);
}

export async function prepareNextOrchestrationSteps(admin: SupabaseClient, planId: string, actorId: string) { const { data: plan, error: planError } = await admin.from("orchestration_plans").select("id, task_id, run_id, owner_id, context, status, approval_status").eq("id", planId).maybeSingle(); if (planError || !plan) throw new Error("Orchestration plan not found"); if (plan.owner_id !== actorId) throw new Error("Orchestration access denied"); if (plan.approval_status === "pending") return { ready: [], waitingApproval: true }; const { data: rawSteps, error } = await admin.from("orchestration_steps").select("id, sequence, dependencies, status, agent_key, model_role, title, expected_output").eq("plan_id", planId).order("sequence"); if (error) throw new Error(error.message); const steps = (rawSteps ?? []) as StepRow[]; const ready = steps.filter((step) => (step.status === "pending" || step.status === "ready") && dependencySatisfied(step, steps)); if (ready.length) await admin.from("orchestration_steps").update({ status: "ready" }).in("id", ready.map((step) => step.id)).eq("plan_id", planId); return { ready, waitingApproval: false }; }

export async function createAgentStepRun(admin: SupabaseClient, planId: string, stepId: string, actorId: string) { const { data: plan } = await admin.from("orchestration_plans").select("id, task_id, owner_id, run_id, context").eq("id", planId).maybeSingle(); if (!plan || plan.owner_id !== actorId) throw new Error("Orchestration access denied"); const { data: step } = await admin.from("orchestration_steps").select("id, status, agent_key, model_role, title, task_id, plan_id").eq("id", stepId).eq("plan_id", planId).maybeSingle(); if (!step || !["ready", "pending"].includes(step.status)) throw new Error("Step is not ready for execution"); if (!step.agent_key) throw new Error("Step has no authorized agent"); const context = plan.context && typeof plan.context === "object" ? plan.context as Record<string, unknown> : {}; const query = String(context.requestText ?? context.query ?? "").trim().slice(0, 20000); const projectId = typeof context.projectId === "string" ? context.projectId : null; const approvedKnowledge = await retrieveApprovedKnowledgeForPlan(admin, actorId, projectId, query); const run = await createRun(admin, { task_id: plan.task_id, owner_id: actorId, agent_key: step.agent_key, inputs: { plan_id: planId, step_id: stepId, model_role: step.model_role, approved_knowledge: approvedKnowledge }, timeout_ms: "1h", max_retries: 3, idempotency_key: `aether:orchestration-step:${planId}:${stepId}` }); await admin.from("orchestration_steps").update({ status: "running", run_id: run.id, started_at: new Date().toISOString() }).eq("id", stepId).eq("plan_id", planId); await traceOrchestrationEvent(admin, { planId, taskId: plan.task_id, runId: run.id, stepId, actorId, actorType: "orchestrator", eventType: "step.delegated", action: "delegate_agent_step", reason: `Delegated step to authorized agent ${step.agent_key}`, decision: "execute", data: { agent_key: step.agent_key, model_role: step.model_role, approvedKnowledgeCount: approvedKnowledge.length } }); return run; }

export async function completeAgentStep(admin: SupabaseClient, planId: string, stepId: string, actorId: string, output: Record<string, unknown>) { const { data: plan } = await admin.from("orchestration_plans").select("id, task_id, owner_id").eq("id", planId).maybeSingle(); if (!plan || plan.owner_id !== actorId) throw new Error("Orchestration access denied"); const { data: step } = await admin.from("orchestration_steps").select("id, run_id, status").eq("id", stepId).eq("plan_id", planId).maybeSingle(); if (!step || step.status !== "running") throw new Error("Step is not running"); if (step.run_id) { const run = await admin.from("task_runs").select("status").eq("id", step.run_id).single(); if (!run.error && run.data) await transitionRunStatus(admin, step.run_id, run.data.status as TaskStatus, "completed", { outputs: output, actorId }); } await admin.from("orchestration_steps").update({ status: "completed", ended_at: new Date().toISOString(), output }).eq("id", stepId).eq("plan_id", planId); await traceOrchestrationEvent(admin, { planId, taskId: plan.task_id, runId: step.run_id, stepId, actorId, actorType: "agent", eventType: "step.completed", action: "complete_agent_step", reason: "Agent step completed", decision: "continue", data: { output_keys: Object.keys(output) } }); await prepareNextOrchestrationSteps(admin, planId, actorId); }

export async function failAgentStep(admin: SupabaseClient, planId: string, stepId: string, actorId: string, reason: string) { const { data: plan } = await admin.from("orchestration_plans").select("id, task_id, owner_id").eq("id", planId).maybeSingle(); if (!plan || plan.owner_id !== actorId) throw new Error("Orchestration access denied"); const { data: step } = await admin.from("orchestration_steps").select("id, run_id, status").eq("id", stepId).eq("plan_id", planId).maybeSingle(); if (!step || step.status !== "running") throw new Error("Step is not running"); if (step.run_id) { const run = await admin.from("task_runs").select("status").eq("id", step.run_id).single(); if (!run.error && run.data) await transitionRunStatus(admin, step.run_id, run.data.status as TaskStatus, "failed", { error: reason, failureCode: "agent_step_failed", retryable: false, actorId }); } await admin.from("orchestration_steps").update({ status: "failed", ended_at: new Date().toISOString(), error: { message: reason } }).eq("id", stepId).eq("plan_id", planId); await appendTaskEvent(admin, { taskId: plan.task_id, eventType: "orchestration.step_failed", message: reason.slice(0, 1000), data: { plan_id: planId, step_id: stepId }, actorId }); await traceOrchestrationEvent(admin, { planId, taskId: plan.task_id, runId: step.run_id, stepId, actorId, actorType: "agent", eventType: "step.failed", action: "fail_agent_step", reason, decision: "escalate", data: {} }); }
