/** Phase N — authenticated durable orchestration control-plane functions. */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { createOrchestrationPlan,dispatchReadyStep,recordStepResult,requestGate,recoverOrchestrationPlans,validateOrchestrationPlan } from "./orchestrator";
import type { AgentKey } from "./agents";
const db=supabaseAdmin as any;async function isAdmin(userId:string){const{data}=await db.rpc("has_role",{_user_id:userId,_role:"admin"});return Boolean(data)}function key(v:unknown):AgentKey{return String(v||"") as AgentKey}
export const createOrchestration=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>{const p=x?.plan;if(!p||typeof p!=="object")throw new Response("Plan is required",{status:400});const n={taskId:String(p.taskId||""),objective:String(p.objective||""),context:p.context&&typeof p.context==="object"?p.context:{},steps:Array.isArray(p.steps)?p.steps.map((s:any)=>({stepId:String(s?.stepId||""),agentKey:key(s?.agentKey),title:String(s?.title||""),input:s?.input&&typeof s.input==="object"?s.input:{},dependsOn:Array.isArray(s?.dependsOn)?s.dependsOn.map(String):[],requiresApproval:Boolean(s?.requiresApproval),requiresVerification:Boolean(s?.requiresVerification),maxRetries:s?.maxRetries===undefined?2:Number(s.maxRetries),timeoutMs:s?.timeoutMs===undefined?300000:Number(s.timeoutMs),critical:Boolean(s?.critical)})):[]};const e=validateOrchestrationPlan(n);if(e.length)throw new Response(e.join("; "),{status:400});return n}).handler(async({context,data})=>createOrchestrationPlan({...data,ownerId:context.userId}));
export const listOrchestrationPlans=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const{data,error}=await db.from("orchestration_plans").select("*").eq("owner_id",context.userId).order("updated_at",{ascending:false});if(error)throw new Response(error.message,{status:500});return data??[]});
export const getOrchestration=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((x:{planId:string})=>x).handler(async({context,data})=>{const{data:plan,error}=await db.from("orchestration_plans").select("*").eq("id",data.planId).single();if(error||!plan)throw new Response("Orchestration plan not found",{status:404});if(plan.owner_id!==context.userId&&!await isAdmin(context.userId))throw new Response("Forbidden",{status:403});const[{data:steps},{data:gates}]=await Promise.all([db.from("orchestration_steps").select("*").eq("plan_id",plan.id).order("sequence"),db.from("orchestration_gates").select("*").eq("plan_id",plan.id).order("created_at")]);const{data:runtime}=await db.from("orchestration_step_runtime").select("*").eq("plan_id",plan.id).order("sequence");return{plan,steps:steps??[],runtime:runtime??[],gates:gates??[]}});
export const dispatchOrchestrationStep=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{planId:string;stepId:string;taskId:string})=>x).handler(async({context,data})=>{const{data:task,error}=await db.from("tasks").select("id,owner_id").eq("id",data.taskId).single();if(error||!task)throw new Response("Task not found",{status:404});if(task.owner_id!==context.userId&&!await isAdmin(context.userId))throw new Response("Forbidden",{status:403});return dispatchReadyStep({...data,actorId:context.userId})});
export const completeOrchestrationStep=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({stepId:String(x?.stepId||""),status:String(x?.status||""),result:x?.result&&typeof x.result==="object"?x.result:{},warnings:Array.isArray(x?.warnings)?x.warnings.map(String):[],errors:Array.isArray(x?.errors)?x.errors.map(String):[]})).handler(async({context,data})=>recordStepResult({...data,status:data.status as any,actorId:context.userId}));
export const requestOrchestrationGate=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{stepId:string;gateType:"approval"|"verification"|"policy";reason:string})=>x).handler(async({context,data})=>requestGate({...data,actorId:context.userId}));
export const recoverOrchestration=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).handler(async({context})=>{if(!await isAdmin(context.userId))throw new Response("Administrator authorization required",{status:403});return recoverOrchestrationPlans()});
