// @ts-nocheck
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { createPhaseNPlan,dispatchPhaseNStep,recordPhaseNStepResult,requestPhaseNGate,recoverPhaseN,validatePhaseNPlan } from "./phase-n-orchestrator";
export const createPhaseNOrchestration=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>{const p=x?.plan;if(!p)throw new Response("Plan is required",{status:400});const n={taskId:String(p.taskId||""),objective:String(p.objective||""),context:p.context&&typeof p.context==="object"?p.context:{},steps:Array.isArray(p.steps)?p.steps:[]};const e=validatePhaseNPlan(n);if(e.length)throw new Response(e.join("; "),{status:400});return n}).handler(async({context,data}:any)=>createPhaseNPlan({...data,ownerId:context.userId}));
export const getPhaseNOrchestration=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>{const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const{data:plan,error}=await supabaseAdmin.from("orchestration_plans").select("*").eq("id",data.planId).single();if(error||!plan)throw new Response("Orchestration plan not found",{status:404});if(plan.owner_id!==context.userId){const{data:isAdmin}=await supabaseAdmin.rpc("has_role",{_user_id:context.userId,_role:"admin"});if(!isAdmin)throw new Response("Forbidden",{status:403})}const{data:runtime}=await supabaseAdmin.from("orchestration_step_runtime").select("*").eq("plan_id",plan.id).order("sequence");const{data:gates}=await supabaseAdmin.from("orchestration_gates").select("*").eq("plan_id",plan.id).order("created_at");return{plan,runtime:runtime??[],gates:gates??[]}});
export const dispatchPhaseNOrchestrationStep=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>dispatchPhaseNStep({...data,actorId:context.userId}));
export const completePhaseNOrchestrationStep=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>recordPhaseNStepResult({...data,actorId:context.userId}));
export const requestPhaseNOrchestrationGate=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>requestPhaseNGate({...data,actorId:context.userId}));
export const recoverPhaseNOrchestration=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).handler(async({context}:any)=>{const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const{data:isAdmin}=await supabaseAdmin.rpc("has_role",{_user_id:context.userId,_role:"admin"});if(!isAdmin)throw new Response("Administrator authorization required",{status:403});return recoverPhaseN()});
