import { createCipheriv, randomBytes } from "node:crypto";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { hashZ2Secret, makeZ2Secret } from "./phase-z2-api";
function encryptionKey(): Buffer { const raw = process.env.AETHER_API_KEY_ENCRYPTION_KEY?.trim(); if (!raw) throw new Error("Missing server configuration: AETHER_API_KEY_ENCRYPTION_KEY"); if (/^[0-9a-fA-F]{64}$/.test(raw)) return Buffer.from(raw, "hex"); const decoded = Buffer.from(raw, "base64url"); if (decoded.length !== 32) throw new Error("AETHER_API_KEY_ENCRYPTION_KEY must encode exactly 32 bytes"); return decoded; }
function encryptSecret(secret: string) { const iv=randomBytes(12); const cipher=createCipheriv("aes-256-gcm",encryptionKey(),iv); const ciphertext=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]); return `1.${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${ciphertext.toString("base64url")}`; }
export async function rotateZ2ApiKeyGracefully(ownerId: string,keyId: string,actorId: string,admin=false) {
  let query=supabaseAdmin.from("aether_api_keys").select("*").eq("id",keyId).eq("api_kind","aax"); if(!admin) query=query.eq("owner_id",ownerId); const {data:old,error}=await query.maybeSingle(); if(error||!old) throw new Response("API key not found",{status:404}); if(old.status==='revoked') throw new Response("Revoked API keys cannot be rotated",{status:409});
  const {data:model,error:modelError}=await supabaseAdmin.from("aax_models").select("id,model_key,generation,revision").eq("model_key",old.model_key).maybeSingle(); if(modelError||!model) throw new Response("The key's AAX model no longer exists",{status:409});
  const secret=makeZ2Secret(model.generation,model.revision); const encryptedSecret=encryptSecret(secret); const {data:replacement,error:insertError}=await supabaseAdmin.from("aether_api_keys").insert({owner_id:old.owner_id,project_id:old.project_id,name:old.name, key_prefix:secret.slice(0,16),key_hash:hashZ2Secret(secret),scopes:old.scopes,rate_limit_per_minute:old.rate_limit_per_minute,expires_at:old.expires_at,api_kind:'aax',model_id:model.id,model_key:model.model_key,model_generation:model.generation,model_revision:model.revision,environment:old.environment,application_name:old.application_name,encrypted_secret:encryptedSecret,secret_version:1,secret_recovery_available:true,status:'active',monthly_token_limit:old.monthly_token_limit,unlimited_tokens:old.unlimited_tokens,max_tokens_per_request:old.max_tokens_per_request,max_input_tokens:old.max_input_tokens,max_output_tokens:old.max_output_tokens,metadata:old.metadata??{}}).select("id,owner_id,name,application_name,environment,key_prefix,model_key,model_generation,model_revision,rate_limit_per_minute,expires_at,status,monthly_token_limit,unlimited_tokens,max_tokens_per_request,max_input_tokens,max_output_tokens,secret_recovery_available,created_at,updated_at").single(); if(insertError||!replacement) throw new Error(`Could not create replacement API key: ${insertError?.message??'unknown error'}`);
  const {error:revokeError}=await supabaseAdmin.from("aether_api_keys").update({status:'revoked',revoked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",old.id).eq("status","active"); if(revokeError) { await supabaseAdmin.from("aether_api_keys").update({status:'revoked',revoked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",replacement.id); throw new Error(`Could not complete API key rotation: ${revokeError.message}`); }
  await supabaseAdmin.from("aether_api_key_events").insert([{api_key_id:old.id,owner_id:old.owner_id,actor_id:actorId,event_type:'rotated',action_source:admin?'admin':'user',metadata:{replacementKeyId:replacement.id}},{api_key_id:replacement.id,owner_id:old.owner_id,actor_id:actorId,event_type:'created_by_rotation',action_source:admin?'admin':'user',metadata:{replacesKeyId:old.id}}]);
  return {...replacement,key:secret,replacedKeyId:old.id};
}
