import type { AgentKey } from "./agents";
import { AGENTS } from "./agents";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { authorizeAgentAction, appendAgentMessage } from "./agent-runtime";
import { exponentialBackoffMs, resolveTimeoutMs } from "./task-runtime";
export type PhaseNStepStatus="pending"|"ready"|"running"|"waiting_approval"|"completed"|"failed"|"skipped"|"cancelled";
export type PhaseNGateType="approval"|"verification"|"policy";
export interface PhaseNStepDefinition{stepId:string;agentKey:AgentKey;title:string;input?:Record<string,unknown>;dependsOn?:string[];requiresApproval?:boolean;requiresVerification?:boolean;maxRetries?:number;timeoutMs?:number;critical?:boolean;}
export interface PhaseNPlanDefinition{taskId:string;objective:string;steps:PhaseNStepDefinition[];context?:Record<string,unknown>;}
const db=supabaseAdmin as any;const AGENT_SET=new Set<AgentKey>(AGENTS.map(a=>a.key));
export function validatePhaseNPlan(plan:PhaseNPlanDefinition):string[]{const errors:string[]=[];if(!plan.taskId)errors.push("taskId is required");if(!plan.objective?.trim())errors.push("objective is required");if(!Array.isArray(plan.steps)||!plan.steps.length)errors.push("At least one orchestration step is required");const ids=new Set<string>();for(const s of plan.steps??[]){if(!s.stepId||ids.has(s.stepId))errors.push(`Duplicate or empty stepId: ${s.stepId||"<empty>"}`);ids.add(s.stepId);if(!AGENT_SET.has(s.agentKey))errors.push(`Unknown agent: ${s.agentKey}`);if(s.agentKey==="orchestrator")errors.push("Orchestrator cannot delegate to itself");if(s.maxRetries!==undefined&&(!Number.isInteger(s.maxRetries)||s.maxRetries<0||s.maxRetries>20))errors.push(`Invalid maxRetries for ${s.stepId}`);if(s.timeoutMs!==undefined){try{resolveTimeoutMs(s.timeoutMs)}catch{errors.push(`Invalid timeout for ${s.stepId}`)}}}for(const s of plan.steps??[])for(const d of s.dependsOn??[])if(!ids.has(d))errors.push(`Unknown dependency ${d} for ${s.stepId}`);if(!errors.length){const visiting=new Set<string>(),visited=new Set<string>();const walk=(id:string)=>{if(visiting.has(id)){errors.push("Orchestration plan contains a dependency cycle");return}if(visited.has(id))return;visiting.add(id);const s=plan.steps.find(x=>x.stepId===id);for(const d of s?.dependsOn??[])walk(d);visiting.delete(id);visited.add(id)};for(const s of plan.steps)walk(s.stepId)}return[...new Set(errors)]}
export function readyPhaseNStepIds(steps:Array<{step_id:string;status:PhaseNStepStatus;depends_on?:string[]|null}>){const byId=new Map(steps.map(s=>[s.step_id,s]));return steps.filter(s=>s.status==="pending"&&(s.depends_on??[]).every(d=>byId.get(d)?.status==="completed")).map(s=>s.step_id)}
export function aggregatePhaseNResults(results:Array<{stepId:string;agentKey:AgentKey;status:string;result?:Record<string,unknown>;warnings?:string[];errors?:string[]}>){const warnings=results.flatMap(r=>r.warnings??[]),errors=results.flatMap(r=>r.errors??[]);return{status:results.some(r=>r.status==="failed")?"failed":"completed",result:{steps:results.map(r=>({stepId:r.stepId,agentKey:r.agentKey,status:r.status,result:r.result??{}}))},warnings,errors}}
export function selectPhaseNAgent(agentKey:AgentKey){if(!AGENT_SET.has(agentKey))throw new Error(`Unknown agent: ${agentKey}`);if(agentKey==="orchestrator")throw new Error("Orchestrator cannot select itself as a worker");const a=AGENTS.find(x=>x.key===agentKey)!;return{agentKey,reason:`Selected ${a.name} for its declared mission and tool territory`,score:1}}
export function makePhaseNIdempotencyKey(taskId:string,objective:string){let h=2166136261;for(let i=0;i<objective.length;i++){h^=objective.charCodeAt(i);h=Math.imul(h,16777619)}return`aether:orchestration:${taskId}:${(h>>>0).toString(16)}`}export function phaseNRetryDelay(retryCount:number){return exponentialBackoffMs(retryCount,5000,300000)}
export async function createPhaseNPlan(input:PhaseNPlanDefinition&{ownerId:string}){const errors=validatePhaseNPlan(input);if(errors.length)throw new Error(errors.join(";"));const{data,error}=await db.rpc("create_phase_n_orchestration_plan",{p_task_id:input.taskId,p_owner_id:input.ownerId,p_objective:input.objective,p_context:input.context??{},p_idempotency_key:makePhaseNIdempotencyKey(input.taskId,input.objective),p_steps:input.steps});if(error||!data)throw new Error(error?.message??"Could not create orchestration plan");return data}
export async function dispatchPhaseNStep(input:{planId:string;stepId:string;taskId:string;actorId:string}){const{data:step,error}=await db.from("orchestration_step_runtime").select("*").eq("plan_id",input.planId).eq("step_key",input.stepId).single();if(error||!step)throw new Error("Orchestration step not found");const{data:plan}=await db.from("orchestration_plans").select("*").eq("id",input.planId).single();if(!plan||plan.owner_id!==input.actorId)throw new Error("Forbidden: orchestration plan ownership mismatch");const auth=await authorizeAgentAction({agentKey:step.agent_key,permission:"orchestration.execute",action:"orchestration.execute",taskId:input.taskId,actorId:input.actorId});if(!auth.allowed)throw new Error(auth.reason);const{data:claimed,error:claimError}=await db.rpc("claim_phase_n_step",{p_runtime_step_id:step.id,p_actor_id:input.actorId});if(claimError||!claimed)throw new Error(claimError?.message??"Step claim failed");return claimed}
export async function recordPhaseNStepResult(input:{stepId:string;status:PhaseNStepStatus;result?:Record<string,unknown>;warnings?:string[];errors?:string[];actorId:string}){const{data,error}=await db.rpc("complete_phase_n_step",{p_runtime_step_id:input.stepId,p_status:input.status,p_result:input.result??{},p_warnings:input.warnings??[],p_errors:input.errors??[],p_actor_id:input.actorId});if(error||!data)throw new Error(error?.message??"Could not record orchestration result");return data}
export async function requestPhaseNGate(input:{stepId:string;gateType:PhaseNGateType;actorId:string;reason:string}){const{data,error}=await db.rpc("request_phase_n_gate",{p_runtime_step_id:input.stepId,p_gate_type:input.gateType,p_reason:input.reason,p_actor_id:input.actorId});if(error||!data)throw new Error(error?.message??"Could not request orchestration gate");return data}
export async function handoffPhaseNStep(input:{taskId:string;runId:string;fromAgent:AgentKey;toAgent:AgentKey;payload:Record<string,unknown>;actorId:string}){return appendAgentMessage({taskId:input.taskId,runId:input.runId,fromAgent:input.fromAgent,toAgent:input.toAgent,type:"orchestration.handoff",payload:input.payload,actorId:input.actorId})}
export async function recoverPhaseN(){const{data,error}=await db.rpc("recover_phase_n_steps");if(error)throw new Error(error.message);return data??0}
