/** Phase J — deterministic, provider-independent report/PDF composition. */
export type ReportVerificationStatus = "verified" | "needs_review" | "conflicting" | "unsupported" | "outdated" | "pending";
export type ReportApprovalStatus = "pending" | "approved" | "rejected";
export interface ReportSource { title: string; url?: string | null; publishedAt?: string | null; retrievedAt?: string | null; authority?: number | null; }
export interface ReportFinding { claim: string; evidence?: string | null; verificationStatus?: ReportVerificationStatus; confidence?: number | null; }
export interface ReportData { title: string; topic?: string | null; sessionId?: string | null; runId?: string | null; generatedAt: string; verificationStatus: ReportVerificationStatus; approvalStatus: ReportApprovalStatus; version: number; sources: ReportSource[]; verifiedFindings: ReportFinding[]; unresolvedClaims: ReportFinding[]; notes?: string[]; }

const PAGE_W = 612, PAGE_H = 792, LEFT = 54, TOP = 54, BOTTOM = 54, LEADING = 14, MAX = 92;
function safeText(value: string): string { return value.normalize("NFKC").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[—–]/g, "-").replace(/[“”]/g, '"').replace(/[‘’]/g, "'").replace(/•/g, "*").replace(/\u00a0/g, " ").replace(/[^\x09\x20-\x7e]/g, "?"); }
function escapePdf(value: string): string { return safeText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)"); }
export function wrapReportText(value: string, maxChars = MAX): string[] { const s = safeText(value).replace(/\s+/g, " ").trim(); if (!s) return [""]; const out: string[] = []; let line = ""; for (const word of s.split(" ")) { if (word.length > maxChars) { if (line) { out.push(line); line = ""; } for (let i = 0; i < word.length; i += maxChars) out.push(word.slice(i, i + maxChars)); continue; } const next = line ? `${line} ${word}` : word; if (next.length > maxChars) { out.push(line); line = word; } else line = next; } if (line) out.push(line); return out; }
export function slugifyReportFilename(title: string, reportId: string, version: number): string { const slug = safeText(title).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 72) || "aether-report"; return `${slug}-${reportId.slice(0, 8)}-v${version}.pdf`; }
function reportLines(d: ReportData): string[] { const lines = ["AETHER AI PLATFORM", d.title, ...(d.topic ? [`Topic: ${d.topic}`] : []), `Research session: ${d.sessionId ?? "N/A"}`, `Generation run: ${d.runId ?? "N/A"}`, `Generated: ${d.generatedAt}`, `Verification status: ${d.verificationStatus}`, `Approval state: ${d.approvalStatus}`, `Report version: ${d.version}`, "", "VERIFIED FINDINGS"]; if (!d.verifiedFindings.length) lines.push("No verified findings were supplied."); for (const f of d.verifiedFindings) { lines.push(`- ${f.claim}`); if (f.evidence) lines.push(`  Evidence: ${f.evidence}`); if (f.confidence != null) lines.push(`  Confidence: ${Math.max(0, Math.min(1, f.confidence)).toFixed(2)}`); } lines.push("", "UNRESOLVED CLAIMS"); if (!d.unresolvedClaims.length) lines.push("None recorded."); for (const f of d.unresolvedClaims) { lines.push(`- ${f.claim}`); if (f.evidence) lines.push(`  Evidence: ${f.evidence}`); if (f.verificationStatus) lines.push(`  Status: ${f.verificationStatus}`); } lines.push("", "SOURCES"); if (!d.sources.length) lines.push("No sources recorded."); d.sources.forEach((s, i) => { lines.push(`${i + 1}. ${s.title}`); if (s.url) lines.push(`   ${s.url}`); if (s.publishedAt) lines.push(`   Published: ${s.publishedAt}`); if (s.retrievedAt) lines.push(`   Retrieved: ${s.retrievedAt}`); }); if (d.notes?.length) { lines.push("", "REPORT NOTES"); d.notes.forEach((n) => lines.push(`- ${n}`)); } lines.push("", "This report is a review artifact. Verified findings are distinguished from unresolved claims."); return lines.flatMap((x) => wrapReportText(x)); }
export function buildReportPdf(d: ReportData): Uint8Array { if (!d.title.trim()) throw new Error("Report title is required"); if (!d.generatedAt.trim()) throw new Error("Report generation date is required"); if (!Number.isInteger(d.version) || d.version < 1) throw new Error("Report version must be positive"); const lines = reportLines(d), perPage = Math.max(1, Math.floor((PAGE_H - TOP - BOTTOM - 34) / LEADING)), pages: string[][] = []; for (let i = 0; i < lines.length; i += perPage) pages.push(lines.slice(i, i + perPage)); if (!pages.length) pages.push(["AETHER AI PLATFORM"]); const pageIds: number[] = [], contentIds: number[] = []; let next = 4; for (const _ of pages) { pageIds.push(next++); contentIds.push(next++); } const objects: string[] = []; objects[1] = "<< /Type /Catalog /Pages 2 0 R >>"; objects[2] = `<< /Type /Pages /Kids [${pageIds.map((x) => `${x} 0 R`).join(" ")}] /Count ${pages.length} >>`; objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>"; pages.forEach((page, i) => { const commands = ["BT", "/F1 10 Tf", `${LEFT} ${PAGE_H - TOP - 14} Td`, ...page.flatMap((line, n) => [n ? `0 -${LEADING} Td` : "", `(${escapePdf(line)}) Tj`]), "ET", "BT", "/F1 8 Tf", `${LEFT} 28 Td`, `(Aether AI Platform - Review Artifact - Page ${i + 1} of ${pages.length}) Tj`, "ET"].filter(Boolean).join("\n"); objects[pageIds[i]] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentIds[i]} 0 R >>`; objects[contentIds[i]] = `<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`; }); let pdf = "%PDF-1.4\n"; const offsets = [0]; for (let id = 1; id < objects.length; id++) { offsets[id] = pdf.length; pdf += `${id} 0 obj\n${objects[id]}\nendobj\n`; } const xref = pdf.length; pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`; for (let id = 1; id < objects.length; id++) pdf += `${String(offsets[id]).padStart(10, "0")} 00000 n \n`; return new TextEncoder().encode(`${pdf}trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`); }
export function buildReportDataFingerprint(d: ReportData): string { const s = JSON.stringify(d); let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0).toString(16).padStart(8, "0"); }
