/** Phase L — server-authoritative durable scheduling. Browser lifecycle never owns execution state. */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { calculateNextRunAt, validateSchedule, type ScheduleKind } from "./scheduler-runtime";

const isAdmin = async (uid: string) => { const { data, error } = await supabaseAdmin.rpc("has_role", { _user_id: uid, _role: "admin" }); if (error) throw new Response(error.message, { status: 500 }); return !!data; };
const normalizedPayload = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const limits = (x: { limit?: number; leaseSeconds?: number } = {}) => ({ limit: Math.min(50, Math.max(1, Math.floor(Number(x.limit ?? 10)))), leaseSeconds: Math.min(900, Math.max(30, Math.floor(Number(x.leaseSeconds ?? 120)))) });

export const createSchedule = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((x: any) => ({ ownerId: String(x?.ownerId || ""), name: String(x?.name || ""), description: x?.description ? String(x.description) : null, kind: x?.kind as ScheduleKind, expression: String(x?.expression || ""), timezone: String(x?.timezone || "UTC"), taskType: String(x?.taskType || ""), payload: normalizedPayload(x?.payload), enabled: x?.enabled !== false })).handler(async ({ context, data }) => {
  if (data.ownerId !== context.userId) throw new Response("Schedule owner must be the authenticated user", { status: 403 });
  const validation = validateSchedule({ ...data, nextRunAt: null }); if (!validation.ok) throw new Error(validation.message);
  const next = data.enabled ? calculateNextRunAt(data, new Date()) : null; if (data.enabled && !next) throw new Error("The schedule has no future occurrence");
  const { data: row, error } = await supabaseAdmin.from("schedules").insert({ owner_id: context.userId, name: data.name.trim().slice(0, 160), description: data.description?.slice(0, 2000) || null, schedule_kind: data.kind, schedule_expression: data.expression.trim(), timezone: data.timezone.trim(), task_type: data.taskType.trim().slice(0, 120), payload: data.payload, enabled: data.enabled, next_run_at: next?.toISOString() || null }).select("*").single();
  if (error) throw new Response(error.message, { status: 500 }); return row;
});

export const listSchedules = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { const { data, error } = await context.supabase.from("schedules").select("*").eq("owner_id", context.userId).order("created_at", { ascending: false }); if (error) throw new Response(error.message, { status: 500 }); return data || []; });

export const listScheduledRuns = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).inputValidator((x: { scheduleId?: string; limit?: number } = {}) => ({ scheduleId: x.scheduleId ? String(x.scheduleId) : null, limit: Math.min(100, Math.max(1, Math.floor(Number(x.limit ?? 50)))) })).handler(async ({ context, data }) => {
  let query = context.supabase.from("scheduled_runs").select("id,schedule_id,status,scheduled_for,started_at,finished_at,attempt_count,max_attempts,result,error,task_id,task_run_id,created_at").eq("owner_id", context.userId).order("scheduled_for", { ascending: false }).limit(data.limit);
  if (data.scheduleId) query = query.eq("schedule_id", data.scheduleId); const { data: rows, error } = await query; if (error) throw new Response(error.message, { status: 500 }); return rows || [];
});

export const updateSchedule = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((x: any) => ({ id: String(x?.id || ""), enabled: typeof x?.enabled === "boolean" ? x.enabled : undefined, name: x?.name === undefined ? undefined : String(x.name), description: x?.description === undefined ? undefined : (x.description ? String(x.description) : null), kind: x?.kind === undefined ? undefined : x.kind as ScheduleKind, expression: x?.expression === undefined ? undefined : String(x.expression), timezone: x?.timezone === undefined ? undefined : String(x.timezone), taskType: x?.taskType === undefined ? undefined : String(x.taskType), payload: x?.payload === undefined ? undefined : normalizedPayload(x.payload) })).handler(async ({ context, data }) => {
  if (!data.id) throw new Error("Schedule id is required"); const { data: current, error: readError } = await supabaseAdmin.from("schedules").select("*").eq("id", data.id).eq("owner_id", context.userId).single(); if (readError || !current) throw new Response(readError?.message || "Schedule not found", { status: readError ? 500 : 404 });
  const merged = { ownerId: context.userId, name: data.name ?? current.name, description: data.description ?? current.description, kind: (data.kind ?? current.schedule_kind) as ScheduleKind, expression: data.expression ?? current.schedule_expression, timezone: data.timezone ?? current.timezone, taskType: data.taskType ?? current.task_type, payload: data.payload ?? current.payload, enabled: data.enabled ?? current.enabled, nextRunAt: null };
  const validation = validateSchedule(merged); if (!validation.ok) throw new Error(validation.message); const next = merged.enabled ? calculateNextRunAt(merged, new Date()) : null; if (merged.enabled && !next) throw new Error(merged.kind === "once" ? "The one-time schedule is in the past" : "The schedule has no future occurrence");
  const patch = { name: merged.name.trim().slice(0, 160), description: merged.description?.slice(0, 2000) || null, schedule_kind: merged.kind, schedule_expression: merged.expression.trim(), timezone: merged.timezone.trim(), task_type: merged.taskType.trim().slice(0, 120), payload: merged.payload, enabled: merged.enabled, next_run_at: next?.toISOString() || null, updated_at: new Date().toISOString() };
  const { data: row, error } = await supabaseAdmin.from("schedules").update(patch).eq("id", data.id).eq("owner_id", context.userId).select("*").single(); if (error || !row) throw new Response(error?.message || "Schedule not found", { status: error ? 500 : 404 }); return row;
});

export const deleteSchedule = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((x: { id: string }) => { if (!x?.id) throw new Error("Schedule id is required"); return { id: x.id }; }).handler(async ({ context, data }) => { const { error } = await supabaseAdmin.from("schedules").delete().eq("id", data.id).eq("owner_id", context.userId); if (error) throw new Response(error.message, { status: 500 }); return { ok: true as const }; });

export const runScheduleNow = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((x: { id: string } = { id: "" }) => { if (!x.id) throw new Error("Schedule id is required"); return x; }).handler(async ({ context, data }) => { const { data: schedule, error: scheduleError } = await supabaseAdmin.from("schedules").select("*").eq("id", data.id).eq("owner_id", context.userId).single(); if (scheduleError || !schedule) throw new Response(scheduleError?.message || "Schedule not found", { status: scheduleError ? 500 : 404 }); const scheduledFor = new Date().toISOString(); const { data: run, error } = await supabaseAdmin.from("scheduled_runs").insert({ schedule_id: schedule.id, owner_id: context.userId, status: "queued", scheduled_for: scheduledFor, max_attempts: 3, payload: schedule.payload, idempotency_key: `manual:${schedule.id}:${scheduledFor}` }).select("*").single(); if (error) throw new Response(error.message, { status: 500 }); return run; });

export const claimScheduledRuns = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator(limits).handler(async ({ context, data }) => { if (!await isAdmin(context.userId)) throw new Response("Administrator authorization required", { status: 403 }); const { data: runs, error } = await supabaseAdmin.rpc("claim_due_schedules", { p_limit: data.limit, p_lease_seconds: data.leaseSeconds }); if (error) throw new Response(error.message, { status: 500 }); return { ok: true as const, runs: runs || [] }; });
export const dispatchScheduledRuns = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator(limits).handler(async ({ context, data }) => { if (!await isAdmin(context.userId)) throw new Response("Administrator authorization required", { status: 403 }); const { data: runs, error } = await supabaseAdmin.rpc("claim_queued_scheduled_runs", { p_limit: data.limit, p_lease_seconds: data.leaseSeconds }); if (error) throw new Response(error.message, { status: 500 }); return { ok: true as const, runs: runs || [] }; });
export const recoverScheduledRuns = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((x: { limit?: number } = {}) => ({ limit: Math.min(100, Math.max(1, Math.floor(Number(x.limit ?? 50)))) })).handler(async ({ context, data }) => { if (!await isAdmin(context.userId)) throw new Response("Administrator authorization required", { status: 403 }); const { data: recovered, error } = await supabaseAdmin.rpc("recover_expired_scheduled_runs", { p_limit: data.limit }); if (error) throw new Response(error.message, { status: 500 }); return { ok: true as const, recovered: Number(recovered || 0) }; });
export const runSchedulerTick = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator(limits).handler(async ({ context, data }) => { if (!await isAdmin(context.userId)) throw new Response("Administrator authorization required", { status: 403 }); const { data: recovered, error: recoveryError } = await supabaseAdmin.rpc("recover_expired_scheduled_runs", { p_limit: data.limit * 2 }); if (recoveryError) throw new Response(recoveryError.message, { status: 500 }); const { data: fired, error: fireError } = await supabaseAdmin.rpc("claim_due_schedules", { p_limit: data.limit, p_lease_seconds: data.leaseSeconds }); if (fireError) throw new Response(fireError.message, { status: 500 }); const { data: dispatched, error: dispatchError } = await supabaseAdmin.rpc("claim_queued_scheduled_runs", { p_limit: data.limit, p_lease_seconds: data.leaseSeconds }); if (dispatchError) throw new Response(dispatchError.message, { status: 500 }); return { ok: true as const, recovered: Number(recovered || 0), fired: fired || [], dispatched: dispatched || [] }; });
