/** Phase L — server-authoritative durable scheduling. Browser lifecycle never owns execution state. */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { validateSchedule } from "./scheduler-runtime";

const admin = async (uid:string) => { const {data,error}=await supabaseAdmin.rpc("has_role",{_user_id:uid,_role:"admin"}); if(error) throw new Response(error.message,{status:500}); return !!data; };

export const createSchedule=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>{const data={ownerId:String(x?.ownerId||""),name:String(x?.name||""),description:x?.description?String(x.description):null,kind:x?.kind,expression:String(x?.expression||""),timezone:String(x?.timezone||"UTC"),taskType:String(x?.taskType||""),payload:x?.payload&&typeof x.payload==="object"?x.payload:{},enabled:x?.enabled!==false,nextRunAt:x?.nextRunAt?String(x.nextRunAt):null};const v=validateSchedule(data);if(!v.ok)throw new Error(v.message);return data;}).handler(async({context,data})=>{if(data.ownerId!==context.userId)throw new Response("Schedule owner must be the authenticated user",{status:403});const {data:row,error}=await supabaseAdmin.from("schedules").insert({owner_id:data.ownerId,name:data.name.trim().slice(0,160),description:data.description?.slice(0,2000)||null,schedule_kind:data.kind,schedule_expression:data.expression.trim(),timezone:data.timezone,task_type:data.taskType.trim().slice(0,120),payload:data.payload,enabled:data.enabled,next_run_at:data.nextRunAt}).select("*").single();if(error)throw new Response(error.message,{status:500});return row;});

export const listSchedules=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data,error}=await context.supabase.from("schedules").select("*").eq("owner_id",context.userId).order("created_at",{ascending:false});if(error)throw new Response(error.message,{status:500});return data||[];});

export const updateSchedule=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({id:String(x?.id||""),enabled:typeof x?.enabled==="boolean"?x.enabled:undefined,name:x?.name===undefined?undefined:String(x.name),expression:x?.expression===undefined?undefined:String(x.expression),nextRunAt:x?.nextRunAt===undefined?undefined:(x.nextRunAt?String(x.nextRunAt):null)})).handler(async({context,data})=>{if(!data.id)throw new Error("Schedule id is required");const patch:any={};if(data.enabled!==undefined)patch.enabled=data.enabled;if(data.name!==undefined)patch.name=data.name.trim().slice(0,160);if(data.expression!==undefined)patch.schedule_expression=data.expression.trim();if(data.nextRunAt!==undefined)patch.next_run_at=data.nextRunAt;patch.updated_at=new Date().toISOString();const {data:row,error}=await supabaseAdmin.from("schedules").update(patch).eq("id",data.id).eq("owner_id",context.userId).select("*").single();if(error||!row)throw new Response(error?.message||"Schedule not found",{status:error?500:404});return row;});

export const deleteSchedule=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{id:string})=>{if(!x?.id)throw new Error("Schedule id is required");return {id:x.id};}).handler(async({context,data})=>{const {error}=await supabaseAdmin.from("schedules").delete().eq("id",data.id).eq("owner_id",context.userId);if(error)throw new Response(error.message,{status:500});return {ok:true as const};});

export const claimScheduledRuns=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:{limit?:number;leaseSeconds?:number}={})=>({limit:Math.min(50,Math.max(1,Math.floor(Number(x?.limit??10)))),leaseSeconds:Math.min(900,Math.max(30,Math.floor(Number(x?.leaseSeconds??120))))})).handler(async({context,data})=>{if(!await admin(context.userId))throw new Response("Administrator authorization required",{status:403});const {data:runs,error}=await supabaseAdmin.rpc("claim_due_schedules",{p_limit:data.limit,p_lease_seconds:data.leaseSeconds});if(error)throw new Response(error.message,{status:500});return {ok:true as const,runs:runs||[]};});

export const completeScheduledRun=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>({id:String(x?.id||""),leaseToken:String(x?.leaseToken||""),success:!!x?.success,result:x?.result&&typeof x.result==="object"?x.result:null,error:x?.error?String(x.error).slice(0,4000):null})).handler(async({context,data})=>{if(!await admin(context.userId))throw new Response("Administrator authorization required",{status:403});if(!data.id||!data.leaseToken)throw new Error("Run id and lease token are required");const now=new Date().toISOString();const {data:row,error}=await supabaseAdmin.from("scheduled_runs").update({status:data.success?"succeeded":"failed",finished_at:now,result:data.result,error:data.error,updated_at:now}).eq("id",data.id).eq("lease_token",data.leaseToken).eq("status","running").select("*").single();if(error||!row)throw new Response(error?.message||"Run lease is invalid or expired",{status:error?500:409});return row;});
