// @ts-nocheck
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { authorizeSecurityAction, createSecurityIncident } from "./security-runtime";
const db=supabaseAdmin as any;
async function assertAdmin(userId:string){const {data,error}=await db.rpc("has_role",{_user_id:userId,_role:"admin"});if(error||!data)throw new Response("Administrator authorization required",{status:403});}
export const evaluateSecurityAction=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>authorizeSecurityAction({...data,actorId:context.userId}));
export const getSecurityControlPlane=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context}:any)=>{await assertAdmin(context.userId);const [{data:policies,error:pErr},{data:incidents,error:iErr},{data:events,error:eErr},{data:requests,error:rErr}]=await Promise.all([db.from("security_policies").select("*").order("priority",{ascending:false}),db.from("security_incidents").select("*").order("updated_at",{ascending:false}).limit(200),db.from("security_events").select("*").order("created_at",{ascending:false}).limit(200),db.from("security_requests").select("*").order("created_at",{ascending:false}).limit(200)]);if(pErr||iErr||eErr||rErr)throw new Response("Could not load security control plane",{status:500});return{policies:policies??[],incidents:incidents??[],events:events??[],requests:requests??[]};});
export const createSecurityPolicy=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>{await assertAdmin(context.userId);const policy={policy_key:String(data.policyKey||"").trim(),version:Number(data.version||1),status:String(data.status||"draft"),priority:Number(data.priority||100),action_pattern:String(data.actionPattern||".*"),resource_type_pattern:String(data.resourceTypePattern||".*"),effect:String(data.effect||"allow"),severity:String(data.severity||"low"),conditions:data.conditions&&typeof data.conditions==="object"?data.conditions:{},description:String(data.description||""),created_by:context.userId,updated_by:context.userId};if(!policy.policy_key||!policy.action_pattern)throw new Response("Policy key and action pattern are required",{status:400});try{new RegExp(policy.action_pattern);}catch{throw new Response("Invalid action regex",{status:400});}const {data:row,error}=await db.from("security_policies").insert(policy).select("*").single();if(error)throw new Response(error.message,{status:409});return row;});
export const updateSecurityPolicy=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>{await assertAdmin(context.userId);const patch={version:Number(data.version||1),status:String(data.status||"draft"),priority:Number(data.priority||100),action_pattern:String(data.actionPattern||".*"),resource_type_pattern:String(data.resourceTypePattern||".*"),effect:String(data.effect||"allow"),severity:String(data.severity||"low"),conditions:data.conditions&&typeof data.conditions==="object"?data.conditions:{},description:String(data.description||""),updated_by:context.userId,updated_at:new Date().toISOString()};try{new RegExp(patch.action_pattern);}catch{throw new Response("Invalid action regex",{status:400});}const {data:row,error}=await db.from("security_policies").update(patch).eq("id",String(data.id||"")).select("*").single();if(error||!row)throw new Response(error?.message??"Security policy not found",{status:404});return row;});
export const createSecurityIncidentFn=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>{await assertAdmin(context.userId);return createSecurityIncident({...data,actorId:data.actorId??context.userId});});
export const updateSecurityIncident=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:any)=>x).handler(async({context,data}:any)=>{await assertAdmin(context.userId);const status=String(data.status||"");if(!["open","investigating","contained","resolved","false_positive"].includes(status))throw new Response("Invalid incident status",{status:400});const patch:any={status,updated_at:new Date().toISOString()};if(status==="contained")patch.contained_at=new Date().toISOString();if(status==="resolved"||status==="false_positive"){patch.resolved_at=new Date().toISOString();patch.resolution=String(data.resolution||"");}const {data:row,error}=await db.from("security_incidents").update(patch).eq("id",String(data.id||"")).select("*").single();if(error||!row)throw new Response(error?.message??"Security incident not found",{status:404});return row;});
