/** Phase O: provider-independent durable security control-plane primitives. */
import { supabaseAdmin } from "@/integrations/supabase/client.server";

export type SecurityDecision = "allow" | "deny" | "approval_required";
export interface SecurityAuthorizationInput { actorId?: string|null; agentKey?: string|null; action: string; resourceType?: string|null; resourceId?: string|null; taskId?: string|null; runId?: string|null; context?: Record<string, unknown>; idempotencyKey?: string; }
export interface SecurityAuthorizationResult { allowed: boolean; requiresApproval: boolean; decision: SecurityDecision; reason: string; requestId?: string; policyIds?: string[]; }
const db = supabaseAdmin as any;

function stableHash(input:string):string { let h=2166136261; for(let i=0;i<input.length;i+=1){h^=input.charCodeAt(i);h=Math.imul(h,16777619);} return (h>>>0).toString(16).padStart(8,"0"); }
export function securityIdempotencyKey(input:Omit<SecurityAuthorizationInput,"idempotencyKey">):string { return `phase-o:${stableHash(JSON.stringify({actorId:input.actorId??null,agentKey:input.agentKey??null,action:input.action,resourceType:input.resourceType??null,resourceId:input.resourceId??null,taskId:input.taskId??null,runId:input.runId??null,context:input.context??{}}))}`; }
export function normalizeSecurityAuthorization(input:SecurityAuthorizationInput):Required<Pick<SecurityAuthorizationInput,"action">>&SecurityAuthorizationInput { const action=input.action.trim(); if(!action) throw new Error("Security action is required"); return {...input,action}; }
export async function authorizeSecurityAction(input:SecurityAuthorizationInput):Promise<SecurityAuthorizationResult>{ const normalized=normalizeSecurityAuthorization(input); const key=normalized.idempotencyKey??securityIdempotencyKey(normalized); const {data,error}=await db.rpc("security_authorize_action",{p_idempotency_key:key,p_actor_id:normalized.actorId??null,p_agent_key:normalized.agentKey??null,p_action:normalized.action,p_resource_type:normalized.resourceType??null,p_resource_id:normalized.resourceId??null,p_task_id:normalized.taskId??null,p_run_id:normalized.runId??null,p_context:normalized.context??{}}); if(error) throw new Error(`Security authorization failed: ${error.message}`); const result=Array.isArray(data)?data[0]:data; if(!result) throw new Error("Security authorization returned no decision"); return {allowed:Boolean(result.allowed),requiresApproval:Boolean(result.requires_approval),decision:(result.decision??"deny") as SecurityDecision,reason:String(result.reason??"Security policy denied the action"),requestId:result.request_id??undefined,policyIds:Array.isArray(result.policy_ids)?result.policy_ids:[]}; }
export async function createSecurityIncident(input:{incidentKey:string;incidentType:string;severity:"low"|"medium"|"high"|"critical";title:string;description?:string;sourceEventId?:string|null;actorId?:string|null;agentKey?:string|null;metadata?:Record<string,unknown>}):Promise<unknown>{ const {data,error}=await db.rpc("create_security_incident",{p_incident_key:input.incidentKey,p_incident_type:input.incidentType,p_severity:input.severity,p_title:input.title,p_description:input.description??"",p_source_event_id:input.sourceEventId??null,p_actor_id:input.actorId??null,p_agent_key:input.agentKey??null,p_metadata:input.metadata??{}}); if(error) throw new Error(`Security incident creation failed: ${error.message}`); return Array.isArray(data)?data[0]:data; }
export function incidentKey(eventType:string,resourceId?:string|null):string { return `phase-o:${stableHash(`${eventType}:${resourceId??"none"}`)}`; }
