import { describe, expect, it } from "vitest";
import { buildReportDataFingerprint, buildReportPdf, slugifyReportFilename, wrapReportText, type ReportData } from "../report-engine";
const base:ReportData={title:"Aether Research Report — Café & AI",topic:"Verification",sessionId:"session-123",runId:"run-456",generatedAt:"2026-09-11T13:00:00.000Z",verificationStatus:"verified",approvalStatus:"pending",version:1,sources:[{title:"Example Source",url:"https://example.com/source",publishedAt:"2026-09-10",retrievedAt:"2026-09-11"}],verifiedFindings:[{claim:"Aether separates verified findings from unresolved claims.",evidence:"Persisted evidence marks this claim verified.",confidence:.97}],unresolvedClaims:[{claim:"An unresolved claim remains visible in the review artifact.",verificationStatus:"needs_review"}]};
describe("Phase J report engine",()=>{
 it("wraps long text deterministically",()=>{const v="word ".repeat(50);expect(wrapReportText(v)).toEqual(wrapReportText(v));expect(wrapReportText(v).every(x=>x.length<=92)).toBe(true);});
 it("creates safe deterministic filenames",()=>expect(slugifyReportFilename(base.title,"12345678-aaaa",2)).toBe("aether-research-report-cafe-ai-12345678-v2.pdf"));
 it("renders a PDF with required sections",()=>{const pdf=new TextDecoder().decode(buildReportPdf(base));expect(pdf.startsWith("%PDF-1.4")).toBe(true);expect(pdf).toContain("AETHER AI PLATFORM");expect(pdf).toContain("VERIFIED FINDINGS");expect(pdf).toContain("UNRESOLVED CLAIMS");expect(pdf).toContain("SOURCES");expect(pdf).toContain("Page 1 of");expect(pdf.endsWith("%%EOF\n")).toBe(true);});
 it("handles special characters without failing",()=>expect(buildReportPdf({...base,title:"Résumé — “Special” Café • Aether",verifiedFindings:[{claim:"Unicode punctuation — € ✓ uses a deterministic safe representation."}]}).byteLength).toBeGreaterThan(500));
 it("keeps structured fingerprints stable",()=>expect(buildReportDataFingerprint(base)).toBe(buildReportDataFingerprint({...base}))); 
 it("creates multiple pages for large reports",()=>{const d={...base,verifiedFindings:Array.from({length:140},(_,i)=>({claim:`Finding ${i+1}: Aether preserves structured report evidence and provenance for review.`,evidence:"Persisted evidence passage for the finding."}))};const pdf=new TextDecoder().decode(buildReportPdf(d));expect((pdf.match(/Page \d+ of \d+/g)??[]).length).toBeGreaterThan(1);});
});
