/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsOverviewRouteImport } from './routes/agents-overview'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelsOverviewRouteImport } from './routes/models-overview'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOverviewRoute = AgentsOverviewRouteImport.update({
  id: '/agents-overview',
  path: '/agents-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsOverviewRoute = ModelsOverviewRouteImport.update({
  id: '/models-overview',
  path: '/models-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/models-overview': typeof ModelsOverviewRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/models-overview': typeof ModelsOverviewRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/models-overview': typeof ModelsOverviewRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents-overview'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/features'
    | '/login'
    | '/models-overview'
    | '/privacy'
    | '/signup'
    | '/status'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents-overview'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/features'
    | '/login'
    | '/models-overview'
    | '/privacy'
    | '/signup'
    | '/status'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/agents-overview'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/features'
    | '/login'
    | '/models-overview'
    | '/privacy'
    | '/signup'
    | '/status'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsOverviewRoute: typeof AgentsOverviewRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  ModelsOverviewRoute: typeof ModelsOverviewRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-overview': {
      id: '/agents-overview'
      path: '/agents-overview'
      fullPath: '/agents-overview'
      preLoaderRoute: typeof AgentsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models-overview': {
      id: '/models-overview'
      path: '/models-overview'
      fullPath: '/models-overview'
      preLoaderRoute: typeof ModelsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsOverviewRoute: AgentsOverviewRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  ModelsOverviewRoute: ModelsOverviewRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
