/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsOverviewRouteImport } from './routes/agents-overview'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ModelsOverviewRouteImport } from './routes/models-overview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOverviewRoute = AgentsOverviewRouteImport.update({
  id: '/agents-overview',
  path: '/agents-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsOverviewRoute = ModelsOverviewRouteImport.update({
  id: '/models-overview',
  path: '/models-overview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/features': typeof FeaturesRoute
  '/models-overview': typeof ModelsOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/features': typeof FeaturesRoute
  '/models-overview': typeof ModelsOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/features': typeof FeaturesRoute
  '/models-overview': typeof ModelsOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents-overview' | '/features' | '/models-overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents-overview' | '/features' | '/models-overview'
  id: '__root__' | '/' | '/agents-overview' | '/features' | '/models-overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsOverviewRoute: typeof AgentsOverviewRoute
  FeaturesRoute: typeof FeaturesRoute
  ModelsOverviewRoute: typeof ModelsOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-overview': {
      id: '/agents-overview'
      path: '/agents-overview'
      fullPath: '/agents-overview'
      preLoaderRoute: typeof AgentsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models-overview': {
      id: '/models-overview'
      path: '/models-overview'
      fullPath: '/models-overview'
      preLoaderRoute: typeof ModelsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsOverviewRoute: AgentsOverviewRoute,
  FeaturesRoute: FeaturesRoute,
  ModelsOverviewRoute: ModelsOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
