-- AETHER PHASE N: durable orchestration plans, dependency steps, gates and recovery.
create table if not exists public.orchestration_plans (
 id uuid primary key default gen_random_uuid(), task_id uuid not null references public.tasks(id) on delete cascade,
 owner_id uuid not null references auth.users(id) on delete cascade, objective text not null, context jsonb not null default '{}'::jsonb,
 status text not null default 'draft' check(status in ('draft','ready','running','waiting_approval','completed','failed','cancelled','paused')),
 idempotency_key text not null unique, aggregated_result jsonb not null default '{}'::jsonb, warnings jsonb not null default '[]'::jsonb, errors jsonb not null default '[]'::jsonb,
 created_at timestamptz not null default now(), started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now()
);
create table if not exists public.orchestration_steps (
 id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.orchestration_plans(id) on delete cascade,
 step_id text not null, agent_key text not null references public.agents(agent_key), title text not null, input jsonb not null default '{}'::jsonb,
 depends_on jsonb not null default '[]'::jsonb, requires_approval boolean not null default false, requires_verification boolean not null default false,
 max_retries integer not null default 2 check(max_retries between 0 and 20), retry_count integer not null default 0,
 timeout_ms bigint not null default 300000 check(timeout_ms between 1 and 18000000), critical boolean not null default false,
 status text not null default 'pending' check(status in ('pending','ready','running','waiting_approval','completed','failed','skipped','cancelled')),
 worker_id text, lease_expires_at timestamptz, result jsonb not null default '{}', warnings jsonb not null default '[]', errors jsonb not null default '[]',
 run_id uuid references public.task_runs(id) on delete set null, started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now(),
 unique(plan_id,step_id)
);
create table if not exists public.orchestration_gates (
 id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.orchestration_plans(id) on delete cascade,
 step_id uuid not null references public.orchestration_steps(id) on delete cascade, gate_type text not null check(gate_type in ('approval','verification','policy')),
 status text not null default 'pending' check(status in ('pending','approved','rejected','expired')), reason text, requested_by uuid references auth.users(id) on delete set null,
 decided_by uuid references auth.users(id) on delete set null, decision_note text, created_at timestamptz not null default now(), decided_at timestamptz
);
create index if not exists orchestration_plans_owner_idx on public.orchestration_plans(owner_id,updated_at desc);
create index if not exists orchestration_steps_plan_status_idx on public.orchestration_steps(plan_id,status);
create index if not exists orchestration_steps_lease_idx on public.orchestration_steps(lease_expires_at) where status='running';
create index if not exists orchestration_gates_plan_idx on public.orchestration_gates(plan_id,status);
alter table public.orchestration_plans enable row level security;alter table public.orchestration_steps enable row level security;alter table public.orchestration_gates enable row level security;
revoke all on public.orchestration_plans,public.orchestration_steps,public.orchestration_gates from anon,authenticated;grant select on public.orchestration_plans,public.orchestration_steps,public.orchestration_gates to authenticated;
create or replace function public.create_orchestration_plan(p_task_id uuid,p_owner_id uuid,p_objective text,p_context jsonb,p_idempotency_key text,p_steps jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare t public.tasks;p public.orchestration_plans;s jsonb;sid text;akey text;deps jsonb;v_step public.orchestration_steps;begin
if auth.uid() is distinct from p_owner_id then raise exception 'Forbidden: owner mismatch';end if;
select * into t from public.tasks where id=p_task_id for update;if not found or t.owner_id<>p_owner_id then raise exception 'Task not found or not owned';end if;
select to_jsonb(op) into s from public.orchestration_plans op where op.idempotency_key=p_idempotency_key limit 1;if s is not null then return s;end if;
insert into public.orchestration_plans(task_id,owner_id,objective,context,status,idempotency_key) values(p_task_id,p_owner_id,trim(p_objective),coalesce(p_context,'{}'::jsonb),'ready',p_idempotency_key) returning * into p;
for s in select * from jsonb_array_elements(p_steps) loop sid=trim(coalesce(s->>'stepId',''));akey=trim(coalesce(s->>'agentKey',''));deps=coalesce(s->'dependsOn','[]'::jsonb);if sid='' or akey='' then raise exception 'Invalid orchestration step';end if;if akey='orchestrator' then raise exception 'Orchestrator cannot delegate to itself';end if;if not exists(select 1 from public.agents where agent_key=akey and status='enabled') then raise exception 'Agent is unavailable: %',akey;end if;insert into public.orchestration_steps(plan_id,step_id,agent_key,title,input,depends_on,requires_approval,requires_verification,max_retries,timeout_ms,critical) values(p.id,sid,akey,coalesce(nullif(trim(s->>'title'),''),sid),coalesce(s->'input','{}'::jsonb),deps,coalesce((s->>'requiresApproval')::boolean,false),coalesce((s->>'requiresVerification')::boolean,false),coalesce((s->>'maxRetries')::integer,2),coalesce((s->>'timeoutMs')::bigint,300000),coalesce((s->>'critical')::boolean,false));end loop;
update public.orchestration_plans set status='ready',updated_at=now() where id=p.id;return to_jsonb(p)||jsonb_build_object('id',p.id);end;$$;
revoke all on function public.create_orchestration_plan(uuid,uuid,text,jsonb,text,jsonb) from public,anon,authenticated;grant execute on function public.create_orchestration_plan(uuid,uuid,text,jsonb,text,jsonb) to authenticated,service_role;
create or replace function public.orchestration_step_ready(p_step_id uuid) returns boolean language sql security definer set search_path=public as $$select exists(select 1 from public.orchestration_steps s where s.id=p_step_id and s.status='pending' and not exists(select 1 from jsonb_array_elements_text(s.depends_on) d where not exists(select 1 from public.orchestration_steps x where x.plan_id=s.plan_id and x.step_id=d and x.status='completed')));$$;
revoke all on function public.orchestration_step_ready(uuid) from public,anon,authenticated;grant execute on function public.orchestration_step_ready(uuid) to authenticated,service_role;
create or replace function public.claim_orchestration_step(p_step_id uuid,p_actor_id uuid) returns public.orchestration_steps language plpgsql security definer set search_path=public as $$declare s public.orchestration_steps;p public.orchestration_plans;begin if auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;select * into s from public.orchestration_steps where id=p_step_id for update;if not found then raise exception 'Step not found';end if;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;if not public.orchestration_step_ready(s.id) then raise exception 'Step dependencies are not complete';end if;update public.orchestration_steps set status='running',worker_id=p_actor_id::text,lease_expires_at=now()+interval '10 minutes',started_at=coalesce(started_at,now()),updated_at=now() where id=s.id returning * into s;update public.orchestration_plans set status='running',started_at=coalesce(started_at,now()),updated_at=now() where id=s.plan_id and status in ('ready','draft');return s;end;$$;
revoke all on function public.claim_orchestration_step(uuid,uuid) from public,anon,authenticated;grant execute on function public.claim_orchestration_step(uuid,uuid) to authenticated,service_role;
create or replace function public.complete_orchestration_step(p_step_id uuid,p_status text,p_result jsonb,p_warnings jsonb,p_errors jsonb,p_actor_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare s public.orchestration_steps;p public.orchestration_plans;total integer;done integer;failed integer;agg jsonb;begin if auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;if p_status not in ('completed','failed','waiting_approval','skipped','cancelled') then raise exception 'Invalid terminal step state';end if;select * into s from public.orchestration_steps where id=p_step_id for update;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;update public.orchestration_steps set status=p_status,result=coalesce(p_result,'{}'),warnings=coalesce(p_warnings,'[]'),errors=coalesce(p_errors,'[]'),completed_at=case when p_status in ('completed','failed','skipped','cancelled') then now() else null end,lease_expires_at=null,updated_at=now() where id=s.id returning * into s;select count(*),count(*) filter(where status='completed'),count(*) filter(where status='failed') into total,done,failed from public.orchestration_steps where plan_id=s.plan_id;if failed>0 and exists(select 1 from public.orchestration_steps where plan_id=s.plan_id and critical and status='failed') then update public.orchestration_plans set status='failed',completed_at=now(),errors=coalesce(p_errors,'[]'),updated_at=now() where id=s.plan_id;elsif done=total then select jsonb_agg(jsonb_build_object('stepId',step_id,'agentKey',agent_key,'status',status,'result',result)) into agg from public.orchestration_steps where plan_id=s.plan_id;update public.orchestration_plans set status='completed',aggregated_result=coalesce(agg,'[]'),warnings=(select coalesce(jsonb_agg(w),'[]') from public.orchestration_steps st,cross join lateral jsonb_array_elements(st.warnings) w where st.plan_id=s.plan_id),completed_at=now(),updated_at=now() where id=s.plan_id;else update public.orchestration_plans set status=case when exists(select 1 from public.orchestration_steps where plan_id=s.plan_id and status='waiting_approval') then 'waiting_approval' else 'running' end,updated_at=now() where id=s.plan_id;end if;return jsonb_build_object('step',to_jsonb(s),'plan',to_jsonb((select op from public.orchestration_plans op where id=s.plan_id)));end;end;$$;
revoke all on function public.complete_orchestration_step(uuid,text,jsonb,jsonb,jsonb,uuid) from public,anon,authenticated;grant execute on function public.complete_orchestration_step(uuid,text,jsonb,jsonb,jsonb,uuid) to authenticated,service_role;
create or replace function public.request_orchestration_gate(p_step_id uuid,p_gate_type text,p_reason text,p_actor_id uuid) returns public.orchestration_gates language plpgsql security definer set search_path=public as $$declare s public.orchestration_steps;p public.orchestration_plans;g public.orchestration_gates;begin if auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;select * into s from public.orchestration_steps where id=p_step_id;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;if p_gate_type not in ('approval','verification','policy') then raise exception 'Invalid gate type';end if;insert into public.orchestration_gates(plan_id,step_id,gate_type,reason,requested_by) values(p.id,s.id,p_gate_type,p_reason,p_actor_id) returning * into g;update public.orchestration_steps set status='waiting_approval',updated_at=now() where id=s.id;update public.orchestration_plans set status='waiting_approval',updated_at=now() where id=p.id;return g;end;$$;
revoke all on function public.request_orchestration_gate(uuid,text,text,uuid) from public,anon,authenticated;grant execute on function public.request_orchestration_gate(uuid,text,text,uuid) to authenticated,service_role;
create or replace function public.recover_orchestration_plans() returns integer language plpgsql security definer set search_path=public as $$declare n integer;begin update public.orchestration_steps set status='pending',worker_id=null,lease_expires_at=null,retry_count=retry_count+1,updated_at=now() where status='running' and lease_expires_at<now() and retry_count<max_retries;get diagnostics n=row_count;update public.orchestration_steps set status='failed',errors=jsonb_build_array('orchestration step lease expired and retry budget exhausted'),updated_at=now() where status='running' and lease_expires_at<now() and retry_count>=max_retries;update public.orchestration_plans p set status='failed',completed_at=now(),updated_at=now() where p.status='running' and exists(select 1 from public.orchestration_steps s where s.plan_id=p.id and s.status='failed' and s.critical);return n;end;$$;
revoke all on function public.recover_orchestration_plans() from public,anon,authenticated;grant execute on function public.recover_orchestration_plans() to service_role;
