-- AETHER PHASE Q: durable, provider-independent extensible module registry/runtime.
create table if not exists public.modules (id uuid primary key default gen_random_uuid(),slug text not null unique check(slug ~ '^[a-z0-9][a-z0-9._-]{1,62}$'),name text not null check(char_length(name) between 1 and 120),description text not null default '',module_kind text not null default 'application' check(module_kind in ('application','game','integration','tool','workflow')),status text not null default 'draft' check(status in ('draft','validated','tested','active','disabled','maintenance','rolled_back')),owner_id uuid not null references auth.users(id) on delete cascade,created_by uuid references auth.users(id) on delete set null,active_version_id uuid,manifest jsonb not null default '{}'::jsonb,config jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),last_activity_at timestamptz);
create table if not exists public.module_versions (id uuid primary key default gen_random_uuid(),module_id uuid not null references public.modules(id) on delete cascade,version text not null check(char_length(version) between 1 and 64),lifecycle_state text not null default 'draft' check(lifecycle_state in ('draft','validated','tested','active','disabled','maintenance','rolled_back')),manifest jsonb not null default '{}'::jsonb,config jsonb not null default '{}'::jsonb,config_hash text not null,parent_version_id uuid references public.module_versions(id) on delete set null,created_by uuid references auth.users(id) on delete set null,validated_by uuid references auth.users(id) on delete set null,tested_by uuid references auth.users(id) on delete set null,activated_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),validated_at timestamptz,tested_at timestamptz,activated_at timestamptz,retired_at timestamptz,reason text,unique(module_id,version));
alter table public.modules add constraint modules_active_version_fk foreign key(active_version_id) references public.module_versions(id) on delete set null;
create unique index if not exists module_versions_one_active on public.module_versions(module_id) where lifecycle_state='active';
create table if not exists public.module_dependencies (id uuid primary key default gen_random_uuid(),module_version_id uuid not null references public.module_versions(id) on delete cascade,dependency_module_id uuid not null references public.modules(id) on delete restrict,version_range text not null,optional boolean not null default false,unique(module_version_id,dependency_module_id));
create table if not exists public.module_permissions (id uuid primary key default gen_random_uuid(),module_version_id uuid not null references public.module_versions(id) on delete cascade,permission text not null,allowed boolean not null default false,requires_approval boolean not null default false,unique(module_version_id,permission));
create table if not exists public.module_runs (id uuid primary key default gen_random_uuid(),module_id uuid not null references public.modules(id) on delete cascade,module_version_id uuid not null references public.module_versions(id) on delete restrict,owner_id uuid not null references auth.users(id) on delete cascade,task_id uuid references public.tasks(id) on delete set null,run_id uuid references public.task_runs(id) on delete set null,status text not null default 'queued' check(status in ('queued','running','succeeded','failed','cancelled')),inputs jsonb not null default '{}'::jsonb,outputs jsonb not null default '{}'::jsonb,error_message text,attempt integer not null default 0,max_attempts integer not null default 3,worker_id text,lease_expires_at timestamptz,heartbeat_at timestamptz,started_at timestamptz,completed_at timestamptz,next_attempt_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),idempotency_key text unique);
create index if not exists module_runs_due_idx on public.module_runs(status,next_attempt_at,created_at);
create index if not exists module_runs_owner_idx on public.module_runs(owner_id,created_at desc);
create table if not exists public.module_artifacts (id uuid primary key default gen_random_uuid(),module_id uuid not null references public.modules(id) on delete cascade,module_version_id uuid references public.module_versions(id) on delete set null,run_id uuid references public.module_runs(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,artifact_type text not null,path text not null,checksum text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(run_id,path));
create table if not exists public.module_events (id uuid primary key default gen_random_uuid(),module_id uuid not null references public.modules(id) on delete cascade,module_version_id uuid references public.module_versions(id) on delete set null,run_id uuid references public.module_runs(id) on delete set null,event_type text not null,payload jsonb not null default '{}'::jsonb,actor_id uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.module_config_history (id uuid primary key default gen_random_uuid(),module_id uuid not null references public.modules(id) on delete cascade,version_id uuid references public.module_versions(id) on delete set null,action text not null,before_config jsonb,after_config jsonb,actor_id uuid references auth.users(id) on delete set null,reason text,created_at timestamptz not null default now());
create index if not exists module_events_module_idx on public.module_events(module_id,created_at desc);

alter table public.modules enable row level security; alter table public.module_versions enable row level security; alter table public.module_dependencies enable row level security; alter table public.module_permissions enable row level security; alter table public.module_runs enable row level security; alter table public.module_artifacts enable row level security; alter table public.module_events enable row level security; alter table public.module_config_history enable row level security;
revoke all on public.modules,public.module_versions,public.module_dependencies,public.module_permissions,public.module_runs,public.module_artifacts,public.module_events,public.module_config_history from anon,authenticated;
grant select on public.modules,public.module_versions,public.module_dependencies,public.module_permissions,public.module_runs,public.module_artifacts,public.module_events,public.module_config_history to authenticated;

create or replace function public.claim_module_runs(p_worker_id text,p_limit integer default 10) returns setof public.module_runs language plpgsql security definer set search_path=public as $$ begin return query with picked as (select id from public.module_runs where status='queued' and (next_attempt_at is null or next_attempt_at<=now()) order by created_at for update skip locked limit greatest(1,least(p_limit,50))) update public.module_runs r set status='running',worker_id=p_worker_id,attempt=r.attempt+1,started_at=coalesce(r.started_at,now()),heartbeat_at=now(),lease_expires_at=now()+interval '10 minutes',updated_at=now() from picked where r.id=picked.id returning r.*; end; $$;
create or replace function public.recover_expired_module_runs(p_limit integer default 100) returns integer language plpgsql security definer set search_path=public as $$ declare n integer; begin with expired as (select id from public.module_runs where status='running' and lease_expires_at<now() for update skip locked limit greatest(1,least(p_limit,500))) update public.module_runs r set status=case when r.attempt<r.max_attempts then 'queued' else 'failed' end,next_attempt_at=case when r.attempt<r.max_attempts then now()+least(interval '5 minutes',interval '5 seconds'*power(2,greatest(r.attempt-1,0))) else null end,worker_id=null,lease_expires_at=null,heartbeat_at=null,error_message=case when r.attempt<r.max_attempts then 'Worker lease expired; queued for recovery' else 'Worker lease expired; retry budget exhausted' end,updated_at=now() from expired where r.id=expired.id; get diagnostics n=row_count; return n; end; $$;
create or replace function public.complete_module_run(p_run_id uuid,p_status text,p_outputs jsonb default '{}'::jsonb,p_error text default null) returns public.module_runs language plpgsql security definer set search_path=public as $$ declare r public.module_runs; begin if p_status not in ('succeeded','failed','cancelled') then raise exception 'Invalid terminal module run status'; end if; update public.module_runs set status=p_status,outputs=coalesce(p_outputs,'{}'::jsonb),error_message=p_error,completed_at=now(),worker_id=null,lease_expires_at=null,heartbeat_at=null,updated_at=now() where id=p_run_id and status='running' returning * into r; if not found then raise exception 'Module run is not running or not found'; end if; return r; end; $$;
revoke all on function public.claim_module_runs(text,integer),public.recover_expired_module_runs(integer),public.complete_module_run(uuid,text,jsonb,text) from public,anon,authenticated; grant execute on function public.claim_module_runs(text,integer),public.recover_expired_module_runs(integer),public.complete_module_run(uuid,text,jsonb,text) to service_role;
