-- AETHER PHASE M: durable Agent SDK registry, lifecycle, permissions, handoffs and sandbox audit.
-- Production schema was applied through Supabase migration tooling; this file is the source-of-truth migration.
create table if not exists public.agent_versions (id uuid primary key default gen_random_uuid(),agent_id uuid not null references public.agents(id) on delete cascade,version text not null check(char_length(version) between 1 and 64),lifecycle_state text not null default 'draft' check(lifecycle_state in ('draft','validated','tested','active','disabled','maintenance','rolled_back')),definition jsonb not null default '{}'::jsonb,config_hash text not null,parent_version_id uuid references public.agent_versions(id) on delete set null,created_by uuid references auth.users(id) on delete set null,validated_by uuid references auth.users(id) on delete set null,tested_by uuid references auth.users(id) on delete set null,activated_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),validated_at timestamptz,tested_at timestamptz,activated_at timestamptz,retired_at timestamptz,rollback_reason text,unique(agent_id,version));
create unique index if not exists agent_versions_one_active on public.agent_versions(agent_id) where lifecycle_state='active';
create table if not exists public.agent_config_history (id uuid primary key default gen_random_uuid(),agent_id uuid not null references public.agents(id) on delete cascade,version_id uuid references public.agent_versions(id) on delete set null,action text not null,before_config jsonb,after_config jsonb,actor_id uuid references auth.users(id) on delete set null,reason text,created_at timestamptz not null default now());
create table if not exists public.agent_messages (id uuid primary key default gen_random_uuid(),task_id uuid references public.tasks(id) on delete cascade,run_id uuid references public.task_runs(id) on delete cascade,from_agent text not null,to_agent text not null,message_type text not null,payload jsonb not null default '{}'::jsonb,sequence integer not null default 1,correlation_id uuid,created_at timestamptz not null default now());
create unique index if not exists agent_messages_sequence_idx on public.agent_messages(task_id,sequence) where task_id is not null;
create table if not exists public.agent_handoffs (id uuid primary key default gen_random_uuid(),task_id uuid not null references public.tasks(id) on delete cascade,run_id uuid references public.task_runs(id) on delete cascade,from_agent text not null,to_agent text not null,status text not null default 'requested',message_id uuid references public.agent_messages(id) on delete set null,payload jsonb not null default '{}'::jsonb,rejection_reason text,created_at timestamptz not null default now(),accepted_at timestamptz,completed_at timestamptz);
create table if not exists public.agent_sandbox_sessions (id uuid primary key default gen_random_uuid(),task_id uuid not null references public.tasks(id) on delete cascade,run_id uuid references public.task_runs(id) on delete cascade,agent_id uuid not null references public.agents(id) on delete restrict,owner_id uuid not null references auth.users(id) on delete cascade,status text not null default 'active',root_path text not null,expires_at timestamptz not null,created_at timestamptz not null default now(),ended_at timestamptz);
create table if not exists public.agent_sandbox_artifacts (id uuid primary key default gen_random_uuid(),session_id uuid not null references public.agent_sandbox_sessions(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,artifact_type text not null,path text not null,checksum text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(session_id,path));
create table if not exists public.agent_action_audit (id uuid primary key default gen_random_uuid(),agent_id uuid not null references public.agents(id) on delete cascade,agent_key text not null,task_id uuid references public.tasks(id) on delete set null,run_id uuid references public.task_runs(id) on delete set null,actor_id uuid references auth.users(id) on delete set null,action text not null,permission text not null,decision text not null,reason text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.agent_versions enable row level security; alter table public.agent_config_history enable row level security; alter table public.agent_messages enable row level security; alter table public.agent_handoffs enable row level security; alter table public.agent_sandbox_sessions enable row level security; alter table public.agent_sandbox_artifacts enable row level security; alter table public.agent_action_audit enable row level security;
-- All mutations are service-role only. Admin reads are exposed through server functions that re-check admin role.
revoke all on public.agent_versions,public.agent_config_history,public.agent_messages,public.agent_handoffs,public.agent_sandbox_sessions,public.agent_sandbox_artifacts,public.agent_action_audit from anon,authenticated; grant select on public.agent_versions,public.agent_config_history,public.agent_messages,public.agent_handoffs,public.agent_sandbox_sessions,public.agent_sandbox_artifacts,public.agent_action_audit to authenticated;
create or replace function public.agent_permission_check(p_agent_key text,p_permission text) returns table(allowed boolean,requires_approval boolean,reason text) language sql stable security definer set search_path=public as $$ select coalesce(p.allowed,false),coalesce(p.requires_approval,false),case when a.id is null then 'Unknown agent' when a.status <> 'enabled' then 'Agent is '||a.status::text when p.id is null then 'Permission not granted' when not p.allowed then 'Permission denied by registry' else null end from public.agents a left join public.agent_permissions p on p.agent_id=a.id and p.permission=p_permission where a.agent_key=p_agent_key; $$;
revoke all on function public.agent_permission_check(text,text) from public,anon,authenticated; grant execute on function public.agent_permission_check(text,text) to service_role;
create or replace function public.agent_lifecycle_transition(p_version_id uuid,p_target_state text,p_actor_id uuid,p_reason text default null) returns public.agent_versions language plpgsql security definer set search_path=public as $$ declare v public.agent_versions; prev public.agent_versions; begin if not public.has_role(p_actor_id,'admin') then raise exception 'Administrator authorization required'; end if; select * into v from public.agent_versions where id=p_version_id for update; if not found then raise exception 'Agent version not found'; end if; if p_target_state='validated' and v.lifecycle_state<>'draft' then raise exception 'Only draft versions can be validated'; end if; if p_target_state='tested' and v.lifecycle_state<>'validated' then raise exception 'Only validated versions can be tested'; end if; if p_target_state='active' and v.lifecycle_state<>'tested' then raise exception 'Only tested versions can be activated'; end if; if p_target_state not in ('validated','tested','active','disabled','maintenance','rolled_back') then raise exception 'Invalid lifecycle target'; end if; if p_target_state='active' then select * into prev from public.agent_versions where agent_id=v.agent_id and lifecycle_state='active' and id<>v.id order by activated_at desc nulls last limit 1; if prev.id is not null then update public.agent_versions set lifecycle_state='rolled_back',retired_at=now(),rollback_reason='Superseded by version '||v.version where id=prev.id; end if; update public.agents set config=v.definition,status='enabled',last_activity_at=now(),updated_at=now() where id=v.agent_id; update public.agent_versions set lifecycle_state='active',activated_by=p_actor_id,activated_at=now() where id=v.id; elsif p_target_state='maintenance' then update public.agents set status='maintenance',updated_at=now() where id=v.agent_id; update public.agent_versions set lifecycle_state='maintenance' where id=v.id; elsif p_target_state='disabled' then update public.agents set status='disabled',updated_at=now() where id=v.agent_id; update public.agent_versions set lifecycle_state='disabled',retired_at=coalesce(retired_at,now()) where id=v.id; elsif p_target_state='validated' then update public.agent_versions set lifecycle_state='validated',validated_by=p_actor_id,validated_at=now() where id=v.id; elsif p_target_state='tested' then update public.agent_versions set lifecycle_state='tested',tested_by=p_actor_id,tested_at=now() where id=v.id; else update public.agent_versions set lifecycle_state='rolled_back',retired_at=coalesce(retired_at,now()),rollback_reason=p_reason where id=v.id; end if; insert into public.agent_config_history(agent_id,version_id,action,after_config,actor_id,reason) values(v.agent_id,v.id,case when p_target_state='rolled_back' then 'rollback' else p_target_state end,v.definition,p_actor_id,p_reason); select * into v from public.agent_versions where id=v.id; return v; end; $$;
revoke all on function public.agent_lifecycle_transition(uuid,text,uuid,text) from public,anon,authenticated; grant execute on function public.agent_lifecycle_transition(uuid,text,uuid,text) to service_role;
