-- Phase N hardening: service-role worker compatibility and orchestrator activation.
insert into public.agent_permissions(agent_id,permission,allowed,requires_approval)
select a.id,'orchestration.execute',true,false from public.agents a where a.agent_key <> 'orchestrator'
on conflict(agent_id,permission) do update set allowed=excluded.allowed,requires_approval=excluded.requires_approval;
insert into public.agent_permissions(agent_id,permission,allowed,requires_approval)
select a.id,'orchestration.execute',true,false from public.agents a where a.agent_key='orchestrator'
on conflict(agent_id,permission) do update set allowed=excluded.allowed,requires_approval=excluded.requires_approval;
update public.agents set status='enabled',updated_at=now() where agent_key='orchestrator' and status='disabled';
create or replace function public.claim_orchestration_step(p_step_id uuid,p_actor_id uuid) returns public.orchestration_steps language plpgsql security definer set search_path=public as $$declare s public.orchestration_steps;p public.orchestration_plans;is_service boolean:=coalesce(auth.role(),'')='service_role';begin if not is_service and auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;select * into s from public.orchestration_steps where id=p_step_id for update;if not found then raise exception 'Step not found';end if;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') and not is_service then raise exception 'Forbidden';end if;if not public.orchestration_step_ready(s.id) then raise exception 'Step dependencies are not complete';end if;update public.orchestration_steps set status='running',worker_id=p_actor_id::text,lease_expires_at=now()+interval '10 minutes',started_at=coalesce(started_at,now()),updated_at=now() where id=s.id returning * into s;update public.orchestration_plans set status='running',started_at=coalesce(started_at,now()),updated_at=now() where id=s.plan_id and status in ('ready','draft');return s;end;$$;
create or replace function public.complete_orchestration_step(p_step_id uuid,p_status text,p_result jsonb,p_warnings jsonb,p_errors jsonb,p_actor_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare s public.orchestration_steps;p public.orchestration_plans;total integer;done integer;failed integer;agg jsonb;is_service boolean:=coalesce(auth.role(),'')='service_role';begin if not is_service and auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;if p_status not in ('completed','failed','waiting_approval','skipped','cancelled') then raise exception 'Invalid terminal step state';end if;select * into s from public.orchestration_steps where id=p_step_id for update;if not found then raise exception 'Step not found';end if;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') and not is_service then raise exception 'Forbidden';end if;update public.orchestration_steps set status=p_status,result=coalesce(p_result,'{}'),warnings=coalesce(p_warnings,'[]'),errors=coalesce(p_errors,'[]'),completed_at=case when p_status in ('completed','failed','skipped','cancelled') then now() else null end,lease_expires_at=null,updated_at=now() where id=s.id returning * into s;select count(*),count(*) filter(where status='completed'),count(*) filter(where status='failed') into total,done,failed from public.orchestration_steps where plan_id=s.plan_id;if failed>0 and exists(select 1 from public.orchestration_steps where plan_id=s.plan_id and critical and status='failed') then update public.orchestration_plans set status='failed',completed_at=now(),errors=coalesce(p_errors,'[]'),updated_at=now() where id=s.plan_id;elsif done=total then select jsonb_agg(jsonb_build_object('stepId',step_id,'agentKey',agent_key,'status',status,'result',result)) into agg from public.orchestration_steps where plan_id=s.plan_id;update public.orchestration_plans set status='completed',aggregated_result=coalesce(agg,'[]'),completed_at=now(),updated_at=now() where id=s.plan_id;else update public.orchestration_plans set status=case when exists(select 1 from public.orchestration_steps where plan_id=s.plan_id and status='waiting_approval') then 'waiting_approval' else 'running' end,updated_at=now() where id=s.plan_id;end if;return jsonb_build_object('step',to_jsonb(s),'plan',to_jsonb((select op from public.orchestration_plans op where id=s.plan_id)));end;$$;
