-- Phase Z2/security: privileged SECURITY DEFINER functions are server-only.
revoke execute on function public.aether_api_authenticate(text) from public, anon, authenticated;
grant execute on function public.aether_api_authenticate(text) to service_role;
revoke execute on function public.aether_api_z2_authenticate(text) from public, anon, authenticated;
grant execute on function public.aether_api_z2_authenticate(text) to service_role;
revoke execute on function public.aether_api_quota_reserve(uuid,uuid,integer) from public, anon, authenticated;
grant execute on function public.aether_api_quota_reserve(uuid,uuid,integer) to service_role;
revoke execute on function public.aether_api_quota_finalize(uuid,integer,boolean) from public, anon, authenticated;
grant execute on function public.aether_api_quota_finalize(uuid,integer,boolean) to service_role;
revoke execute on function public.aether_api_monthly_usage(uuid) from public, anon, authenticated;
grant execute on function public.aether_api_monthly_usage(uuid) to service_role;
revoke execute on function public.aether_api_controls_enabled() from public, anon, authenticated;
grant execute on function public.aether_api_controls_enabled() to service_role;
revoke execute on function public.aether_api_idempotency_claim(uuid,text) from public, anon, authenticated;
revoke execute on function public.aether_api_idempotency_claim(uuid,uuid,text,text) from public, anon, authenticated;
grant execute on function public.aether_api_idempotency_claim(uuid,uuid,text,text) to service_role;
revoke execute on function public.aether_api_idempotency_complete(uuid,text,uuid,jsonb,boolean) from public, anon, authenticated;
grant execute on function public.aether_api_idempotency_complete(uuid,text,uuid,jsonb,boolean) to service_role;
revoke execute on function public.aether_api_rate_allowed(uuid,integer) from public, anon, authenticated;
grant execute on function public.aether_api_rate_allowed(uuid,integer) to service_role;
revoke execute on function public.append_orchestration_event(uuid,text,text,uuid,uuid,uuid,uuid,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.append_orchestration_event(uuid,text,text,uuid,uuid,uuid,uuid,text,text,text,jsonb) to service_role;
revoke execute on function public.record_ai_stat_change(text,uuid,text,numeric,text,jsonb,uuid,uuid,uuid,uuid) from public, anon, authenticated;
grant execute on function public.record_ai_stat_change(text,uuid,text,numeric,text,jsonb,uuid,uuid,uuid,uuid) to service_role;
revoke execute on function public.consume_aether_research_rate_limit(uuid,text,integer,integer) from public, anon, authenticated;
grant execute on function public.consume_aether_research_rate_limit(uuid,text,integer,integer) to service_role;
revoke execute on function public.bridge_aax_knowledge_event_to_task_event() from public, anon, authenticated;
grant execute on function public.bridge_aax_knowledge_event_to_task_event() to service_role;
revoke execute on function public.activate_due_aax_releases() from public, anon, authenticated;
grant execute on function public.activate_due_aax_releases() to service_role;
revoke execute on function public.get_available_aax_model(text) from public, anon, authenticated;
grant execute on function public.get_available_aax_model(text) to service_role;
revoke execute on function public.bv_transfer_yons(uuid,uuid,bigint,text) from public, anon, authenticated;
grant execute on function public.bv_transfer_yons(uuid,uuid,bigint,text) to service_role;
revoke execute on function public.bv_place_bid(uuid,uuid,bigint) from public, anon, authenticated;
grant execute on function public.bv_place_bid(uuid,uuid,bigint) to service_role;
revoke execute on function public.bv_join_auction(uuid,uuid) from public, anon, authenticated;
grant execute on function public.bv_join_auction(uuid,uuid) to service_role;
revoke execute on function public.bv_start_auction(uuid,uuid) from public, anon, authenticated;
grant execute on function public.bv_start_auction(uuid,uuid) to service_role;
revoke execute on function public.bv_advance_auction(uuid,uuid) from public, anon, authenticated;
grant execute on function public.bv_advance_auction(uuid,uuid) to service_role;
revoke execute on function public.bv_settle_auction(uuid,uuid) from public, anon, authenticated;
grant execute on function public.bv_settle_auction(uuid,uuid) to service_role;
revoke execute on function public.bv_start_match(uuid,uuid) from public, anon, authenticated;
grant execute on function public.bv_start_match(uuid,uuid) to service_role;
revoke execute on function public.bv_complete_match(uuid,uuid,uuid) from public, anon, authenticated;
grant execute on function public.bv_complete_match(uuid,uuid,uuid) to service_role;
revoke execute on function public.bv_start_tournament(uuid,uuid) from public, anon, authenticated;
grant execute on function public.bv_start_tournament(uuid,uuid) to service_role;
