-- AETHER PHASE N: execution durability layered onto the existing Phase B orchestration model.
create table if not exists public.orchestration_step_runtime (
 id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.orchestration_plans(id) on delete cascade,
 orchestration_step_id uuid not null references public.orchestration_steps(id) on delete cascade,
 step_key text not null,sequence integer not null,agent_key text not null references public.agents(agent_key),
 depends_on_keys jsonb not null default '[]'::jsonb,requires_approval boolean not null default false,requires_verification boolean not null default false,
 max_retries integer not null default 2 check(max_retries between 0 and 20),retry_count integer not null default 0,
 timeout_ms bigint not null default 300000 check(timeout_ms between 1 and 18000000),critical boolean not null default false,
 status text not null default 'pending' check(status in ('pending','ready','running','waiting_approval','completed','failed','skipped','cancelled')),
 worker_id text,lease_expires_at timestamptz,result jsonb not null default '{}',warnings jsonb not null default '[]',errors jsonb not null default '[]',
 run_id uuid references public.task_runs(id) on delete set null,started_at timestamptz,completed_at timestamptz,updated_at timestamptz not null default now(),
 unique(plan_id,step_key),unique(plan_id,sequence)
);
create table if not exists public.orchestration_gates (
 id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.orchestration_plans(id) on delete cascade,
 runtime_step_id uuid not null references public.orchestration_step_runtime(id) on delete cascade,gate_type text not null check(gate_type in ('approval','verification','policy')),
 status text not null default 'pending' check(status in ('pending','approved','rejected','expired')),reason text,requested_by uuid references auth.users(id) on delete set null,
 decided_by uuid references auth.users(id) on delete set null,decision_note text,created_at timestamptz not null default now(),decided_at timestamptz
);
create index if not exists orchestration_runtime_plan_status_idx on public.orchestration_step_runtime(plan_id,status,sequence);
create index if not exists orchestration_runtime_lease_idx on public.orchestration_step_runtime(lease_expires_at) where status='running';
create index if not exists orchestration_gates_runtime_idx on public.orchestration_gates(runtime_step_id,status);
alter table public.orchestration_step_runtime enable row level security;alter table public.orchestration_gates enable row level security;
revoke all on public.orchestration_step_runtime,public.orchestration_gates from anon,authenticated;grant select on public.orchestration_step_runtime,public.orchestration_gates to authenticated;
create or replace function public.create_phase_n_orchestration_plan(p_task_id uuid,p_owner_id uuid,p_objective text,p_context jsonb,p_idempotency_key text,p_steps jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare t public.tasks;p public.orchestration_plans;existing jsonb;s jsonb;v_step public.orchestration_steps;v_runtime public.orchestration_step_runtime;seq integer:=0;sid text;akey text;deps jsonb;dep_id uuid;begin
if auth.uid() is distinct from p_owner_id then raise exception 'Forbidden: owner mismatch';end if;select * into t from public.tasks where id=p_task_id for update;if not found or t.owner_id<>p_owner_id then raise exception 'Task not found or not owned';end if;select to_jsonb(op) into existing from public.orchestration_plans op where op.task_id=p_task_id and op.owner_id=p_owner_id and op.intent=trim(p_objective) and op.status not in ('failed','cancelled','superseded') order by op.version desc limit 1;if existing is not null then return existing;end if;
insert into public.orchestration_plans(task_id,owner_id,title,intent,capabilities,context,agents,expected_outputs,risk_level,status,version) values(p_task_id,p_owner_id,trim(p_objective),trim(p_objective),'["multi_agent_orchestration"]'::jsonb,coalesce(p_context,'{}'::jsonb),(select coalesce(jsonb_agg(distinct s->>'agentKey'),'[]') from jsonb_array_elements(p_steps) s),(select coalesce(jsonb_agg(distinct s->>'title'),'[]') from jsonb_array_elements(p_steps) s),'low','validated',1) returning * into p;
for s in select * from jsonb_array_elements(p_steps) loop seq:=seq+1;sid=trim(coalesce(s->>'stepId',''));akey=trim(coalesce(s->>'agentKey',''));deps=coalesce(s->'dependsOn','[]'::jsonb);if sid='' or akey='' then raise exception 'Invalid orchestration step';end if;if akey='orchestrator' then raise exception 'Orchestrator cannot delegate to itself';end if;if not exists(select 1 from public.agents where agent_key=akey and status='enabled') then raise exception 'Agent is unavailable: %',akey;end if;insert into public.orchestration_steps(plan_id,task_id,sequence,step_key,kind,title,description,dependencies,agent_key,required_capabilities,input_refs,expected_output,approval_required,status) values(p.id,p_task_id,seq,sid,'agent',coalesce(nullif(trim(s->>'title'),''),sid),null, '{}',''||akey,'[]',coalesce(s->'input','{}'::jsonb),jsonb_build_object('agent',akey),coalesce((s->>'requiresApproval')::boolean,false),case when jsonb_array_length(deps)=0 then 'ready' else 'pending' end) returning * into v_step;
insert into public.orchestration_step_runtime(plan_id,orchestration_step_id,step_key,sequence,agent_key,depends_on_keys,requires_approval,requires_verification,max_retries,timeout_ms,critical) values(p.id,v_step.id,sid,seq,akey,deps,coalesce((s->>'requiresApproval')::boolean,false),coalesce((s->>'requiresVerification')::boolean,false),coalesce((s->>'maxRetries')::integer,2),coalesce((s->>'timeoutMs')::bigint,300000),coalesce((s->>'critical')::boolean,false)) returning * into v_runtime;
end loop;
perform public.append_orchestration_event(p.id,'plan.created','user',p_owner_id,p_task_id,null,null,'create','Phase N durable orchestration plan created','accepted',jsonb_build_object('stepCount',seq));return to_jsonb(p);end;$$;
revoke all on function public.create_phase_n_orchestration_plan(uuid,uuid,text,jsonb,text,jsonb) from public,anon;grant execute on function public.create_phase_n_orchestration_plan(uuid,uuid,text,jsonb,text,jsonb) to authenticated,service_role;
create or replace function public.claim_phase_n_step(p_runtime_step_id uuid,p_actor_id uuid) returns public.orchestration_step_runtime language plpgsql security definer set search_path=public as $$declare s public.orchestration_step_runtime;p public.orchestration_plans;begin if auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;select * into s from public.orchestration_step_runtime where id=p_runtime_step_id for update;if not found then raise exception 'Step not found';end if;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;if s.status<>'pending' and s.status<>'ready' then raise exception 'Step is not dispatchable';end if;if exists(select 1 from jsonb_array_elements_text(s.depends_on_keys) d where not exists(select 1 from public.orchestration_step_runtime x where x.plan_id=s.plan_id and x.step_key=d and x.status='completed')) then raise exception 'Step dependencies are not complete';end if;update public.orchestration_step_runtime set status='running',worker_id=p_actor_id::text,lease_expires_at=now()+interval '10 minutes',started_at=coalesce(started_at,now()),updated_at=now() where id=s.id returning * into s;update public.orchestration_steps set status='running',started_at=coalesce(started_at,now()) where id=s.orchestration_step_id;update public.orchestration_plans set status='executing',updated_at=now() where id=s.plan_id and status in ('draft','validated');perform public.append_orchestration_event(p.id,'step.claimed','user',p_actor_id,p.task_id,null,s.orchestration_step_id,'dispatch',null,'accepted',jsonb_build_object('stepKey',s.step_key,'agent',s.agent_key));return s;end;$$;
revoke all on function public.claim_phase_n_step(uuid,uuid) from public,anon;grant execute on function public.claim_phase_n_step(uuid,uuid) to authenticated,service_role;
create or replace function public.complete_phase_n_step(p_runtime_step_id uuid,p_status text,p_result jsonb,p_warnings jsonb,p_errors jsonb,p_actor_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare s public.orchestration_step_runtime;p public.orchestration_plans;total integer;done integer;failed integer;begin if auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;if p_status not in ('completed','failed','waiting_approval','skipped','cancelled') then raise exception 'Invalid terminal step state';end if;select * into s from public.orchestration_step_runtime where id=p_runtime_step_id for update;if not found then raise exception 'Step not found';end if;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;update public.orchestration_step_runtime set status=p_status,result=coalesce(p_result,'{}'),warnings=coalesce(p_warnings,'[]'),errors=coalesce(p_errors,'[]'),completed_at=case when p_status in ('completed','failed','skipped','cancelled') then now() else null end,lease_expires_at=null,updated_at=now() where id=s.id returning * into s;update public.orchestration_steps set status=p_status,result=coalesce(p_result,'{}'),error=case when jsonb_array_length(coalesce(p_errors,'[]'))>0 then p_errors->>0 else null end,completed_at=case when p_status in ('completed','failed','skipped','cancelled') then now() else null end where id=s.orchestration_step_id;select count(*),count(*) filter(where status='completed'),count(*) filter(where status='failed') into total,done,failed from public.orchestration_step_runtime where plan_id=s.plan_id;if failed>0 and exists(select 1 from public.orchestration_step_runtime where plan_id=s.plan_id and critical and status='failed') then update public.orchestration_plans set status='failed',completed_at=now(),updated_at=now() where id=s.plan_id;elsif done=total then update public.orchestration_plans set status='completed',completed_at=now(),updated_at=now() where id=s.plan_id;else update public.orchestration_plans set status=case when exists(select 1 from public.orchestration_step_runtime where plan_id=s.plan_id and status='waiting_approval') then 'awaiting_approval' else 'executing' end,updated_at=now() where id=s.plan_id;end if;perform public.append_orchestration_event(p.id,'step.completed', 'user',p_actor_id,p.task_id,null,s.orchestration_step_id,'complete',null,p_status,jsonb_build_object('stepKey',s.step_key,'result',coalesce(p_result,'{}')));return jsonb_build_object('step',to_jsonb(s),'plan',to_jsonb((select op from public.orchestration_plans op where id=s.plan_id)));end;$$;
revoke all on function public.complete_phase_n_step(uuid,text,jsonb,jsonb,jsonb,uuid) from public,anon;grant execute on function public.complete_phase_n_step(uuid,text,jsonb,jsonb,jsonb,uuid) to authenticated,service_role;
create or replace function public.request_phase_n_gate(p_runtime_step_id uuid,p_gate_type text,p_reason text,p_actor_id uuid) returns public.orchestration_gates language plpgsql security definer set search_path=public as $$declare s public.orchestration_step_runtime;p public.orchestration_plans;g public.orchestration_gates;begin if auth.uid() is distinct from p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;select * into s from public.orchestration_step_runtime where id=p_runtime_step_id;select * into p from public.orchestration_plans where id=s.plan_id;if p.owner_id<>p_actor_id and not public.has_role(p_actor_id,'admin') then raise exception 'Forbidden';end if;insert into public.orchestration_gates(plan_id,runtime_step_id,gate_type,reason,requested_by) values(p.id,s.id,p_gate_type,p_reason,p_actor_id) returning * into g;update public.orchestration_step_runtime set status='waiting_approval',updated_at=now() where id=s.id;update public.orchestration_steps set status='waiting_approval' where id=s.orchestration_step_id;update public.orchestration_plans set status='awaiting_approval',updated_at=now() where id=p.id;return g;end;$$;
revoke all on function public.request_phase_n_gate(uuid,text,text,uuid) from public,anon;grant execute on function public.request_phase_n_gate(uuid,text,text,uuid) to authenticated,service_role;
create or replace function public.recover_phase_n_steps() returns integer language plpgsql security definer set search_path=public as $$declare n integer;begin update public.orchestration_step_runtime set status='pending',worker_id=null,lease_expires_at=null,retry_count=retry_count+1,updated_at=now() where status='running' and lease_expires_at<now() and retry_count<max_retries;get diagnostics n=row_count;update public.orchestration_step_runtime set status='failed',errors=jsonb_build_array('orchestration step lease expired and retry budget exhausted'),updated_at=now() where status='running' and lease_expires_at<now() and retry_count>=max_retries;return n;end;$$;revoke all on function public.recover_phase_n_steps() from public,anon,authenticated;grant execute on function public.recover_phase_n_steps() to service_role;
