CREATE TABLE IF NOT EXISTS public.aether_project_files (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE, storage_path TEXT NOT NULL UNIQUE, filename TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes BIGINT NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 26214400), sha256 TEXT, extraction_status TEXT NOT NULL DEFAULT 'pending' CHECK (extraction_status IN ('pending','processing','completed','failed','unsupported')), extracted_text TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS aether_project_files_owner_project_idx ON public.aether_project_files(owner_id, project_id, created_at DESC);
ALTER TABLE public.aether_project_files ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.aether_project_files TO authenticated;
GRANT ALL ON public.aether_project_files TO service_role;
DROP POLICY IF EXISTS "own aether project files" ON public.aether_project_files;
CREATE POLICY "own aether project files" ON public.aether_project_files FOR ALL TO authenticated USING ((select auth.uid()) = owner_id) WITH CHECK ((select auth.uid()) = owner_id AND EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_id AND p.owner_id = (select auth.uid())));
DROP TRIGGER IF EXISTS aether_project_files_updated ON public.aether_project_files;
CREATE TRIGGER aether_project_files_updated BEFORE UPDATE ON public.aether_project_files FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES ('aether-project-files', 'aether-project-files', false, 26214400, ARRAY['application/pdf','text/plain','text/markdown','text/csv','application/json','application/xml','text/xml','text/html','image/jpeg','image/png','image/webp','image/gif']) ON CONFLICT (id) DO UPDATE SET public = false, file_size_limit = 26214400, allowed_mime_types = ARRAY['application/pdf','text/plain','text/markdown','text/csv','application/json','application/xml','text/xml','text/html','image/jpeg','image/png','image/webp','image/gif'];
DROP POLICY IF EXISTS "aether project files upload own" ON storage.objects;
CREATE POLICY "aether project files upload own" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'aether-project-files' AND split_part(name, '/', 1) = (select auth.uid())::text);
DROP POLICY IF EXISTS "aether project files read own" ON storage.objects;
CREATE POLICY "aether project files read own" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'aether-project-files' AND split_part(name, '/', 1) = (select auth.uid())::text);
DROP POLICY IF EXISTS "aether project files update own" ON storage.objects;
CREATE POLICY "aether project files update own" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'aether-project-files' AND split_part(name, '/', 1) = (select auth.uid())::text) WITH CHECK (bucket_id = 'aether-project-files' AND split_part(name, '/', 1) = (select auth.uid())::text);
DROP POLICY IF EXISTS "aether project files delete own" ON storage.objects;
CREATE POLICY "aether project files delete own" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'aether-project-files' AND split_part(name, '/', 1) = (select auth.uid())::text);
