// This file is automatically generated by the Aether auth integration.
import { createMiddleware } from '@tanstack/react-start'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { getRequest } from '@tanstack/react-start/server'
import { readAdminSessionCookies, writeAdminSessionCookies } from '@/lib/auth/admin.session.server'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env['SUPABASE_URL'];
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      throw new Error(`Missing Supabase environment variable(s): ${missing.join(', ')}`);
    }

    const request = getRequest();
    const requestHeader = request?.headers.get('authorization');
    const cookieSession = readAdminSessionCookies();

    let token = requestHeader?.startsWith('Bearer ')
      ? requestHeader.slice('Bearer '.length).trim()
      : cookieSession.accessToken;
    let refreshToken = cookieSession.refreshToken;

    if (!token) {
      throw new Error('Unauthorized: No authenticated session');
    }

    const makeClient = (accessToken?: string) => createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          ...(accessToken ? { headers: { Authorization: `Bearer ${accessToken}` } } : {}),
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      },
    );

    let supabase = makeClient(token);
    let { data, error } = await supabase.auth.getClaims(token);

    // Access tokens expire. If the browser still has the refresh token cookie,
    // transparently rotate the session and continue without forcing a login.
    if ((error || !data?.claims?.sub) && refreshToken) {
      const refreshClient = makeClient();
      const refreshed = await refreshClient.auth.refreshSession({ refresh_token: refreshToken });
      const refreshedSession = refreshed.data.session;

      if (refreshed.error || !refreshedSession) {
        throw new Error('Unauthorized: Session expired');
      }

      token = refreshedSession.access_token;
      refreshToken = refreshedSession.refresh_token;
      writeAdminSessionCookies(token, refreshToken);
      supabase = makeClient(token);
      ({ data, error } = await supabase.auth.getClaims(token));
    }

    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    const userId = data.claims.sub;
    if (!userId) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId,
        claims: data.claims,
      },
    });
  },
);
