// This file is automatically generated by the Aether auth integration.
import { createMiddleware } from '@tanstack/react-start'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { getRequest } from '@tanstack/react-start/server'
import { readAdminSessionCookies, writeAdminSessionCookies } from '@/lib/auth/admin.session.server'
import { supabaseAdmin } from '@/integrations/supabase/client.server'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function missingEnvError(): Error {
  const missing = [
    ...(!process.env['SUPABASE_URL'] ? ['SUPABASE_URL'] : []),
    ...(!process.env['SUPABASE_PUBLISHABLE_KEY'] ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
  ];
  return new Error(
    `Missing Supabase environment variable(s): ${missing.join(', ') || 'SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY'}. Set them in Vercel and redeploy.`,
  );
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env['SUPABASE_URL'];
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw missingEnvError();
    }

    const request = getRequest();
    const requestHeader = request?.headers.get('authorization');
    const cookieSession = readAdminSessionCookies();

    let token = requestHeader?.startsWith('Bearer ')
      ? requestHeader.slice('Bearer '.length).trim()
      : cookieSession.accessToken;
    let refreshToken = cookieSession.refreshToken;

    if (!token) {
      throw new Error('Unauthorized: No authenticated session');
    }

    const makeClient = (accessToken?: string) => createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          ...(accessToken ? { headers: { Authorization: `Bearer ${accessToken}` } } : {}),
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      },
    );

    let supabase = makeClient(token);
    let { data, error } = await supabase.auth.getClaims(token);

    // Access tokens expire. If the browser still has the refresh token cookie,
    // transparently rotate the session and continue without forcing a login.
    if ((error || !data?.claims?.sub) && refreshToken) {
      const refreshClient = makeClient();
      const refreshed = await refreshClient.auth.refreshSession({ refresh_token: refreshToken });
      const refreshedSession = refreshed.data.session;

      if (refreshed.error || !refreshedSession) {
        throw new Error('Unauthorized: Session expired');
      }

      token = refreshedSession.access_token;
      refreshToken = refreshedSession.refresh_token;
      writeAdminSessionCookies(token, refreshToken);
      supabase = makeClient(token);
      ({ data, error } = await supabase.auth.getClaims(token));
    }

    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    const userId = data.claims.sub;
    if (!userId) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    // Bootstrap administration is granted only after a successful Supabase Auth
    // login whose email exactly matches the server-only bootstrap identity.
    // This never demotes existing administrators and never trusts client claims
    // without first validating the access token above.
    const bootstrapEmail = process.env['AETHER_ADMIN_EMAIL']?.trim().toLowerCase();
    const authenticatedEmail = typeof data.claims.email === 'string' ? data.claims.email.trim().toLowerCase() : '';
    if (bootstrapEmail && authenticatedEmail && authenticatedEmail === bootstrapEmail) {
      const { error: bootstrapRoleError } = await supabaseAdmin
        .from('user_roles')
        .insert({ user_id: userId, role: 'admin' })
        .select('id')
        .maybeSingle();
      if (bootstrapRoleError && !/duplicate|unique/i.test(bootstrapRoleError.message)) {
        throw new Error('Bootstrap administrator provisioning failed');
      }
    }

    return next({
      context: {
        supabase,
        userId,
        claims: data.claims,
      },
    });
  },
);


/** Request middleware variant for createFileRoute({ server: { middleware } }). */
export const requireSupabaseAuthRequest = createMiddleware({ type: 'request' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env['SUPABASE_URL'];
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'];
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) throw missingEnvError();
    const request = getRequest();
    const requestHeader = request?.headers.get('authorization');
    const cookieSession = readAdminSessionCookies();
    let token = requestHeader?.startsWith('Bearer ') ? requestHeader.slice('Bearer '.length).trim() : cookieSession.accessToken;
    let refreshToken = cookieSession.refreshToken;
    if (!token) throw new Error('Unauthorized: No authenticated session');
    const makeClient = (accessToken?: string) => createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY), ...(accessToken ? { headers: { Authorization: `Bearer ${accessToken}` } } : {}) },
      auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
    });
    let supabase = makeClient(token);
    let { data, error } = await supabase.auth.getClaims(token);
    if ((error || !data?.claims?.sub) && refreshToken) {
      const refreshed = await makeClient().auth.refreshSession({ refresh_token: refreshToken });
      if (refreshed.error || !refreshed.data.session) throw new Error('Unauthorized: Session expired');
      token = refreshed.data.session.access_token;
      refreshToken = refreshed.data.session.refresh_token;
      writeAdminSessionCookies(token, refreshToken);
      supabase = makeClient(token);
      ({ data, error } = await supabase.auth.getClaims(token));
    }
    if (error || !data?.claims?.sub) throw new Error('Unauthorized: Invalid token');
    return next({ context: { supabase, userId: data.claims.sub, claims: data.claims } });
  },
);
