// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export function getSupabaseBrowserEnv(): { url: string; key: string } | null {
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return null;
  }
  return { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY };
}

export function isSupabaseConfigured(): boolean {
  return getSupabaseBrowserEnv() !== null;
}

function missingEnvMessage(): string {
  const missing = [
    ...(!(import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL']) ? ['SUPABASE_URL / VITE_SUPABASE_URL'] : []),
    ...(!(import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'])
      ? ['SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_PUBLISHABLE_KEY']
      : []),
  ];
  return `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in Vercel (Project Settings → Environment Variables) and redeploy.`;
}

function createSupabaseClient(): SupabaseClient<Database> {
  const env = getSupabaseBrowserEnv();
  if (!env) {
    const message = missingEnvMessage();
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(env.url, env.key, {
    global: {
      fetch: createSupabaseFetch(env.key),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

/**
 * Minimal no-op auth surface so public pages / middleware that only touch
 * supabase.auth.getSession / onAuthStateChange do not hard-crash the whole app
 * when env is missing. Real data operations still throw a clear config error.
 */
function createUnconfiguredStub(): SupabaseClient<Database> {
  const message = missingEnvMessage();
  const noopUnsubscribe = { data: { subscription: { unsubscribe() {} } } };

  const authStub = {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    onAuthStateChange: () => noopUnsubscribe,
    signInWithPassword: async () => {
      throw new Error(message);
    },
    signUp: async () => {
      throw new Error(message);
    },
    signOut: async () => ({ error: null }),
    exchangeCodeForSession: async () => {
      throw new Error(message);
    },
    refreshSession: async () => {
      throw new Error(message);
    },
  };

  return new Proxy({} as SupabaseClient<Database>, {
    get(_target, prop) {
      if (prop === 'auth') return authStub;
      if (prop === 'then') return undefined; // not a thenable
      throw new Error(message);
    },
  });
}

let _supabase: SupabaseClient<Database> | undefined;
let _unconfiguredLogged = false;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      if (!isSupabaseConfigured()) {
        if (!_unconfiguredLogged) {
          console.warn(`[Supabase] ${missingEnvMessage()}`);
          _unconfiguredLogged = true;
        }
        _supabase = createUnconfiguredStub();
      } else {
        _supabase = createSupabaseClient();
      }
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
