import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { createZ2ApiKey, getZ2AdminApiKeys, getZ2Models, getZ2SecurityAlerts, listZ2RequestRecords, revokeZ2ApiKey, setZ2ExternalIntelligenceEnabled, suspendZ2ApiKey } from "@/lib/aether/phase-z2-api";
import { rotateZ2ApiKeyGracefully } from "@/lib/aether/phase-z2-rotation";
import { recoverAnyZ2ApiKeySecret } from "@/lib/aether/phase-z2-secret-recovery";
import { updateAdminZ2ApiKey } from "@/lib/admin/phase-z2-controls";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
async function assertAdmin(userId: string) { const { data, error } = await supabaseAdmin.rpc("has_role", { _user_id: userId, _role: "admin" }); if (error) throw new Response("Unable to verify administrator authorization", { status: 500 }); if (!data) throw new Response("Forbidden", { status: 403 }); }
export const listAdminZ2ApiKeys = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await assertAdmin(context.userId); return getZ2AdminApiKeys(); });
export const listAdminZ2Models = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await assertAdmin(context.userId); return getZ2Models(); });
export const createAdminZ2ApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { name: string; applicationName: string; environment: "development" | "test" | "production"; modelKey: string; projectId?: string | null; expiresAt?: string | null; rateLimitPerMinute?: number; monthlyTokenLimit?: number; unlimitedTokens?: boolean; maxTokensPerRequest?: number; maxInputTokens?: number; maxOutputTokens?: number; allowWebResearch?: boolean; allowStreaming?: boolean }) => data).handler(async ({ context, data }) => { await assertAdmin(context.userId); return createZ2ApiKey({ ownerId: context.userId, actorId: context.userId, adminOverride: true, ...data }); });
export const getAdminZ2ApiKeySecret = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { keyId: string }) => data).handler(async ({ context, data }) => { await assertAdmin(context.userId); return recoverAnyZ2ApiKeySecret(context.userId, data.keyId); });
export const updateAdminZ2ApiKeyPolicy = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { keyId: string; patch: Record<string, unknown> }) => data).handler(async ({ context, data }) => { await assertAdmin(context.userId); return updateAdminZ2ApiKey(data.keyId, data.patch as any, context.userId); });
export const revokeAdminZ2ApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { keyId: string }) => data).handler(async ({ context, data }) => { await assertAdmin(context.userId); const { data: key } = await supabaseAdmin.from("aether_api_keys").select("owner_id").eq("id", data.keyId).eq("api_kind", "aax").maybeSingle(); if (!key) throw new Response("API key not found", { status: 404 }); return revokeZ2ApiKey(key.owner_id, data.keyId, context.userId, true); });
export const suspendAdminZ2ApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { keyId: string; suspend: boolean }) => data).handler(async ({ context, data }) => { await assertAdmin(context.userId); const { data: key, error } = await supabaseAdmin.from("aether_api_keys").select("owner_id").eq("id", data.keyId).eq("api_kind", "aax").maybeSingle(); if (error || !key) throw new Response("API key not found", { status: 404 }); return suspendZ2ApiKey(key.owner_id, data.keyId, context.userId, data.suspend, true); });
export const rotateAdminZ2ApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { keyId: string }) => data).handler(async ({ context, data }) => { await assertAdmin(context.userId); const { data: key } = await supabaseAdmin.from("aether_api_keys").select("owner_id").eq("id", data.keyId).eq("api_kind", "aax").maybeSingle(); if (!key) throw new Response("API key not found", { status: 404 }); return rotateZ2ApiKeyGracefully(key.owner_id, data.keyId, context.userId, true); });
export const listAdminZ2Requests = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).inputValidator((data?: { keyId?: string | null; ownerId?: string | null }) => data ?? {}).handler(async ({ context, data }) => { await assertAdmin(context.userId); if (data?.ownerId) return listZ2RequestRecords(data.ownerId, data.keyId); return supabaseAdmin.from("aether_api_request_records").select("id,request_id,api_key_id,owner_id,application_name,environment,model_key,provider,provider_model,response_validation_status,status_code,outcome,error_code,tokens_reserved,tokens_in,tokens_out,tokens_total,latency_ms,started_at,completed_at,created_at,metadata").order("created_at", { ascending: false }).limit(1000).then(({ data: rows, error }) => { if (error) throw new Response(error.message, { status: 500 }); return rows ?? []; }); });
export const getAdminZ2SecurityAlerts = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await assertAdmin(context.userId); return getZ2SecurityAlerts(); });
export const setAdminZ2IntelligenceEnabled = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((data: { enabled: boolean }) => data).handler(async ({ context, data }) => { await assertAdmin(context.userId); return setZ2ExternalIntelligenceEnabled(context.userId, data.enabled); });
