import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { revokeDeveloperApiKey, rotateDeveloperApiKey } from "@/lib/aether/developer-api";

async function admin(context: { supabase: unknown; userId: string }) {
  const db = context.supabase as SupabaseClient;
  const { data, error } = await db.rpc("has_role", { _user_id: context.userId, _role: "admin" });
  if (error) throw new Response("Unable to verify administrator authorization", { status: 500 });
  if (!data) throw new Response("Forbidden", { status: 403 });
}
async function audit(actorId: string, action: string, targetType: string, targetId: string | null, metadata: Record<string, unknown> = {}) {
  const { error } = await supabaseAdmin.from("audit_logs").insert({ actor_id: actorId, action, target_type: targetType, target_id: targetId, metadata });
  if (error) throw new Error(`Audit write failed: ${error.message}`);
}

export const getPhaseUUsers = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).inputValidator((d?: { search?: string }) => ({ search: String(d?.search ?? "").trim().slice(0, 100) })).handler(async ({ context, data }) => {
  await admin(context); const [{ data: profiles, error: pe }, { data: roles, error: re }, { data: auth, error: ae }] = await Promise.all([
    supabaseAdmin.from("profiles").select("id,display_name,created_at,onboarding_completed").order("created_at", { ascending: false }).limit(500),
    supabaseAdmin.from("user_roles").select("user_id,role"), supabaseAdmin.auth.admin.listUsers({ page: 1, perPage: 500 }),
  ]);
  if (pe || re || ae) throw new Response("Could not load users", { status: 500 });
  const emails = new Map((auth?.users ?? []).map(u => [u.id, u.email ?? null])); const last = new Map((auth?.users ?? []).map(u => [u.id, u.last_sign_in_at ?? null])); const banned = new Map((auth?.users ?? []).map(u => [u.id, u.banned_until ?? null]));
  const q = data.search.toLowerCase();
  return (profiles ?? []).filter(p => !q || `${p.display_name ?? ""} ${emails.get(p.id) ?? ""}`.toLowerCase().includes(q)).map(p => ({ ...p, email: emails.get(p.id) ?? null, lastSignInAt: last.get(p.id) ?? null, bannedUntil: banned.get(p.id) ?? null, roles: (roles ?? []).filter(r => r.user_id === p.id).map(r => r.role as string) }));
});

export const setPhaseUUserRole = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { userId: string; role: "admin" | "user" }) => ({ userId: String(d.userId), role: d.role })).handler(async ({ context, data }) => {
  await admin(context); if (data.userId === context.userId && data.role !== "admin") throw new Response("You cannot remove your own final administrator access", { status: 409 });
  if (data.role === "user") { const { count } = await supabaseAdmin.from("user_roles").select("user_id", { count: "exact", head: true }).eq("role", "admin"); if ((count ?? 0) <= 1) throw new Response("The final administrator cannot be demoted", { status: 409 }); }
  const { error } = await supabaseAdmin.from("user_roles").delete().eq("user_id", data.userId); if (error) throw new Response(error.message, { status: 500 });
  const { error: insertError } = await supabaseAdmin.from("user_roles").insert({ user_id: data.userId, role: data.role }); if (insertError) throw new Response(insertError.message, { status: 500 });
  await audit(context.userId, "admin.user_role_changed", "user", data.userId, { role: data.role }); return { ok: true };
});

export const setPhaseUUserBan = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { userId: string; banned: boolean }) => d).handler(async ({ context, data }) => {
  await admin(context); if (data.userId === context.userId && data.banned) throw new Response("You cannot ban your own administrator account", { status: 409 });
  const { error } = await supabaseAdmin.auth.admin.updateUserById(data.userId, { ban_duration: data.banned ? "876000h" : "none" }); if (error) throw new Response(error.message, { status: 500 });
  await audit(context.userId, data.banned ? "admin.user_banned" : "admin.user_unbanned", "user", data.userId); return { ok: true };
});

export const updatePhaseUModel = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { roleKey: string; status?: string; provider?: string; providerModel?: string; sortOrder?: number }) => ({ roleKey: String(d.roleKey).trim().slice(0, 100), status: d.status?.trim().slice(0, 50), provider: d.provider?.trim().slice(0, 100), providerModel: d.providerModel?.trim().slice(0, 200), sortOrder: d.sortOrder === undefined ? undefined : Math.max(-10000, Math.min(10000, Math.floor(d.sortOrder))) })).handler(async ({ context, data }) => {
  await admin(context); const patch: Record<string, unknown> = {}; if (data.status !== undefined) patch.status = data.status; if (data.provider !== undefined) patch.provider = data.provider; if (data.providerModel !== undefined) patch.provider_model = data.providerModel; if (data.sortOrder !== undefined) patch.sort_order = data.sortOrder; if (!Object.keys(patch).length) throw new Response("No model changes supplied", { status: 400 });
  const { data: row, error } = await supabaseAdmin.from("model_configs").update(patch).eq("role_key", data.roleKey).select("role_key,display_name,status,provider,provider_model,sort_order").maybeSingle(); if (error || !row) throw new Response(error?.message ?? "Model role not found", { status: 404 }); await audit(context.userId, "admin.model_updated", "model_config", data.roleKey, patch); return row;
});

export const updatePhaseUAgent = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { agentKey: string; status: "enabled" | "disabled" | "maintenance" }) => ({ agentKey: String(d.agentKey).trim().slice(0, 100), status: d.status })).handler(async ({ context, data }) => {
  await admin(context); const { data: row, error } = await supabaseAdmin.from("agents").update({ status: data.status, updated_at: new Date().toISOString() }).eq("agent_key", data.agentKey).select("id,agent_key,name,status").maybeSingle(); if (error || !row) throw new Response(error?.message ?? "Agent not found", { status: 404 }); await audit(context.userId, "admin.agent_status_changed", "agent", row.id, { agent_key: data.agentKey, status: data.status }); return row;
});

export const getPhaseUKnowledge = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await admin(context); const { data, error } = await supabaseAdmin.from("knowledge_entries").select("id,title,stage,confidence,tags,owner_id,current_version,approved_by,approved_at,created_at,updated_at").order("updated_at", { ascending: false }).limit(250); if (error) throw new Response(error.message, { status: 500 }); return data ?? []; });
export const decidePhaseUKnowledge = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { entryId: string; decision: "approve" | "reject"; reason?: string }) => ({ entryId: String(d.entryId), decision: d.decision, reason: d.reason?.trim().slice(0, 500) })).handler(async ({ context, data }) => { await admin(context); const { data: entry } = await supabaseAdmin.from("knowledge_entries").select("id,stage,current_version,owner_id,body").eq("id", data.entryId).maybeSingle(); if (!entry) throw new Response("Knowledge entry not found", { status: 404 }); if (data.decision === "reject") { const { error } = await supabaseAdmin.from("knowledge_entries").update({ stage: "sandbox", updated_at: new Date().toISOString() }).eq("id", data.entryId); if (error) throw new Response(error.message, { status: 500 }); await audit(context.userId, "knowledge.rejected", "knowledge_entries", data.entryId, { reason: data.reason ?? null }); return { ok: true, stage: "sandbox" }; }
  const next = Number(entry.current_version ?? 0) + 1; const { error: ve } = await supabaseAdmin.from("knowledge_versions").insert({ entry_id: data.entryId, owner_id: entry.owner_id, version: next, body: entry.body, stage: "production", change_note: data.reason ?? "Approved by administrator" }); if (ve) throw new Response(ve.message, { status: 500 }); const { error } = await supabaseAdmin.from("knowledge_entries").update({ stage: "production", current_version: next, approved_by: context.userId, approved_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", data.entryId); if (error) throw new Response(error.message, { status: 500 }); await audit(context.userId, "knowledge.approved", "knowledge_entries", data.entryId, { version: next, reason: data.reason ?? null }); return { ok: true, stage: "production", version: next }; });

export const getPhaseUResearch = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await admin(context); const { data, error } = await supabaseAdmin.from("aether_research_sessions").select("id,owner_id,project_id,query,status,source_count,diversity_score,task_id,run_id,created_at,completed_at,last_event_at").order("created_at", { ascending: false }).limit(200); if (error) throw new Response(error.message, { status: 500 }); return data ?? []; });

export const getPhaseUTasks = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await admin(context); const { data, error } = await supabaseAdmin.from("tasks").select("id,user_id,project_id,title,kind,status,progress,priority,detail,worker_id,retry_count,max_retries,next_attempt_at,deadline_at,created_at,updated_at,completed_at,last_error_code,last_error_message").order("created_at", { ascending: false }).limit(300); if (error) throw new Response(error.message, { status: 500 }); return data ?? []; });
export const cancelPhaseUTask = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { taskId: string; reason?: string }) => ({ taskId: String(d.taskId), reason: d.reason?.trim().slice(0, 500) || "Cancelled by administrator" })).handler(async ({ context, data }) => { await admin(context); const { data: task } = await supabaseAdmin.from("tasks").select("id,status").eq("id", data.taskId).maybeSingle(); if (!task) throw new Response("Task not found", { status: 404 }); if (["completed","failed","cancelled"].includes(task.status)) return { ok: true, alreadyFinal: true }; const { error } = await supabaseAdmin.from("tasks").update({ status: "cancelled", cancel_requested_at: new Date().toISOString(), cancellation_reason: data.reason, completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", data.taskId).eq("status", task.status); if (error) throw new Response(error.message, { status: 500 }); await audit(context.userId, "admin.task_cancelled", "task", data.taskId, { reason: data.reason }); return { ok: true }; });
export const retryPhaseUTask = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { taskId: string }) => ({ taskId: String(d.taskId) })).handler(async ({ context, data }) => { await admin(context); const { data: task } = await supabaseAdmin.from("tasks").select("id,user_id,status,retry_count,max_retries").eq("id", data.taskId).maybeSingle(); if (!task) throw new Response("Task not found", { status: 404 }); if (task.status !== "failed") throw new Response("Only failed tasks can be retried", { status: 409 }); if (Number(task.retry_count ?? 0) >= Number(task.max_retries ?? 0)) throw new Response("Retry budget exhausted", { status: 409 }); const { data: run } = await supabaseAdmin.from("task_runs").select("id,attempt,inputs,timeout_ms,max_retries").eq("task_id", data.taskId).order("attempt", { ascending: false }).limit(1).maybeSingle(); if (!run) throw new Response("No failed run exists for this task", { status: 409 }); const { data: newRun, error } = await supabaseAdmin.from("task_runs").insert({ task_id: task.id, owner_id: task.user_id, attempt: Number(run.attempt) + 1, status: "queued", inputs: run.inputs ?? {}, outputs: {}, retry_of: run.id, timeout_ms: run.timeout_ms, max_retries: run.max_retries, retry_count: 0 }).select("id,attempt,status").single(); if (error || !newRun) throw new Response(error?.message ?? "Could not create retry", { status: 500 }); await supabaseAdmin.from("tasks").update({ status: "queued", retry_count: Number(task.retry_count ?? 0) + 1, next_attempt_at: null, last_error_code: null, last_error_message: null, updated_at: new Date().toISOString() }).eq("id", task.id); await audit(context.userId, "admin.task_retried", "task", task.id, { new_run_id: newRun.id }); return newRun; });

export const getPhaseUApiKeys = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await admin(context); const { data, error } = await supabaseAdmin.from("aether_api_keys").select("id,owner_id,name,key_prefix,project_id,scopes,rate_limit_per_minute,expires_at,revoked_at,last_used_at,created_at,updated_at").order("created_at", { ascending: false }).limit(300); if (error) throw new Response(error.message, { status: 500 }); return data ?? []; });
export const revokePhaseUApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { keyId: string; ownerId: string }) => d).handler(async ({ context, data }) => { await admin(context); const result = await revokeDeveloperApiKey(data.ownerId, data.keyId); await audit(context.userId, "admin.api_key_revoked", "api_key", data.keyId, { owner_id: data.ownerId }); return result; });
export const rotatePhaseUApiKey = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { keyId: string; ownerId: string }) => d).handler(async ({ context, data }) => { await admin(context); const result = await rotateDeveloperApiKey(data.ownerId, data.keyId); await audit(context.userId, "admin.api_key_rotated", "api_key", data.keyId, { owner_id: data.ownerId, replacement_id: result.id }); return result; });

export const getPhaseUUsage = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await admin(context); const [{ data: api }, { data: runs }, { data: tasks }, { data: modelMetrics }, { data: agentMetrics }] = await Promise.all([
  supabaseAdmin.from("aether_api_logs").select("status_code,latency_ms,created_at").order("created_at", { ascending: false }).limit(5000),
  supabaseAdmin.from("task_runs").select("status,attempt,duration_ms,created_at,ended_at").order("created_at", { ascending: false }).limit(5000),
  supabaseAdmin.from("tasks").select("status,created_at").order("created_at", { ascending: false }).limit(5000),
  supabaseAdmin.from("model_productivity_metrics").select("model_role,request_count,completed_count,failed_count,productivity_percent,window_end").order("window_end", { ascending: false }).limit(1000),
  supabaseAdmin.from("agent_productivity_metrics").select("agent_key,source_run_count,completed_count,failed_count,productivity_percent,window_end").order("window_end", { ascending: false }).limit(1000),
 ]); const requests = api?.length ?? 0; const errors = (api ?? []).filter(x => Number(x.status_code) >= 400).length; const latency = (api ?? []).map(x => Number(x.latency_ms ?? 0)); const avgLatencyMs = latency.length ? Math.round(latency.reduce((a,b)=>a+b,0)/latency.length) : 0; const completedRuns=(runs??[]).filter(r=>r.status==='completed').length; return { requests, errors, errorRate: requests ? Number((errors/requests*100).toFixed(2)) : 0, avgLatencyMs, runs: runs?.length ?? 0, completedRuns, tasks: tasks?.length ?? 0, modelMetrics: modelMetrics ?? [], agentMetrics: agentMetrics ?? [] }; });

export const getPhaseUSystem = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await admin(context); const now = Date.now(); const [{ data: workers }, { data: quotas }, { data: tasks }, { data: models }, { data: agents }] = await Promise.all([
  supabaseAdmin.from("runtime_workers").select("worker_id,status,capacity,current_run_id,last_heartbeat_at,started_at,metadata,updated_at").order("worker_id"),
  supabaseAdmin.from("runtime_quotas").select("scope_type,scope_id,max_concurrent,max_queue_depth,max_runtime_ms,max_retries,updated_at").order("scope_type"),
  supabaseAdmin.from("tasks").select("status", { count: "exact", head: false }).limit(5000),
  supabaseAdmin.from("model_configs").select("role_key,display_name,status,provider,provider_model,sort_order").order("sort_order"),
  supabaseAdmin.from("agents").select("agent_key,name,status,last_activity_at").order("name"),
 ]); const healthyWorkers=(workers??[]).filter(w=>w.status!=="offline" && now-new Date(w.last_heartbeat_at).getTime()<120000).length; return { workers: workers ?? [], quotas: quotas ?? [], models: models ?? [], agents: agents ?? [], queueDepth:(tasks??[]).filter(t=>["queued","retrying","scheduled"].includes(t.status)).length, running:(tasks??[]).filter(t=>t.status==="running").length, healthyWorkers }; });

export const getPhaseUSettings = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { await admin(context); const { data, error } = await supabaseAdmin.from("platform_settings").select("key,value,description,updated_at,updated_by").order("key"); if (error) throw new Response(error.message, { status: 500 }); return data ?? []; });
export const setPhaseUSetting = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((d: { key: string; value: unknown; description?: string }) => ({ key: String(d.key).trim().slice(0, 120), value: d.value, description: d.description?.trim().slice(0, 500) })).handler(async ({ context, data }) => { await admin(context); if (!data.key) throw new Response("Setting key is required", { status: 400 }); const { data: row, error } = await supabaseAdmin.from("platform_settings").upsert({ key: data.key, value: data.value, description: data.description ?? null, updated_by: context.userId, updated_at: new Date().toISOString() }).select("key,value,description,updated_at,updated_by").single(); if (error || !row) throw new Response(error?.message ?? "Could not save setting", { status: 500 }); await audit(context.userId, "admin.platform_setting_changed", "platform_setting", data.key, { value: data.value }); return row; });
